package orchestrator

import (
	"fmt"
	"path"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/suruseas/opossum/internal/compose"
)

// Adapting a compose project
//
// Some compose files that run fine on Docker cannot start as written on Apple
// `container`, for reasons that are properties of the runtime rather than
// mistakes in the file (see the two patterns below). opossum already warns about
// these; `up --from-docker-compose` goes one step further and writes the fix into
// a `compose.opossum.yaml` overlay, so bringing an existing project over is one
// command instead of a read-warn-edit loop.
//
// Two rules keep this honest:
//   - The overlay is a separate file. The user's own compose files are never
//     modified, docker compose never reads the overlay, and deleting it undoes
//     everything.
//   - Only changes that preserve intent are automated (see adaptations below).
//     Anything that would alter what the project *means* — sharing semantics,
//     published ports, app-specific seeding — stays a warning.
//
// The generated YAML is written from templates rather than marshalled, because
// the comments are the point: the reader is often an agent that must decide what
// to do when the fix doesn't work, so every entry carries what changed, why (with
// the diagnostic code, to cross-reference AGENTS.md), how to verify it, what to do
// if it still fails, and how to undo it.

// Entry classes. The overlay is not only the fixes opossum made — it is the whole
// compatibility picture for this project, so a reader (often an agent) finds the
// problems opossum could NOT fix in the same place, instead of having to know they
// exist. Each class says how much opossum is claiming:
//
//	applied     — changed, and in effect. This is what made the project run.
//	suggestion  — a concrete change opossum will NOT make for you, written out but
//	              commented. It alters what the project means (where data lives,
//	              how services share it), so the call is yours; uncomment to apply.
//	note        — nothing to change here. The compose file can't express a fix;
//	              this records the fact so the failure isn't a mystery.
//
// The markers are stable strings on purpose: an agent greps them to tell
// opossum-generated entries from hand-written ones, and to tell what is live from
// what is merely proposed. Never change them without a migration.
const (
	overlayMarker = "[opossum --from-docker-compose]"
	// overlayGeneratedHeader is the first line of every overlay opossum writes. It
	// is how `destroy` tells a file it generated from one the user wrote by hand:
	// the overlay is a documented place for people to put their own adjustments, so
	// removing one without this line would be deleting someone's work.
	overlayGeneratedHeader = "# Generated by `opossum up --from-docker-compose`."
	suggestionMarker       = "[opossum suggestion — NOT APPLIED]"
	noteMarker             = "[opossum note]"
)

// entryClass is which of the three an overlay entry is.
type entryClass int

const (
	classApplied entryClass = iota
	classSuggestion
	classNote
)

// OverlayFileName is the overlay `up --from-docker-compose` generates.
const OverlayFileName = "compose.opossum.yaml"

// mysqlDataDir is MySQL/MariaDB's default data directory. Like Postgres's, a
// bind mount here fails because the image chowns it at startup.
const mysqlDataDir = "/var/lib/mysql"

// Other databases' data directories, each verified on the real runtime to fail
// the same way (the container starts, chowns its data directory, and exits):
//
//	clickhouse  chown: /var/lib/clickhouse/: Operation not permitted
//	redis       chown: .: Operation not permitted
//	mongo       chown: changing ownership of '/data/db': Operation not permitted
//
// The trap is that `up` reports success and exits 0: the container is created and
// started, and only then does the entrypoint fail its chown and exit. `opossum ps`
// immediately afterwards already shows it stopped.
const (
	clickhouseDataDir = "/var/lib/clickhouse"
	mongoDataDir      = "/data/db"
	// mongo's entrypoint chowns BOTH /data/db and /data/configdb, so fixing only
	// the first leaves the container dying on the second — with the change already
	// announced as the fix and the user's directory already detached.
	mongoConfigDir = "/data/configdb"
	redisDataDir   = "/data"
)

// dbDataDir pairs a database's data directory with the images that own it. Both
// halves are required to adapt a mount: the path alone is not evidence, because
// plenty of services legitimately mount a database's directory without being that
// database (a backup sidecar, an inspector, a migration tool). Rewriting one of
// those would swap its real data for an empty volume — silently, and in the user's
// favourite direction to not notice. So an adaptation only fires when the service
// is plausibly the database that chowns the path at startup.
type dbDataDir struct {
	path string
	// images are the image names of databases that own path, matched against the
	// LAST path segment of the image reference (registry, namespace, tag and digest
	// stripped). Matching the whole reference by substring would be far too loose:
	// `postgres-exporter`, `mysqldump-cron` and `mysql-backup-tool` all contain a
	// database's name while being exactly the sidecars this must not touch. An
	// unrecognized fork is only a missed fix; a wrong match swaps a service's real
	// data for an empty volume, so the list errs toward missing.
	images []string
}

var dbDataDirs = []dbDataDir{
	{postgresDataDir, []string{"postgres", "postgresql", "postgis", "timescaledb", "timescaledb-ha"}},
	{mysqlDataDir, []string{"mysql", "mysql-server", "mariadb", "percona", "percona-server", "percona-xtradb-cluster"}},
	{clickhouseDataDir, []string{"clickhouse", "clickhouse-server"}},
	{mongoDataDir, []string{"mongo", "mongodb", "mongodb-community-server"}},
	{mongoConfigDir, []string{"mongo", "mongodb", "mongodb-community-server"}},
	// `/data` is a generic path, so the image name carries all the weight here —
	// which is exactly why the match is exact rather than a substring.
	{redisDataDir, []string{"redis", "redis-stack", "redis-stack-server", "valkey"}},
}

// imageName reduces an image reference to its bare name: the last path segment,
// with any registry, namespace, tag and digest removed. `docker.io/library/
// postgres:16` and `bitnami/postgresql` become `postgres` and `postgresql`.
func imageName(ref string) string {
	s := strings.ToLower(strings.TrimSpace(ref))
	if i := strings.Index(s, "@"); i >= 0 {
		s = s[:i] // digest
	}
	if i := strings.LastIndex(s, ":"); i > strings.LastIndex(s, "/") {
		s = s[:i] // tag (a colon before the last slash is a registry port)
	}
	if i := strings.LastIndex(s, "/"); i >= 0 {
		s = s[i+1:]
	}
	return s
}

// serverCommands are the entrypoint arguments that make a database image behave
// as the server. The official images only chown their data directory on that
// path: redis chowns when argv[0] is `redis-server`, mongo when it's `mongod`.
// A sidecar built on the same image to dump, restore or poke at the data
// (`redis-cli`, `mongodump`, a shell) reads a bind mount perfectly well — and
// rewriting it would swap that service's real data for an empty volume.
var serverCommands = map[string]bool{
	"redis-server": true, "mongod": true, "clickhouse-server": true, "clickhouse": true,
	"postgres": true, "docker-entrypoint.sh": true,
	"mysqld": true, "mysqld_safe": true, "mariadbd": true,
}

// runsAsServer reports whether the service still runs its image's own server.
// An overridden entrypoint means we can't tell what it runs, so assume not; an
// overridden command is judged by its first word.
func runsAsServer(svc *compose.Service) bool {
	if len(svc.Entrypoint) > 0 {
		return false
	}
	if len(svc.Command) == 0 {
		return true // the image's default: the server
	}
	return serverCommands[pathLeaf(svc.Command[0])]
}

// ownsDataDir reports whether svc looks like the database that owns target — i.e.
// whether adapting that mount is safe. A service with a `build:` and no `image:`
// can't be identified, so it is left alone.
func ownsDataDir(svc *compose.Service, target string) bool {
	name := imageName(svc.Image)
	if name == "" {
		return false
	}
	for _, d := range dbDataDirs {
		if d.path != target {
			continue
		}
		for _, img := range d.images {
			if name == img {
				return true
			}
		}
	}
	return false
}

// Adaptation is one change the overlay makes, for reporting to the user.
type Adaptation struct {
	Service string
	Code    string // the diagnostic code this relates to, e.g. "OPSM-101"
	Summary string // one line, in the user's terms
	// Kind is "applied", "suggestion" or "note" — what opossum is claiming. The
	// caller reports each group separately, because calling a note a "change"
	// would overstate what the overlay did.
	Kind string
}

// serviceAdaptation is the internal, renderable form: the YAML fragment for one
// service plus the comment block that explains it.
type serviceAdaptation struct {
	Adaptation
	class   entryClass
	comment string // the full comment block (already prefixed with "# ")
	// block is the service-level YAML key this adaptation writes under (e.g.
	// "volumes"), and entries are its indented items. Kept apart rather than as
	// ready-made lines so a service with two adaptations under the same key emits
	// that key once — YAML rejects a mapping with the same key twice, and the
	// overlay would not load at all.
	block   string
	entries []string
	volume  string // a top-level named volume to declare, if any
}

// PlanOverlay inspects the resolved project (base + any override already merged)
// and returns the text of a compose.opossum.yaml that adapts it to run on Apple
// `container`, plus a description of each change. It returns ("", nil) when
// nothing needs adapting.
//
// Detection runs on the *resolved* project on purpose: an override may already
// have applied the fix by hand, and adapting on top of that would be noise (or
// wrong).
func (o *Orchestrator) PlanOverlay() (string, []Adaptation) {
	names := make([]string, 0, len(o.Project.Services))
	for name := range o.Project.Services {
		names = append(names, name)
	}
	sort.Strings(names) // deterministic output

	claimed := map[string]bool{} // volume names this plan has already taken
	var plans []serviceAdaptation
	for _, name := range names {
		plans = append(plans, o.adaptService(name, o.Project.Services[name], claimed)...)
	}
	plans = append(plans, o.suggestSharedVolumeFix(names)...)
	plans = append(plans, o.suggestObservedChownFailures(plans, claimed)...)
	if len(plans) == 0 {
		return "", nil
	}
	return renderOverlay(plans), summarize(plans)
}

func summarize(plans []serviceAdaptation) []Adaptation {
	out := make([]Adaptation, 0, len(plans))
	for _, p := range plans {
		a := p.Adaptation
		switch p.class {
		case classSuggestion:
			a.Kind = "suggestion"
		case classNote:
			a.Kind = "note"
		default:
			a.Kind = "applied"
		}
		out = append(out, a)
	}
	return out
}

// adaptService returns the adaptations for one service. A Postgres service whose
// data directory is a bind mount needs both fixes: the mount has to become a named
// volume (bind mounts can't be chowned), and PGDATA then has to point at a
// subdirectory of it (a named volume mount point isn't empty). Handling only one
// would move the failure rather than remove it.
func (o *Orchestrator) adaptService(name string, svc *compose.Service, claimed map[string]bool) []serviceAdaptation {
	if svc == nil {
		return nil
	}
	var out []serviceAdaptation
	swaps, swappedPostgres := o.adaptBindMountedDataDir(name, svc, claimed)
	out = append(out, swaps...)
	if p, ok := o.adaptPGDATA(name, svc, swappedPostgres); ok {
		out = append(out, p)
	}
	out = append(out, o.noteUnfixable(name, svc)...)
	return out
}

// noteUnfixable records the problems opossum finds but will not change: things the
// compose file simply can't express a fix for. Writing them down is the point —
// otherwise the user meets the failure with no idea opossum already knew about it.
func (o *Orchestrator) noteUnfixable(name string, svc *compose.Service) []serviceAdaptation {
	var out []serviceAdaptation
	note := func(code diagCode, what string, why, next []string) {
		out = append(out, serviceAdaptation{
			Adaptation: Adaptation{Service: name, Code: string(code), Summary: what},
			class:      classNote,
			comment:    noteBlock(fmt.Sprintf("%s service %q: %s", noteMarker, esc(name), esc(what)), why, next),
		})
	}
	// `on-failure` asks for something the runtime can't answer. The overlay is
	// where a migrating user meets the compatibility surprises, so the one policy
	// opossum only approximates belongs here too — not just in `config` and the
	// docs, which the person moving a project over may never open.
	if pol, err := svc.RestartPolicy(); err == nil && pol.Mode == compose.RestartOnFailure {
		note(codeSupervisorAction, "uses `restart: on-failure`, which opossum can only approximate",
			[]string{
				"`on-failure` means restart only if the service failed. Apple container",
				"does not report a container's exit code, so a crash and a clean exit look",
				"the same from outside. opossum treats any exit as a failure, retries a few",
				"times and then stops — rather than restarting a service that may have",
				"finished on purpose. `always` and `unless-stopped` are honoured exactly.",
			},
			[]string{
				"if this service is meant to keep running, `restart: always` says so",
				"exactly. If it is meant to finish, another service can wait for it with",
				"`depends_on: {condition: service_completed_successfully}`, which also",
				"excludes it from supervision.",
			})
	}
	for _, v := range svc.Volumes {
		src, target, _, ok := splitMount(v)
		if !ok {
			continue
		}
		switch {
		case strings.Contains(src, "docker.sock") || strings.Contains(target, "docker.sock"):
			note(codeDockerSocket, "mounts the Docker socket, which Apple container does not have",
				[]string{
					"Apple container is not the Docker daemon and exposes no socket, so a",
					"tool that drives Docker through it cannot work here at all. There is no",
					"compose change that fixes this.",
				},
				[]string{
					"drop the service, or run it against a real Docker daemon elsewhere.",
				})
		case isHostDevicePath(src):
			note(codeHostDeviceMount, fmt.Sprintf("mounts the host path %s, which is a device or session socket", src),
				[]string{
					"Each container is its own VM, so host devices and session sockets (X11,",
					"PulseAudio, /dev/dri) are not reachable from inside it. The mount will",
					"exist but have nothing behind it.",
				},
				[]string{
					"expect this service's device-dependent features not to work; there is no",
					"compose change that grants a VM access to the host's devices.",
				})
		}
	}
	return out
}

// isHostDevicePath reports whether a host path is a device node or a session
// socket directory — things a per-container VM has no route to.
func isHostDevicePath(src string) bool {
	for _, p := range []string{"/dev/", "/tmp/.X11-unix", "/run/user/", "/run/pulse", "/var/run/dbus"} {
		if src == strings.TrimSuffix(p, "/") || strings.HasPrefix(src, p) {
			return true
		}
	}
	return false
}

// noteBlock renders a note: what it is, why nothing can be done, and what to
// expect instead. Notes carry no YAML, so they end at "What to expect".
func noteBlock(what string, why, expect []string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n", what)
	section := func(label string, lines []string) {
		for i, l := range lines {
			if i == 0 {
				fmt.Fprintf(&b, "# %s: %s\n", label, l)
			} else {
				fmt.Fprintf(&b, "#   %s\n", l)
			}
		}
	}
	section("Why", why)
	section("What to expect", expect)
	return b.String()
}

// adaptBindMountedDataDir swaps a bind-mounted database data directory for a named
// volume. This MOVES WHERE THE DATA LIVES (out of the host directory, into a
// volume the runtime manages), so the generated comment says so plainly — it's the
// one automated change a user could be surprised by.
func (o *Orchestrator) adaptBindMountedDataDir(name string, svc *compose.Service, claimed map[string]bool) ([]serviceAdaptation, bool) {
	var out []serviceAdaptation
	swappedPostgres := false
	for _, v := range svc.Volumes {
		src, target, mode, ok := splitMount(v)
		if !ok || !isHostPath(src) {
			continue
		}
		// Both must hold: the path is a database data directory AND this service
		// is the database that owns it. A read-only mount rules it out — a database
		// can't run on one, so the service is something else looking at the files.
		if !ownsDataDir(svc, target) || readOnlyMount(mode) || !runsAsServer(svc) {
			continue
		}
		// Another service on the same host directory means deliberate sharing;
		// splitting it is the user's call, not ours.
		if o.sharesHostDataDir(name, src) {
			continue
		}
		// The service's main data directory gets the plain "<svc>-data"; a second one
		// (mongo's /data/configdb) is named after its path, so the two are telling
		// apart at a glance and can't collide.
		base := compose.SanitizeName(name) + "-data"
		if len(out) > 0 {
			base = compose.SanitizeName(name) + "-" + compose.SanitizeName(pathLeaf(target))
		}
		vol := o.freeVolumeName(base, claimed)
		if target == postgresDataDir {
			swappedPostgres = true
		}
		out = append(out, serviceAdaptation{
			Adaptation: Adaptation{
				Service: name,
				Code:    string(codeBindDataDirChown),
				Summary: fmt.Sprintf("service %q: data directory %s moved from the host path %s to a named volume %q", name, target, src, vol),
			},
			comment: commentBlock(
				fmt.Sprintf("%s service %q: %s now uses the named volume %q instead of the host path %q.", overlayMarker, esc(name), esc(target), vol, esc(src)),
				[]string{
					"Apple container bind-mounts host directories read-write but host-owned,",
					"and they cannot be chowned from inside the container. Official database",
					"images chown their data directory at startup, so they fail on a bind",
					fmt.Sprintf("mount. A named volume is chownable. Diagnostic: %s.", codeBindDataDirChown),
					"NOTE: this changes where the data lives. The database now writes into",
					fmt.Sprintf("the volume, not into %s. Existing data in that directory is", esc(src)),
					"not copied — it is left untouched on the host.",
				},
				[]string{
					fmt.Sprintf("after `opossum up`, `opossum logs %s` should show the database", name),
					"initializing and accepting connections, with no chown error.",
				},
				[]string{
					fmt.Sprintf("run `opossum logs %s` and `opossum doctor`, then match the error", name),
					"against the failure-signatures table in AGENTS.md.",
				},
			),
			block:   "volumes",
			entries: []string{fmt.Sprintf("      - %s:%s", esc(vol), esc(target))},
			volume:  vol,
		})
	}
	return out, swappedPostgres
}

// pathLeaf is the last non-empty path element ("/data/configdb" -> "configdb"),
// used to keep a second volume on the same service distinguishable.
func pathLeaf(p string) string {
	parts := strings.Split(strings.Trim(p, "/"), "/")
	if len(parts) == 0 {
		return "data"
	}
	return parts[len(parts)-1]
}

// adaptPGDATA points PGDATA at a subdirectory when Postgres's data directory is a
// named volume. Purely additive (an environment variable), and the data stays
// inside the same volume — the safest fix in the set, and the most common need.
//
// It fires when the data dir is already a named volume, and also when
// adaptBindMountedDataDir is about to make it one.
//
// It keeps firing even though opossum now clears `lost+found` out of the volumes
// it creates, which is what made the plain mount work. The overlay is a file: it
// outlives the volume it was written for, and is read again on machines and days
// where that volume is not the one opossum made. Dropping the line would also
// strand a cluster already initialised one level down — the next up would find the
// mount point holding `pgdata/`, which is not empty either. A durable artefact
// should not encode a fact that is only true of the moment it was written.
func (o *Orchestrator) adaptPGDATA(name string, svc *compose.Service, willBeNamedVolume bool) (serviceAdaptation, bool) {
	// Any PGDATA the user set is theirs. Checking only for "a subdirectory of the
	// default datadir" would treat a deliberate PGDATA elsewhere (a second volume,
	// say) as unfixed and overwrite it — pointing Postgres at an empty directory
	// and initdb'ing a new cluster, while their real one sits untouched and
	// unreachable. Silence beats a fix here.
	if hasPGDATA(svc) {
		return serviceAdaptation{}, false
	}
	// A mount below the data directory would be stranded above the new PGDATA.
	if hasNestedDataDirMount(svc) {
		return serviceAdaptation{}, false
	}
	for _, v := range svc.Volumes {
		src, target, mode, ok := splitMount(v)
		if !ok || target != postgresDataDir {
			continue
		}
		// Only the Postgres that owns the directory, and never a read-only mount
		// (a database can't run on one) — same reasoning as the bind-mount fix.
		if !ownsDataDir(svc, target) || readOnlyMount(mode) {
			continue
		}
		// The redirection exists because a NAMED VOLUME's mount point isn't empty.
		// It must fire for a named volume today, or for a host path this overlay is
		// converting into one — but never for a bind mount that stays a bind mount
		// (its directory is the user's, initdb is happy with it, and moving PGDATA
		// would just relocate their data a level down for no reason).
		if isHostPath(src) && !willBeNamedVolume {
			continue
		}
		if !isNamedVolume(src) && !isHostPath(src) {
			continue
		}
		if isNamedVolume(src) && o.isExternalVolume(src) {
			continue // an external volume is the user's to manage
		}
		sub := postgresDataDir + "/pgdata"
		return serviceAdaptation{
			Adaptation: Adaptation{
				Service: name,
				Code:    string(codePGDATADatadir),
				Summary: fmt.Sprintf("service %q: PGDATA pointed at %s (a subdirectory of the volume)", name, sub),
			},
			comment: commentBlock(
				fmt.Sprintf("%s service %q: PGDATA moved to a subdirectory of the data volume.", overlayMarker, esc(name)),
				[]string{
					"Apple container attaches a named volume as a filesystem mount point, so",
					"the directory can hold lost+found, which Postgres initdb refuses to",
					fmt.Sprintf("initialize into. Diagnostic: %s. opossum clears that from the", codePGDATADatadir),
					"volumes it creates, so this is belt and braces: it also covers a volume",
					"made before that, or by another tool. The data still lives inside the",
					"same volume, one level down.",
				},
				[]string{
					fmt.Sprintf("after `opossum up`, `opossum logs %s` should show initdb completing", name),
					"and the database accepting connections.",
				},
				[]string{
					fmt.Sprintf("run `opossum logs %s` and `opossum doctor`, then match the error", name),
					"against the failure-signatures table in AGENTS.md.",
				},
			),
			block:   "environment",
			entries: []string{fmt.Sprintf("      PGDATA: %s", sub)},
		}, true
	}
	return serviceAdaptation{}, false
}

// commentBlock renders the five-part contract every generated entry carries. The
// shape is fixed so a reader (often an agent) can rely on it: what changed, why it
// was needed, how to confirm it worked, what to do if it didn't, and how to undo
// it. Wrapped lines are indented so the block stays readable.
func commentBlock(what string, why, verify, ifFails []string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n", what)
	writeSection := func(label string, lines []string) {
		for i, l := range lines {
			if i == 0 {
				fmt.Fprintf(&b, "# %s: %s\n", label, l)
			} else {
				fmt.Fprintf(&b, "#   %s\n", l)
			}
		}
	}
	writeSection("Why", why)
	writeSection("Verify", verify)
	writeSection("If this still fails", ifFails)
	writeSection("To undo", []string{
		"delete this entry, or this whole file. Your original compose file was",
		"not modified, and docker compose never reads this file.",
	})
	return b.String()
}

// renderOverlay assembles the overlay file: a header explaining what the file is,
// then one commented entry per adaptation, grouped under each service, then any
// named volumes the adaptations introduced.
func renderOverlay(plans []serviceAdaptation) string {
	var applied, suggestions, notes []serviceAdaptation
	for _, p := range plans {
		switch p.class {
		case classSuggestion:
			suggestions = append(suggestions, p)
		case classNote:
			notes = append(notes, p)
		default:
			applied = append(applied, p)
		}
	}

	var b strings.Builder
	b.WriteString(overlayGeneratedHeader + "\n" +
		"#\n" +
		"# This file adapts the compose project to Apple's `container` runtime. opossum\n" +
		"# merges it last, at the highest precedence, on top of your compose file and any\n" +
		"# compose.override.yaml. docker compose does not read this file, so the same\n" +
		"# directory still works with both tools and your own files are unchanged.\n" +
		"#\n" +
		"# Entries come in three kinds, and each says which it is:\n" +
		"#   " + overlayMarker + "  — applied. This is live.\n" +
		"#   " + suggestionMarker + " — written out but commented; uncomment to apply.\n" +
		"#   " + noteMarker + "                    — nothing to change; recorded so the\n" +
		"#                                        failure isn't a mystery.\n" +
		"#\n" +
		"# Every entry says what it is about, why, how to check it, and how to undo it.\n" +
		"# Edit or delete anything here — opossum will not overwrite this file.\n")

	if len(applied) > 0 {
		b.WriteString("\nservices:\n")
		b.WriteString(renderServiceBlocks(applied, false))
	}
	if len(suggestions) > 0 {
		b.WriteString("\n# ── Suggestions ─────────────────────────────────────────────────────────\n" +
			"# opossum did NOT make these changes: each alters what the project means, so\n" +
			"# the call is yours. Uncommenting a whole block applies it (the `services:`\n" +
			"# line included — this file is merged like any compose file).\n")
		b.WriteString(commentOut("services:\n" + renderServiceBlocks(suggestions, true)))
	}
	if len(notes) > 0 {
		b.WriteString("\n# ── Notes ───────────────────────────────────────────────────────────────\n" +
			"# Nothing to change for these: the compose file can't express a fix.\n")
		for _, n := range notes {
			b.WriteString(strings.TrimRight(n.comment, "\n") + "\n")
		}
	}

	var volumes []string
	for _, p := range applied {
		if p.volume != "" {
			volumes = append(volumes, p.volume)
		}
	}
	if len(volumes) > 0 {
		sort.Strings(volumes)
		b.WriteString("\nvolumes:\n")
		for _, v := range volumes {
			fmt.Fprintf(&b, "  %s: {}\n", esc(yamlKey(v)))
		}
	}
	return b.String()
}

// renderServiceBlocks lays entries out as compose, grouped by service, each
// preceded by its comment. Two entries on one service share a single YAML key.
func renderServiceBlocks(plans []serviceAdaptation, inlineVolumes bool) string {
	type group struct {
		name     string
		comments []string
		blocks   []string
		entries  map[string][]string
		volumes  []string
	}
	var groups []group
	index := map[string]int{}
	for _, p := range plans {
		i, ok := index[p.Service]
		if !ok {
			index[p.Service] = len(groups)
			groups = append(groups, group{name: p.Service, entries: map[string][]string{}})
			i = len(groups) - 1
		}
		groups[i].comments = append(groups[i].comments, p.comment)
		if p.block == "" {
			continue
		}
		if _, seen := groups[i].entries[p.block]; !seen {
			groups[i].blocks = append(groups[i].blocks, p.block)
		}
		groups[i].entries[p.block] = append(groups[i].entries[p.block], p.entries...)
		if p.volume != "" {
			groups[i].volumes = append(groups[i].volumes, p.volume)
		}
	}
	var b strings.Builder
	for _, g := range groups {
		for _, c := range g.comments {
			for _, line := range strings.Split(strings.TrimRight(c, "\n"), "\n") {
				b.WriteString("  " + line + "\n")
			}
		}
		fmt.Fprintf(&b, "  %s:\n", esc(yamlKey(g.name)))
		for _, blk := range g.blocks {
			fmt.Fprintf(&b, "    %s:\n", blk)
			for _, e := range g.entries[blk] {
				b.WriteString(e + "\n")
			}
		}
	}
	// A SUGGESTION that introduces volumes has to carry their declarations, or
	// uncommenting the block would leave the project referencing volumes nobody
	// declared. They go in ONE section after every service — a `volumes:` key
	// emitted between services would either be a duplicate top-level key (invalid
	// YAML) or, worse, swallow the services that follow it as if they were volume
	// declarations, so the later suggestions would silently do nothing.
	if inlineVolumes {
		var all []string
		seen := map[string]bool{}
		for _, g := range groups {
			for _, v := range g.volumes {
				if !seen[v] {
					seen[v] = true
					all = append(all, v)
				}
			}
		}
		if len(all) > 0 {
			sort.Strings(all)
			b.WriteString("volumes:\n")
			for _, v := range all {
				fmt.Fprintf(&b, "  %s: {}\n", esc(yamlKey(v)))
			}
		}
	}
	return b.String()
}

// commentOut prefixes every line with "# " so a block of real YAML sits inert in
// the file until someone uncomments it.
func commentOut(s string) string {
	var b strings.Builder
	for _, line := range strings.Split(strings.TrimRight(s, "\n"), "\n") {
		if line == "" {
			b.WriteString("#\n")
			continue
		}
		b.WriteString("# " + line + "\n")
	}
	return b.String()
}

// splitMount splits a short-form volumes entry into source, target and mode.
// Entries with no source (an anonymous volume) return ok=false: there's no host
// path or named volume to reason about.
func splitMount(v string) (src, target, mode string, ok bool) {
	parts := strings.SplitN(v, ":", 3)
	if len(parts) < 2 {
		return "", "", "", false
	}
	if len(parts) == 3 {
		mode = parts[2]
	}
	return parts[0], strings.TrimRight(parts[1], "/"), mode, true
}

// readOnlyMount reports whether a mount is read-only. A read-only mount is strong
// evidence the service is NOT the database that owns the directory — a database
// can't run on one — so those are never adapted.
func readOnlyMount(mode string) bool {
	for _, opt := range strings.Split(mode, ",") {
		if strings.TrimSpace(opt) == "ro" {
			return true
		}
	}
	return false
}

// esc escapes a user-derived string for the generated file. opossum interpolates
// ${VAR} over the raw text before parsing — comments included — so an unescaped
// `$` from a host path would be expanded on the next load, or fail the load
// outright ("unterminated variable reference") and leave the project unusable.
func esc(s string) string { return strings.ReplaceAll(s, "$", "$$") }

// plainYAMLKey matches names safe to emit as a bare YAML key.
var plainYAMLKey = regexp.MustCompile(`^[A-Za-z][A-Za-z0-9_-]*$`)

// yamlBareUnsafe are names that look like a bare scalar but parse as something
// else (a bool, a null). A service legitimately named `on` or `no` would silently
// become a different key — or vanish — when the merged tree round-trips through
// YAML, so they must be quoted.
var yamlBareUnsafe = map[string]bool{
	"y": true, "n": true, "yes": true, "no": true, "true": true, "false": true,
	"on": true, "off": true, "null": true, "nil": true, "~": true,
}

// yamlKey renders a name as a YAML mapping key, quoting whatever wouldn't survive
// as a bare scalar. Compose allows service names (digits, dots, reserved words)
// that a bare key would mangle — writing those unquoted produces a file that
// silently renames or drops the service.
func yamlKey(s string) string {
	if plainYAMLKey.MatchString(s) && !yamlBareUnsafe[strings.ToLower(s)] {
		return s
	}
	return strconv.Quote(s)
}

// hasPGDATA reports whether the service sets PGDATA at all — including the
// pass-through forms (`- PGDATA` in a list, `PGDATA:` with no value in a map),
// which are stored as a bare name with no `=` and take their value from the host
// environment. Missing those would overwrite a PGDATA the user is supplying at run
// time, which is the exact damage this guard exists to prevent.
func hasPGDATA(svc *compose.Service) bool {
	for _, e := range svc.Environment {
		if e == "PGDATA" || strings.HasPrefix(e, "PGDATA=") {
			return true
		}
	}
	return false
}

// servicesSharingHostDir names the other services mounting the same host
// directory. The applied path only needs to know whether any exist (it refuses);
// a failure-driven suggestion is kept — the crash is real — so it has to say who
// else is reading the directory it proposes detaching.
func (o *Orchestrator) servicesSharingHostDir(self, src string) []string {
	var peers []string
	for name, svc := range o.Project.Services {
		if name == self || svc == nil {
			continue
		}
		for _, v := range svc.Volumes {
			if s, _, _, ok := splitMount(v); ok && s == src {
				peers = append(peers, name)
				break
			}
		}
	}
	sort.Strings(peers)
	return peers
}

// sharesHostDataDir reports whether another service mounts the same host path.
// Two services on one host directory are sharing it deliberately — a database and
// a backup/inspection sidecar, typically. Giving each its own named volume would
// sever that silently: the sidecar would keep working against an empty volume and
// look healthy forever. Adapting only one is no better (the other would read a
// directory the database no longer writes), so this is a decision for the user.
func (o *Orchestrator) sharesHostDataDir(self, src string) bool {
	for name, svc := range o.Project.Services {
		if name == self || svc == nil {
			continue
		}
		for _, v := range svc.Volumes {
			if s, _, _, ok := splitMount(v); ok && s == src {
				return true
			}
		}
	}
	return false
}

// hasNestedDataDirMount reports whether the service mounts anything at a path
// below Postgres's data directory — an injected `postgresql.conf`, a dedicated
// `pg_wal`. Moving PGDATA down a level would leave those mounts one level above
// the new data directory, so the config would stop being read and the WAL
// directory would go unused, both without a word of complaint.
func hasNestedDataDirMount(svc *compose.Service) bool {
	for _, v := range svc.Volumes {
		_, target, _, ok := splitMount(v)
		if ok && strings.HasPrefix(target, postgresDataDir+"/") {
			return true
		}
	}
	return false
}

// freeVolumeName returns a volume name that no other adaptation has claimed, that
// the project doesn't declare, and that no service already mounts. Reusing a
// declared name would merge into that declaration — including an `external: true`
// one, pointing a freshly-initialized database at data the user manages elsewhere.
// Undeclared-but-mounted names matter just as much: compose doesn't require a
// declaration, so taking one would silently hand another service's volume to a
// database (and trip the exclusive-attach failure, OPSM-102).
func (o *Orchestrator) freeVolumeName(base string, claimed map[string]bool) string {
	used := map[string]bool{}
	for _, svc := range o.Project.Services {
		for _, v := range svc.Volumes {
			if src, _, _, ok := splitMount(v); ok && isNamedVolume(src) {
				used[src] = true
			}
		}
	}
	taken := func(n string) bool {
		if claimed[n] || used[n] {
			return true
		}
		_, declared := o.Project.Volumes[n]
		return declared
	}
	name := base
	for i := 2; taken(name); i++ {
		name = fmt.Sprintf("%s-%d", base, i)
	}
	claimed[name] = true
	return name
}

// suggestSharedVolumeFix proposes — without applying — a way out of the one
// incompatibility that is purely about sharing: Apple `container` attaches a named
// volume to a single container at a time, so two services that mount the same one
// cannot both run (OPSM-102). A host directory IS shareable, so swapping the
// volume for a bind mount fixes it.
//
// This is a suggestion rather than a fix because it changes what the project
// means: the data leaves the runtime's storage for a directory on the Mac, and
// that directory's contents and permissions become the user's problem. Nobody
// should discover that from a tool doing it silently.
func (o *Orchestrator) suggestSharedVolumeFix(order []string) []serviceAdaptation {
	users := map[string][]string{} // volume -> services mounting it
	target := map[string]string{}  // volume -> where the first user mounts it
	for _, name := range order {
		svc := o.Project.Services[name]
		if svc == nil {
			continue
		}
		for _, v := range svc.Volumes {
			src, tgt, _, ok := splitMount(v)
			if !ok || !isNamedVolume(src) || o.isExternalVolume(src) {
				continue
			}
			users[src] = append(users[src], name)
			if _, seen := target[src]; !seen {
				target[src] = tgt
			}
		}
	}
	var vols []string
	for v, u := range users {
		if len(u) > 1 {
			vols = append(vols, v)
		}
	}
	sort.Strings(vols)

	var out []serviceAdaptation
	for _, vol := range vols {
		svcs := users[vol]
		sort.Strings(svcs)
		host := "./" + compose.SanitizeName(vol)
		for _, name := range svcs {
			out = append(out, serviceAdaptation{
				Adaptation: Adaptation{
					Service: name,
					Code:    string(codeSharedVolume),
					Summary: fmt.Sprintf("service %q shares named volume %q with %d other service(s); a bind mount would let them all run", name, vol, len(svcs)-1),
				},
				class: classSuggestion,
				comment: suggestionBlock(
					fmt.Sprintf("%s service %q: mount the shared data from a host directory instead of the named volume %q.",
						suggestionMarker, esc(name), esc(vol)),
					[]string{
						"Apple container attaches a named volume to one container at a time, so",
						fmt.Sprintf("%s cannot all run while they share %q — whichever starts", quotedList(svcs), esc(vol)),
						"first gets it and the rest fail to attach. Diagnostic: " + string(codeSharedVolume) + ".",
						"A host directory is shareable, so a bind mount lets them all mount it.",
						"NOT APPLIED, because it changes what the project means: the data moves out",
						"of the runtime's storage onto the Mac, and that directory's contents and",
						"permissions become yours to manage. A database's data directory in",
						"particular should NOT be moved this way — it needs to be chownable.",
					},
					[]string{
						fmt.Sprintf("uncomment the block for every service sharing %q (all of them,", esc(vol)),
						"or none), create the directory, then `opossum up`. `opossum ps`",
						"should show them all running.",
					},
				),
				block:   "volumes",
				entries: []string{fmt.Sprintf("      - %s:%s", esc(host), esc(target[vol]))},
			})
		}
	}
	return out
}

// suggestionBlock renders a suggestion: what it proposes, why (with the code),
// and how to apply it. The YAML that follows is commented out by the renderer.
func suggestionBlock(what string, why, apply []string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n", what)
	section := func(label string, lines []string) {
		for i, l := range lines {
			if i == 0 {
				fmt.Fprintf(&b, "# %s: %s\n", label, l)
			} else {
				fmt.Fprintf(&b, "#   %s\n", l)
			}
		}
	}
	section("Why", why)
	section("To apply", apply)
	section("To ignore", []string{"delete this block. Nothing here is in effect until you uncomment it."})
	return b.String()
}

// quotedList renders names for prose: `"a", "b" and "c"`.
func quotedList(names []string) string {
	q := make([]string, len(names))
	for i, n := range names {
		q[i] = fmt.Sprintf("%q", esc(n))
	}
	switch len(q) {
	case 0:
		return ""
	case 1:
		return q[0]
	}
	return strings.Join(q[:len(q)-1], ", ") + " and " + q[len(q)-1]
}

// handsThroughAFile reports whether a mount is passing one file into the
// container rather than handing over a directory.
//
// A bind source that does not exist is created as a directory whatever it was
// meant to be — docker compose does the same — so a file the user was told to
// supply becomes an empty directory, indistinguishable from a data directory by
// the time anything downstream looks at it. ensureBindDirs says so (OPSM-107)
// rather than let the failure surface later as something else.
//
// The shape it looks for is the same name on both sides with an extension
// (`./x.js:/somewhere/x.js`), which is how a single file is nearly always passed
// through. It misses a renamed file (`./config.yml:/app/conf.yml`) and one with no
// extension (`./CaddyFile:/etc/caddy/Caddyfile`) — both real shapes in the wild,
// both only worth a warning, never a change.
func handsThroughAFile(src, target string) bool {
	name := path.Base(target)
	return name == path.Base(src) && path.Ext(name) != ""
}

// suggestObservedChownFailures turns each recorded crash into a suggestion for
// the mount that actually died.
//
// Nothing here is inferred from the shape of a path. The service ran, its
// entrypoint tried to take ownership of that directory, and Apple `container`
// refused because a bind mount is host-owned — so the one thing a reader wants to
// know, whether this actually breaks, is already answered. That is the difference
// from the predicate this replaced, which proposed the same swap for any empty
// read-write bind directory and was wrong about half the time.
//
// A record is skipped when the project has moved on: the service or the mount may
// be gone, or the mount may already be a named volume because the suggestion was
// taken. The record is evidence of what happened, not an instruction to keep
// repeating it.
func (o *Orchestrator) suggestObservedChownFailures(plans []serviceAdaptation, claimed map[string]bool) []serviceAdaptation {
	var out []serviceAdaptation
	for _, f := range o.recordedChownFailures() {
		svc := o.Project.Services[f.Service]
		if svc == nil {
			continue
		}
		stillBound := false
		for _, v := range svc.Volumes {
			src, target, mode, ok := splitMount(v)
			if ok && src == f.Source && target == f.Target && !readOnlyMount(mode) && isHostPath(src) {
				stillBound = true
				break
			}
		}
		if !stillBound {
			continue
		}
		// Suppress only when this plan really did emit an applied swap for the same
		// mount. Asking `ownsDataDir` instead was close but not the same question:
		// the applied path also requires the service to run its image's own server
		// and the directory not to be shared, so a mysql with an overridden
		// entrypoint would be silenced here while nothing was applied — the crash
		// would leave no trace in the overlay at all.
		if appliedSameMount(plans, f.Service, f.Target) {
			continue
		}
		// Another service reading the same host directory is what makes this change
		// cost more than it looks: detaching it silently ends the sharing. The applied
		// path refuses outright for that reason; here the crash is real, so the entry
		// stays and names who else is looking.
		var sharedWith []string
		if peers := o.servicesSharingHostDir(f.Service, f.Source); len(peers) > 0 {
			sharedWith = []string{
				"CAREFUL: " + quotedList(peers) + " also mount " + esc(f.Source) + ".",
				"Switching this service to a volume ends that sharing — they keep reading",
				"the directory on the Mac while this one stops writing to it.",
			}
		}
		vol := o.freeVolumeName(compose.SanitizeName(f.Service)+"-"+compose.SanitizeName(pathLeaf(f.Target)), claimed)
		out = append(out, serviceAdaptation{
			Adaptation: Adaptation{
				Service: f.Service,
				Code:    string(codeBindDataDirChown),
				Summary: fmt.Sprintf("service %q died taking ownership of %s; a named volume can be chowned, a bind mount cannot", f.Service, f.Target),
			},
			class: classSuggestion,
			comment: suggestionBlock(
				fmt.Sprintf("%s service %q: use a named volume for %s instead of the host path %q.",
					suggestionMarker, esc(f.Service), esc(f.Target), esc(f.Source)),
				append([]string{
					"This is not a guess. That container started, tried to take ownership of",
					esc(f.Target) + ", and exited: Apple container bind mounts are",
					"host-owned and cannot be chowned from inside. A named volume can.",
					"Diagnostic: " + string(codeBindDataDirChown) + ".",
					"NOT APPLIED, because it moves where the data lives. Today it is on the",
					"Mac at " + esc(f.Source) + " and you can open it; afterwards it",
					"is inside a volume that only the runtime manages. Anything already in",
					"that directory stays where it is and the service stops seeing it.",
				}, sharedWith...),
				[]string{
					"uncomment this block, then `opossum up` again. To keep the data on the",
					"Mac instead, run the service as the user that owns the directory",
					"(`user:` in the compose file) so it has nothing to chown.",
				},
			),
			block:   "volumes",
			entries: []string{fmt.Sprintf("      - %s:%s", esc(vol), esc(f.Target))},
			volume:  vol,
		})
	}
	return out
}

// appliedSameMount reports whether the plan already changes this service's mount
// at target, so the overlay does not carry two blocks for one mount.
func appliedSameMount(plans []serviceAdaptation, service, target string) bool {
	for _, p := range plans {
		if p.class != classApplied || p.Service != service {
			continue
		}
		for _, e := range p.entries {
			if strings.HasSuffix(strings.TrimSpace(e), ":"+target) {
				return true
			}
		}
	}
	return false
}
