package orchestrator

import (
	"fmt"
	"path"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/suruseas/opossum/internal/compose"
)

// Adapting a compose project
//
// Some compose files that run fine on Docker cannot start as written on Apple
// `container`, for reasons that are properties of the runtime rather than
// mistakes in the file (see the two patterns below). opossum already warns about
// these; `up --from-docker-compose` goes one step further and writes the fix into
// a `compose.opossum.yaml` overlay, so bringing an existing project over is one
// command instead of a read-warn-edit loop.
//
// Two rules keep this honest:
//   - The overlay is a separate file. The user's own compose files are never
//     modified, docker compose never reads the overlay, and deleting it undoes
//     everything.
//   - Only changes that preserve intent are automated (see adaptations below).
//     Anything that would alter what the project *means* — sharing semantics,
//     published ports, app-specific seeding — stays a warning.
//
// The generated YAML is written from templates rather than marshalled, because
// the comments are the point: the reader is often an agent that must decide what
// to do when the fix doesn't work, so every entry carries what changed, why (with
// the diagnostic code, to cross-reference AGENTS.md), how to verify it, what to do
// if it still fails, and how to undo it.

// Entry classes. The overlay is not only the fixes opossum made — it is the whole
// compatibility picture for this project, so a reader (often an agent) finds the
// problems opossum could NOT fix in the same place, instead of having to know they
// exist. Each class says how much opossum is claiming:
//
//	applied     — changed, and in effect. This is what made the project run.
//	suggestion  — a concrete change opossum will NOT make for you, written out but
//	              commented. It alters what the project means (where data lives,
//	              how services share it), so the call is yours; uncomment to apply.
//	note        — something opossum writes no YAML for, which is why there is
//	              nothing to uncomment. Whether you can do anything about it is
//	              the note's own business; this records the fact so the failure
//	              isn't a mystery.
//
// The markers are stable strings on purpose: an agent greps them to tell
// opossum-generated entries from hand-written ones, and to tell what is live from
// what is merely proposed. Never change them without a migration.
const (
	overlayMarker = "[opossum --from-docker-compose]"
	// overlayGeneratedHeader is the first line of every overlay opossum writes. It
	// is how `destroy` tells a file it generated from one the user wrote by hand:
	// the overlay is a documented place for people to put their own adjustments, so
	// removing one without this line would be deleting someone's work.
	overlayGeneratedHeader = "# Generated by `opossum up --from-docker-compose`."
	suggestionMarker       = "[opossum suggestion — NOT APPLIED]"
	noteMarker             = "[opossum note]"
	// NoteFrame says what a note is, in the one place every frame reads it from.
	//
	// It is a fragment, not a sentence: each caller supplies the noun in front of
	// it ("things", "something", "2 thing(s)"), because one of them carries a
	// count and the rest do not.
	//
	// It used to be written out wherever it was needed — in `cmd/opossum`, in the
	// Notes heading and the legend here, in the class list above, and again in
	// `AGENTS.md` and `docs/compatibility.md`. Every copy said the same thing:
	// that no compose change could fix these. That was true of some notes and
	// false of others, and when the Docker socket note stopped saying it, the
	// copies went on saying it anyway — including one four lines from here.
	//
	// What is true of every note is narrower, and it is about the file rather
	// than about the reader: a note is a comment, and opossum writes no YAML
	// under it — which is why there is nothing to uncomment. Whether the reader
	// can do anything about it is the note's own business, and each one says so
	// where there is something to say.
	NoteFrame = "opossum writes no YAML for"
)

// entryClass is which of the three an overlay entry is.
type entryClass int

const (
	classApplied entryClass = iota
	classSuggestion
	classNote
)

// OverlayFileName is the overlay `up --from-docker-compose` generates.
const OverlayFileName = "compose.opossum.yaml"

// mysqlDataDir is MySQL/MariaDB's default data directory. Like Postgres's, a
// bind mount here fails because the image chowns it at startup.
const mysqlDataDir = "/var/lib/mysql"

// Other databases' data directories, each verified on the real runtime to fail
// the same way (the container starts, chowns its data directory, and exits):
//
//	clickhouse  chown: /var/lib/clickhouse/: Operation not permitted
//	mongo       chown: changing ownership of '/data/db': Operation not permitted
//
// The trap is that `up` reports success and exits 0: the container is created and
// started, and only then does the entrypoint fail its chown and exit. `opossum ps`
// immediately afterwards already shows it stopped.
const (
	clickhouseDataDir = "/var/lib/clickhouse"
	mongoDataDir      = "/data/db"
	// mongo's entrypoint chowns BOTH /data/db and /data/configdb, so fixing only
	// the first leaves the container dying on the second — with the change already
	// announced as the fix and the user's directory already detached.
	mongoConfigDir = "/data/configdb"
)

// dbDataDir pairs a database's data directory with the images that own it. Both
// halves are required to adapt a mount: the path alone is not evidence, because
// plenty of services legitimately mount a database's directory without being that
// database (a backup sidecar, an inspector, a migration tool). Rewriting one of
// those would swap its real data for an empty volume — silently, and in the user's
// favourite direction to not notice. So an adaptation only fires when the service
// is plausibly the database that chowns the path at startup.
type dbDataDir struct {
	path string
	// images are the image names of databases that own path, matched against the
	// LAST path segment of the image reference (registry, namespace, tag and digest
	// stripped). Matching the whole reference by substring would be far too loose:
	// `postgres-exporter`, `mysqldump-cron` and `mysql-backup-tool` all contain a
	// database's name while being exactly the sidecars this must not touch. An
	// unrecognized fork is only a missed fix; a wrong match swaps a service's real
	// data for an empty volume, so the list errs toward missing.
	images []string
}

var dbDataDirs = []dbDataDir{
	{postgresDataDir, []string{"postgres", "postgresql", "postgis", "timescaledb", "timescaledb-ha"}},
	{mysqlDataDir, []string{"mysql", "mysql-server", "mariadb", "percona", "percona-server", "percona-xtradb-cluster"}},
	{clickhouseDataDir, []string{"clickhouse", "clickhouse-server"}},
	{mongoDataDir, []string{"mongo", "mongodb", "mongodb-community-server"}},
	{mongoConfigDir, []string{"mongo", "mongodb", "mongodb-community-server"}},
}

// imageName reduces an image reference to its bare name: the last path segment,
// with any registry, namespace, tag and digest removed. `docker.io/library/
// postgres:16` and `bitnami/postgresql` become `postgres` and `postgresql`.
func imageName(ref string) string {
	s := strings.ToLower(strings.TrimSpace(ref))
	if i := strings.Index(s, "@"); i >= 0 {
		s = s[:i] // digest
	}
	if i := strings.LastIndex(s, ":"); i > strings.LastIndex(s, "/") {
		s = s[:i] // tag (a colon before the last slash is a registry port)
	}
	if i := strings.LastIndex(s, "/"); i >= 0 {
		s = s[i+1:]
	}
	return s
}

// serverCommands are the entrypoint arguments that make a database image behave
// as the server. The official images only chown their data directory on that
// path: mongo chowns when argv[0] is `mongod`, postgres when it's `postgres`.
// A sidecar built on the same image to dump, restore or poke at the data
// (`redis-cli`, `mongodump`, a shell) reads a bind mount perfectly well — and
// rewriting it would swap that service's real data for an empty volume.
var serverCommands = map[string]bool{
	"mongod": true, "clickhouse-server": true, "clickhouse": true,
	"postgres": true, "docker-entrypoint.sh": true,
	"mysqld": true, "mysqld_safe": true, "mariadbd": true,
}

// runsAsServer reports whether the service still runs its image's own server.
// An overridden entrypoint means we can't tell what it runs, so assume not; an
// overridden command is judged by its first word.
func runsAsServer(svc *compose.Service) bool {
	if len(svc.Entrypoint) > 0 {
		return false
	}
	if len(svc.Command) == 0 {
		return true // the image's default: the server
	}
	return serverCommands[pathLeaf(svc.Command[0])]
}

// pgdataSource says how the answer about a Postgres image's data directory was
// come by. "Asked and told nothing" is not the same as "could not ask", and the
// overlay says which, so a reader is never told the image was unreachable when it
// simply declares nothing.
type pgdataSource int

const (
	// Unreachable is the zero value on purpose: a path that never asked must not
	// come back looking like a reading.
	pgdataUnreachable pgdataSource = iota // the image is not here to be asked
	pgdataRead                            // it was declared, by the image or the service
	pgdataNotDeclared                     // the image answered and declares none
)

// dataDirDecision is where a service's cluster actually goes, and who said so.
//
// It is one value, made in one place, because three rounds of review found the
// same defect three times: the answer was right where it was computed and wrong
// where it was described, since every site worked it out again. Anything that
// needs to say where the data directory is — the swap, the comment on it, the note
// when there is no fix — takes this and does not ask again.
type dataDirDecision struct {
	path   string
	source pgdataSource
	// byService is true when the compose file sets PGDATA: a container's
	// environment overrides the image's, so then the image's declaration is not
	// what will happen.
	byService bool
	// valueUnknown is true when the service sets PGDATA without a value opossum can
	// read — `environment: [PGDATA]` passes the host's through. What the image
	// declares is the best guess left, and saying so is the point.
	valueUnknown bool
}

// explain is how the overlay tells a reader where this came from. Every wording
// about the data directory goes through here, so a reader is never told the image
// decided something the service did.
func (d dataDirDecision) explain() []string {
	switch {
	case d.byService && d.valueUnknown:
		// Where the fallback came from still has to be said: "the image declares" is
		// a claim, and this branch reaches it having asked, having been told nothing,
		// or not having asked at all.
		lead := "This service passes PGDATA in from the environment, so where its cluster"
		switch d.source {
		case pgdataRead:
			return []string{lead, fmt.Sprintf("goes cannot be read here; %s is what the image declares.", esc(d.path))}
		case pgdataNotDeclared:
			return []string{lead, fmt.Sprintf("goes cannot be read here, and the image declares none; %s is", esc(d.path)),
				"the path the Postgres images use by default."}
		default:
			return []string{lead, "goes cannot be read here, and the image was not here to be asked;",
				fmt.Sprintf("%s is the path the Postgres images used through 17.", esc(d.path))}
		}
	case d.byService:
		return []string{fmt.Sprintf("The data directory is the one this service sets: PGDATA=%s.", esc(d.path))}
	case d.source == pgdataRead:
		return []string{fmt.Sprintf("The data directory is the one this image declares: PGDATA=%s.", esc(d.path))}
	case d.source == pgdataNotDeclared:
		return []string{
			fmt.Sprintf("This image declares no PGDATA, so %s is the path the Postgres", esc(d.path)),
			"images use by default.",
		}
	default:
		return []string{
			fmt.Sprintf("The image was not here to be asked, so %s is the path the", esc(d.path)),
			"Postgres images used through 17. Postgres 18 moved it; if the container",
			fmt.Sprintf("exits at startup, %s says where it goes now.", codePGVersionedLayout),
		}
	}
}

// OneLine keeps a value from an image or a compose file inside the line it is
// written on: a stray newline in either would carry YAML out of a comment block
// and cost the whole overlay, and on screen it would put the rest of the value
// at column zero, where opossum's own sentences start.
//
// Exported for the command that prints what this package produces, which needs
// the same rule and must not carry a second copy of it.
//
// Every control character becomes a space — the value keeps its length and stays
// readable, and it can no longer end the line it was written on. That matters
// wherever opossum's own words and a project's words share a screen: a line
// break puts the rest of the value at column zero, where opossum's sentences
// start, and a project can write a sentence in opossum's voice.
//
// Not to be confused with the oneLine in internal/mutate, which collapses runs
// of whitespace for a markdown cell. Same name, different promise: this one
// changes no character that was already printable.
func OneLine(s string) string {
	return strings.Map(func(r rune) rune {
		if r < ' ' || r == 0x7f {
			return ' '
		}
		return r
	}, s)
}

// Quoted keeps a failure on the lines opossum gave it: every line goes through
// OneLine, and a continuation line that does not already start indented is
// pushed in by two spaces, so only the first line begins at the margin — the
// position that separates opossum's sentences from quoted ones.
//
// Deliberately multi-line messages keep their shape: their continuations (a
// hint's command block, an error's second line of advice) are already
// indented. What moves is a line break a VALUE carried — a path, a service
// name, the runtime's own output — which used to start the rest of the value
// at column zero, where a project could put a sentence and have it read as
// opossum reporting something. Indented, it reads as what it is: a quoted
// value.
//
// Two callers, one rule: the CLI's single error printer, and logf (the warning printer) for
// error-typed arguments (#688 — a watch warning printed an `up` failure
// through %v, and the same forged line that the CLI printer indents walked
// straight to column zero).
func Quoted(msg string) string {
	var b strings.Builder
	for i, line := range strings.Split(msg, "\n") {
		if i > 0 {
			b.WriteString("\n")
			if !strings.HasPrefix(line, "  ") {
				b.WriteString("  ")
			}
		}
		b.WriteString(OneLine(line))
	}
	return b.String()
}

// whyNoPGDATA names the one thing that stopped opossum writing the other half,
// rather than listing both and leaving the reader to work out which applies.
func (d dataDirDecision) whyNoPGDATA() string {
	switch {
	case d.valueUnknown:
		return "this service passes PGDATA in from the environment"
	case d.byService:
		return "this service sets its own PGDATA"
	}
	return "this service mounts something below the data directory"
}

// who is the clause for a one-line summary that has to attribute the path. The
// reasoning behind it belongs to explain, which every comment goes through, so the
// two can never disagree.
func (d dataDirDecision) who() string {
	if d.byService {
		return "this service points PGDATA at"
	}
	return "this image keeps its cluster in"
}

// postgresDataDirFor asks the image where it keeps its data, since it says so:
// the Postgres images declare PGDATA, and 18 moved it from
// /var/lib/postgresql/data to a version subdirectory below /var/lib/postgresql.
// A constant here could only find that out by being wrong, which is what happened.
//
// asked is false when the image cannot be reached — `up --from-docker-compose`
// writes the overlay before anything is pulled, so this is the ordinary case, not
// an edge — and the caller says so in the comment it writes rather than passing an
// assumption off as a reading.
func (o *Orchestrator) postgresDataDirFor(svc *compose.Service) dataDirDecision {
	// The service's own PGDATA wins: a container's environment overrides the
	// image's, so when the compose file sets it, where the image would have
	// initialised is no longer where it will.
	// The value ends up in a comment block, so it is kept on its line — the service's
	// as much as the image's, and this one wins over the image's.
	if p := strings.TrimRight(OneLine(servicePGDATA(svc)), "/"); p != "" {
		// The image still answers for what its entrypoint does; only the path is the
		// service's. Asking costs one inspect, remembered per image.
		return dataDirDecision{path: p, source: pgdataRead, byService: true}
	}
	d := o.imageDataDir(svc)
	// A PGDATA with no value opossum can read still overrides the image at runtime.
	// The image's path is the best guess left, and the wording says as much.
	if hasPGDATA(svc) {
		d.byService, d.valueUnknown = true, true
	}
	return d
}

// imageDataDir is what the image says, with nothing from the compose file.
func (o *Orchestrator) imageDataDir(svc *compose.Service) dataDirDecision {
	if o.rt == nil || svc.Image == "" {
		// Nobody to ask: a caller planning without a runtime (the plan is printed,
		// not run). An empty Image is rare — the loader fills in a derived tag for a
		// service that builds — but it costs nothing to answer the same way.
		return dataDirDecision{path: postgresDataDir, source: pgdataUnreachable}
	}
	env, ok := o.imageEnv(svc.Image)
	if !ok {
		return dataDirDecision{path: postgresDataDir, source: pgdataUnreachable}
	}
	if p := strings.TrimRight(OneLine(env["PGDATA"]), "/"); p != "" {
		// The value comes from the image and ends up in a comment block, so it is
		// kept on its line: a stray newline would carry YAML into the overlay and
		// cost the whole file.
		return dataDirDecision{path: p, source: pgdataRead}
	}
	return dataDirDecision{path: postgresDataDir, source: pgdataNotDeclared}
}

// servicePGDATA returns the PGDATA the compose file sets on this service, or "".
func servicePGDATA(svc *compose.Service) string {
	for _, e := range svc.Environment {
		if name, value, ok := strings.Cut(e, "="); ok && name == "PGDATA" {
			return value
		}
	}
	return ""
}

// imageEnv is ImageEnv with the answer remembered: planning an overlay asks about
// the same image for every mount it considers, and each ask is a process.
func (o *Orchestrator) imageEnv(ref string) (map[string]string, bool) {
	if o.imageEnvs == nil {
		o.imageEnvs = map[string]map[string]string{}
	}
	if env, seen := o.imageEnvs[ref]; seen {
		return env, env != nil
	}
	env, ok := o.rt.ImageEnv(ref)
	if !ok {
		env = nil
	}
	o.imageEnvs[ref] = env
	return env, ok
}

// startingDir is the directory a service's process starts in, or "" when nothing
// says. The compose file wins when it names one — that is what the runtime is
// given — and otherwise the image is asked, the same way it is asked where a
// database keeps its data.
//
// Called only when the answer is needed — asking costs a process, and a log that
// names its own path never asks. The answer is remembered per image.
//
// This is a declaration, not a prediction — but the line is finer than it looks.
// What the image declares is where the process *starts*; what the log's `.` means
// is the argument chown was given, which is the process's directory only if chown
// was run there. They line up unless something moved in between — an overridden
// `entrypoint:` or `command:`, a `cd` inside the image's own entrypoint script, a
// subshell — and none of that is checked here. So this is used only to read a
// path the container itself named, and only where the answer lands inside a mount
// the service actually has. It does widen what gets *proposed*: a crash that used
// to end in a shrug now leaves a record, and the next run offers that mount. What
// it never widens is what gets applied — that list is elsewhere and does not read
// this.
func (o *Orchestrator) startingDir(svc *compose.Service) string {
	if d := strings.TrimSpace(svc.WorkingDir); d != "" {
		return d
	}
	if o.rt == nil || svc.Image == "" {
		return ""
	}
	if o.imageWorkdirs == nil {
		o.imageWorkdirs = map[string]string{}
	}
	if d, seen := o.imageWorkdirs[svc.Image]; seen {
		return d
	}
	// An image that could not be asked answers "" — the same as one that declares
	// nothing, which is right here: both leave `.` unresolved, and the caller falls
	// back to the mount being forced or not at all.
	d, _ := o.rt.ImageWorkingDir(svc.Image)
	o.imageWorkdirs[svc.Image] = d
	return d
}

// swapHelpsHere reports whether moving this mount to a named volume is a fix,
// and how the answer was come by.
//
// The swap exists because the image chowns the directory it is handed, and a bind
// mount cannot be chowned from inside. Whether that is this directory depends on
// where the cluster actually goes: the Postgres images declare PGDATA, and a
// service that sets its own overrides them. Three shapes, each measured on the real
// runtime and kept in testdata/error-wordings/:
//
//   - declared AT this mount (17 and earlier) — the image chowns the mount itself
//     and a bind mount fails: pg17-bind-old-datadir.txt. Swap.
//   - declared BELOW this mount — the image makes that subdirectory inside the
//     mount and chowns what it made, so a bind mount works and moving it would
//     take the data somewhere the user did not ask for:
//     pg-image-declares-pgdata-below-the-mount.txt. Leave it.
//   - declared SOMEWHERE ELSE (18 keeps its cluster under /var/lib/postgresql)
//     — the image will not look at this mount at all unless PGDATA is set to point
//     back into it. What it does about that depends on its entrypoint — 18 refuses
//     to start rather than ignore the mount (pg18-named-old-datadir.txt, which also
//     carries the OPSM-110 line), 17 runs and leaves it empty
//     (pg17-service-pgdata-elsewhere.txt) — and both shapes, with the runs they
//     come from, are written down in OPSM-111's entry in AGENTS.md rather than in
//     the note. The pair
//     (named volume plus that PGDATA) does start:
//     pg18-named-old-datadir-with-pgdata.txt. So the swap goes in only alongside the PGDATA
//     half, and when that half cannot be written, neither goes in.
//
// needsPGDATA is true for the third shape: the caller has to know the swap is only
// half of the fix.
func (o *Orchestrator) swapHelpsHere(svc *compose.Service, target string) (helps, needsPGDATA bool, d dataDirDecision) {
	if !ownsDataDir(svc, target) {
		return false, false, dataDirDecision{path: target}
	}
	if !isPostgresImage(svc) {
		return true, false, dataDirDecision{path: target}
	}
	d = o.postgresDataDirFor(svc)
	switch {
	case d.source != pgdataRead:
		// Nothing was read, so this is the answer opossum has always written, and
		// the comment says it was assumed.
		return true, false, d
	case d.path == target:
		return true, false, d
	case strings.HasPrefix(d.path, target+"/"):
		return false, false, d
	default:
		return true, true, d
	}
}

// isPostgresImage reports whether the service runs one of the Postgres images the
// data-directory table knows, which are the ones that declare PGDATA.
func isPostgresImage(svc *compose.Service) bool {
	name := imageName(svc.Image)
	for _, d := range dbDataDirs {
		if d.path != postgresDataDir {
			continue
		}
		for _, img := range d.images {
			if name == img {
				return true
			}
		}
	}
	return false
}

// howWeKnowTheDataDir says whether the data directory in this change was read
// from the image or assumed, so the reader is never left guessing which. The
// Postgres images declare it and moved it in 18; when the image is not here to be
// asked, what is written is the path they used through 17.
func howWeKnowTheDataDir(svc *compose.Service, d dataDirDecision) []string {
	if !isPostgresImage(svc) {
		return nil
	}
	return d.explain()
}

// ownsDataDir reports whether svc looks like the database that owns target — i.e.
// whether adapting that mount is safe. A service with a `build:` and no `image:`
// can't be identified, so it is left alone.
func ownsDataDir(svc *compose.Service, target string) bool {
	name := imageName(svc.Image)
	if name == "" {
		return false
	}
	for _, d := range dbDataDirs {
		if d.path != target {
			continue
		}
		for _, img := range d.images {
			if name == img {
				return true
			}
		}
	}
	return false
}

// Adaptation is one change the overlay makes, for reporting to the user.
type Adaptation struct {
	Service string
	Code    string // the diagnostic code this relates to, e.g. "OPSM-101"
	Summary string // one line, in the user's terms
	// Kind is "applied", "suggestion" or "note" — what opossum is claiming. The
	// caller reports each group separately, because calling a note a "change"
	// would overstate what the overlay did.
	Kind string
}

// serviceAdaptation is the internal, renderable form: the YAML fragment for one
// service plus the comment block that explains it.
type serviceAdaptation struct {
	Adaptation
	class   entryClass
	comment string // the full comment block (already prefixed with "# ")
	// block is the service-level YAML key this adaptation writes under (e.g.
	// "volumes"), and entries are its indented items. Kept apart rather than as
	// ready-made lines so a service with two adaptations under the same key emits
	// that key once — YAML rejects a mapping with the same key twice, and the
	// overlay would not load at all.
	block   string
	entries []string
	volume  string // a top-level named volume to declare, if any
}

// PlanOverlay inspects the resolved project (base + any override already merged)
// and returns the text of a compose.opossum.yaml that adapts it to run on Apple
// `container`, plus a description of each change. It returns ("", nil) when
// nothing needs adapting.
//
// Detection runs on the *resolved* project on purpose: an override may already
// have applied the fix by hand, and adapting on top of that would be noise (or
// wrong).
func (o *Orchestrator) PlanOverlay() (string, []Adaptation) {
	body, changes, _ := o.PlanOverlayFor(nil)
	return body, changes
}

// PlanOverlayFor is PlanOverlay for a run that named services on the command
// line. Naming a profile-gated service enables it, as under docker compose, so
// the plan looks at it too.
//
// A service gated behind a profile that is not active is left out. It is not
// started, not shown by `config` (docker compose omits it there as well) —
// and so not diagnosed: an entry
// about it would ask the reader to judge whether a change to a service that
// is not running concerns them, and a note would say "this cannot be fixed"
// about something that is not going to run. What was left out is returned by
// name, so the caller can say so; a later run with the profile enabled finds
// the overlay already there and reports what those services would need
// (#492).
func (o *Orchestrator) PlanOverlayFor(named []string) (body string, changes []Adaptation, gated []string) {
	on := map[string]bool{}
	for _, n := range named {
		on[n] = true
	}
	names := make([]string, 0, len(o.Project.Services))
	for name := range o.Project.Services {
		if !o.enabled(name, on) {
			gated = append(gated, name)
			continue
		}
		names = append(names, name)
	}
	sort.Strings(names) // deterministic output
	sort.Strings(gated)

	claimed := map[string]bool{} // volume names this plan has already taken
	var plans []serviceAdaptation
	for _, name := range names {
		plans = append(plans, o.adaptService(name, o.Project.Services[name], claimed)...)
	}
	plans = append(plans, o.suggestSharedVolumeFix(names)...)
	plans = append(plans, o.suggestObservedChownFailures(plans, claimed)...)
	if len(plans) == 0 {
		return "", nil, gated
	}
	return renderOverlay(plans), summarize(plans), gated
}

func summarize(plans []serviceAdaptation) []Adaptation {
	out := make([]Adaptation, 0, len(plans))
	for _, p := range plans {
		a := p.Adaptation
		switch p.class {
		case classSuggestion:
			a.Kind = "suggestion"
		case classNote:
			a.Kind = "note"
		default:
			a.Kind = "applied"
		}
		out = append(out, a)
	}
	return out
}

// adaptService returns the adaptations for one service. A Postgres service whose
// data directory is a bind mount needs both fixes: the mount has to become a named
// volume (bind mounts can't be chowned), and PGDATA then has to point at a
// subdirectory of it (a named volume mount point isn't empty). Handling only one
// would move the failure rather than remove it.
func (o *Orchestrator) adaptService(name string, svc *compose.Service, claimed map[string]bool) []serviceAdaptation {
	if svc == nil {
		return nil
	}
	// The notes are computed before anything is decided, because they are the
	// part of this that does not depend on the environment: noteNoYAML reads
	// Restart and Volumes and nothing else. They are appended last, where they
	// have always gone.
	notes := o.noteNoYAML(name, svc)
	// Decide nothing from an environment that could not be read. The two
	// questions below are both answered out of it — whether PGDATA is already
	// set is the load-bearing one — and an unreadable env_file reads there as
	// a variable nobody set, which is the one mistake the PGDATA guard exists
	// to avoid: writing an overlay that sets PGDATA over the value the user
	// was supplying at run time. The overlay outlives the failed run, so a
	// wrong answer is not undone by the command that produced it stopping.
	//
	// The notes still go out. Withholding them would make an unreadable
	// env_file the reason a service's `restart:` policy or device mount went
	// unmentioned, and those notes exist so that a thing opossum writes no
	// YAML for is not a mystery — an unrelated failure elsewhere is no reason
	// to restore the mystery. The same goes for the two suggesters PlanOverlay
	// runs outside this function: they read volumes and recorded failures,
	// never the environment.
	if _, err := svc.ResolvedEnv(); err != nil {
		return notes
	}
	var out []serviceAdaptation
	// Ask first whether the PGDATA half is available: for an image that initialises
	// somewhere other than the mount, the swap is only a fix alongside it.
	_, pgdataFixApplies := o.adaptPGDATA(name, svc, true)
	swaps, swappedPostgres := o.adaptBindMountedDataDir(name, svc, claimed, pgdataFixApplies)
	out = append(out, swaps...)
	if p, ok := o.adaptPGDATA(name, svc, swappedPostgres); ok {
		out = append(out, p)
	}
	out = append(out, notes...)
	return out
}

// notePGDATAHalfMissing writes down the case opossum finds and will not fix: a
// Postgres image that keeps its cluster somewhere other than the directory this
// mount lands on, where the swap to a named volume only works
// alongside a PGDATA pointing back into it — and that half cannot be written here.
// Three things stop it, and all are reachable from here: the service sets its own
// PGDATA, passes one in from the environment, or mounts something below the data
// directory. The external-volume
// case in adaptPGDATA is not: this path only ever sees bind mounts.
//
// Writing nothing would leave a reader to meet the trouble with no sign opossum
// knew. What that trouble is depends on the image, and the shapes it comes in —
// with the run each was measured in — are in OPSM-111's entry in AGENTS.md rather
// than here, so this note reads the same whatever the image turns out to be.
func (o *Orchestrator) notePGDATAHalfMissing(name string, svc *compose.Service, target string, d dataDirDecision) serviceAdaptation {
	var what, fact string
	if !d.valueUnknown {
		what = fmt.Sprintf("service %q: %s is a bind mount, and %s %s instead — left as it is",
			name, target, d.who(), d.path)
		fact = fmt.Sprintf("The cluster this service will write does not land in %s.", esc(target))
	} else {
		// The line most readers see is this one — a note-only overlay is not written
		// at all (#491) — so it hedges where the body does.
		what = fmt.Sprintf("service %q: %s is a bind mount, and PGDATA comes in from the environment — left as it is",
			name, target)
		fact = "Whether it lands in this mount therefore cannot be read here either."
	}
	return serviceAdaptation{
		Adaptation: Adaptation{Service: name, Code: string(codeDataDirNotThisMount), Summary: OneLine(what), Kind: "note"},
		class:      classNote,
		comment: noteBlock(
			fmt.Sprintf("%s service %q: %s left as a bind mount.", noteMarker, esc(name), esc(target)),
			append(append(d.explain(), fact), d.secondHalf()...),
			[]string{
				fmt.Sprintf("%s in AGENTS.md has the shapes this comes in, what each costs,", codeDataDirNotThisMount),
				"and what to change.",
			},
		),
	}
}

// secondHalf says why the mount was left rather than swapped. It is the same
// sentence in every shape on purpose: fourteen rounds of review found a defect in
// this note ten times, and every one of them was in a sentence that varied by
// branch. What varies belongs in the code's entry in AGENTS.md, where each line
// can name the run it comes from.
func (d dataDirDecision) secondHalf() []string {
	return []string{
		"opossum left it alone: moving it to a named volume only helps together with",
		fmt.Sprintf("a PGDATA pointing back into it, and that could not be written here (%s).", d.whyNoPGDATA()),
	}
}

// noteNoYAML records the problems opossum finds but writes no YAML for. Writing
// them down is the point — otherwise the user meets the failure with no idea
// opossum already knew about it.
func (o *Orchestrator) noteNoYAML(name string, svc *compose.Service) []serviceAdaptation {
	var out []serviceAdaptation
	note := func(code diagCode, what string, why, next []string) {
		out = append(out, serviceAdaptation{
			Adaptation: Adaptation{Service: name, Code: string(code), Summary: OneLine(what)},
			class:      classNote,
			comment:    noteBlock(fmt.Sprintf("%s service %q: %s", noteMarker, esc(name), esc(what)), why, next),
		})
	}
	// `on-failure` asks for something the runtime can't answer. The overlay is
	// where a migrating user meets the compatibility surprises, so the one policy
	// opossum only approximates belongs here too — not just in `config` and the
	// docs, which the person moving a project over may never open.
	if pol, err := svc.RestartPolicy(); err == nil && pol.Mode == compose.RestartOnFailure {
		note(codeSupervisorAction, "uses `restart: on-failure`, which opossum can only approximate",
			[]string{
				"`on-failure` means restart only if the service failed. Apple container",
				"does not report a container's exit code, so a crash and a clean exit look",
				"the same from outside. opossum treats any exit as a failure, retries a few",
				"times and then stops — rather than restarting a service that may have",
				"finished on purpose. `always` and `unless-stopped` are honoured exactly.",
			},
			[]string{
				"if this service is meant to keep running, `restart: always` says so",
				"exactly. If it is meant to finish, another service can wait for it with",
				"`depends_on: {condition: service_completed_successfully}`, which also",
				"excludes it from supervision.",
			})
	}
	for _, v := range svc.Volumes {
		src, target, _, ok := splitMount(v)
		if !ok {
			continue
		}
		switch {
		case isDockerSocketMount(src, target):
			note(codeDockerSocket, "mounts the Docker socket, which does not answer for the containers here",
				[]string{
					"Apple container runs these, and it has no socket to share. If a Docker",
					"daemon answers on that path it is a different one, and it knows a",
					"different set: a service that wants this socket in order to watch its",
					"neighbours will be told about theirs.",
				},
				[]string{
					"if you meant that daemon, keep the mount — though a bind whose source",
					"is a symlink to a socket is refused before anything starts, and the",
					"refusal says what to write instead.",
					"If you meant these containers, nothing here answers for them.",
				})
		case isHostDevicePath(src):
			note(codeHostDeviceMount, fmt.Sprintf("mounts the host path %s, which is a device or session socket", src),
				[]string{
					"Each container is its own VM. A device node cannot be handed to one:",
					"/dev/dri and the like arrive as a path with nothing behind them. A",
					"session socket (X11, PulseAudio) is mounted as a path too, and what",
					"would answer on it is the host's own session; whether anything useful",
					"comes through here has not been measured.",
				},
				[]string{
					"expect this service's device-dependent features not to work; no compose",
					"change grants a VM access to the host's devices.",
				})
		}
	}
	return out
}

// isHostDevicePath reports whether a host path is a device node or a session
// socket directory — things a per-container VM has no route to.
func isHostDevicePath(src string) bool {
	for _, p := range []string{"/dev/", "/tmp/.X11-unix", "/run/user/", "/run/pulse", "/var/run/dbus"} {
		if src == strings.TrimSuffix(p, "/") || strings.HasPrefix(src, p) {
			return true
		}
	}
	return false
}

// noteBlock renders a note: what it is, why, and what to expect instead.
// Notes carry no YAML, so they end at "What to expect".
// Every line goes through OneLine. The heading is where a raw path or service
// name arrives from the compose file, and a newline in one of them would end the
// comment and start a line of its own: in the file that line is loose YAML; on
// screen, where the notes are read out without their comment marks, it is a note
// that says whatever its author wanted it to say. The rest arrives normalised
// already, and goes through anyway so that a new caller cannot open this by not
// knowing.
func noteBlock(what string, why, expect []string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n", OneLine(what))
	commentSection(&b, "Why", why)
	commentSection(&b, "What to expect", expect)
	return b.String()
}

// commentSection writes one labelled section of a comment block, every line
// through OneLine. The block ends up on screen or inside the overlay's comment,
// and a value's newline in either place hands the rest of the value a line of
// its own — on screen it speaks from column zero in opossum's voice, in the
// overlay it carries YAML out of the comment and the self-check drops the whole
// file. One writer for every block kind: when the rule lived in each builder's
// own closure, two of the three had lost it (#513).
func commentSection(b *strings.Builder, label string, lines []string) {
	for i, l := range lines {
		if i == 0 {
			fmt.Fprintf(b, "# %s: %s\n", label, OneLine(l))
		} else {
			fmt.Fprintf(b, "#   %s\n", OneLine(l))
		}
	}
}

// adaptBindMountedDataDir swaps a bind-mounted database data directory for a named
// volume. This MOVES WHERE THE DATA LIVES (out of the host directory, into a
// volume the runtime manages), so the generated comment says so plainly — it's the
// one automated change a user could be surprised by.
func (o *Orchestrator) adaptBindMountedDataDir(name string, svc *compose.Service, claimed map[string]bool, pgdataFixApplies bool) ([]serviceAdaptation, bool) {
	var out []serviceAdaptation
	swappedPostgres := false
	for _, v := range svc.Volumes {
		src, target, mode, ok := splitMount(v)
		if !ok || !isHostPath(src) {
			continue
		}
		// Both must hold: the path is a database data directory AND this service
		// is the database that owns it. A read-only mount rules it out — a database
		// can't run on one, so the service is something else looking at the files.
		helps, needsPGDATA, decision := o.swapHelpsHere(svc, target)
		if !helps || readOnlyMount(mode) || !runsAsServer(svc) {
			continue
		}
		// The swap is half a fix for an image that initialises elsewhere. Without the
		// other half the project does not start, so say what was found instead of
		// writing something that looks like a fix.
		if needsPGDATA && !pgdataFixApplies {
			out = append(out, o.notePGDATAHalfMissing(name, svc, target, decision))
			continue
		}

		// Another service on the same host directory means deliberate sharing;
		// splitting it is the user's call, not ours.
		if o.sharesHostDataDir(name, src) {
			continue
		}
		// The service's main data directory gets the plain "<svc>-data"; a second one
		// (mongo's /data/configdb) is named after its path, so the two are telling
		// apart at a glance and can't collide.
		base := compose.SanitizeName(name) + "-data"
		if len(out) > 0 {
			base = compose.SanitizeName(name) + "-" + compose.SanitizeName(pathLeaf(target))
		}
		vol := o.freeVolumeName(base, claimed)
		if target == postgresDataDir {
			swappedPostgres = true
		}
		out = append(out, serviceAdaptation{
			Adaptation: Adaptation{
				Service: name,
				Code:    string(codeBindDataDirChown),
				Summary: fmt.Sprintf("service %q: data directory %s moved from the host path %s to a named volume %q", name, target, src, vol),
			},
			comment: commentBlock(
				fmt.Sprintf("%s service %q: %s now uses the named volume %q instead of the host path %q.", overlayMarker, esc(name), esc(target), vol, esc(src)),
				append([]string{
					"Apple container bind-mounts host directories read-write but host-owned,",
					"and they cannot be chowned from inside the container. Official database",
					"images chown their data directory at startup, so they fail on a bind",
					fmt.Sprintf("mount. A named volume is chownable. Diagnostic: %s.", codeBindDataDirChown),
				}, append(howWeKnowTheDataDir(svc, decision), []string{
					"NOTE: this changes where the data lives. The database now writes into",
					fmt.Sprintf("the volume, not into %s. Existing data in that directory is", esc(src)),
					"not copied — it is left untouched on the host.",
				}...)...),
				[]string{
					fmt.Sprintf("after `opossum up`, `opossum logs %s` should show the database", name),
					"initializing and accepting connections, with no chown error.",
				},
				[]string{
					fmt.Sprintf("run `opossum logs %s` and `opossum doctor`, then match the error", name),
					"against the failure-signatures table in AGENTS.md.",
				},
			),
			block:   "volumes",
			entries: []string{fmt.Sprintf("      - %s:%s", esc(vol), esc(target))},
			volume:  vol,
		})
	}
	return out, swappedPostgres
}

// isDockerSocketMount reports whether a bind mount is about the Docker socket,
// by either end of it.
//
// Two callers: the note below and warnDockerSocket, which since #599 asks
// this same question — one run no longer says opposite things about one
// socket. The pre-flight refusal used to ask it too, to withhold its offer of
// mounting what the link points at — on the reading that the offer could not
// help here. Measured, it does: a container started here reaches a daemon
// through the resolved path. So the refusal makes the same offer to everyone,
// and what is worth saying about that daemon is said once, here.
//
// The last path element, not the whole path. Matching anywhere would call a
// gpg-agent socket under a directory named `docker.sock.d/` a Docker socket
// and tell its owner about a daemon that has nothing to do with it.
func isDockerSocketMount(src, target string) bool {
	return pathLeaf(src) == "docker.sock" || pathLeaf(target) == "docker.sock"
}

// pathLeaf is the last non-empty path element ("/data/configdb" -> "configdb"),
// used to keep a second volume on the same service distinguishable.
func pathLeaf(p string) string {
	parts := strings.Split(strings.Trim(p, "/"), "/")
	if len(parts) == 0 {
		return "data"
	}
	return parts[len(parts)-1]
}

// adaptPGDATA points PGDATA at a subdirectory when Postgres's data directory is a
// named volume. Purely additive (an environment variable), and the data stays
// inside the same volume — the safest fix in the set, and the most common need.
//
// It fires when the data dir is already a named volume, and also when
// adaptBindMountedDataDir is about to make it one.
//
// It keeps firing even though opossum now clears `lost+found` out of the volumes
// it creates, which is what made the plain mount work. The overlay is a file: it
// outlives the volume it was written for, and is read again on machines and days
// where that volume is not the one opossum made. Dropping the line would also
// strand a cluster already initialised one level down — the next up would find the
// mount point holding `pgdata/`, which is not empty either. A durable artefact
// should not encode a fact that is only true of the moment it was written.
func (o *Orchestrator) adaptPGDATA(name string, svc *compose.Service, willBeNamedVolume bool) (serviceAdaptation, bool) {
	// Any PGDATA the user set is theirs. Checking only for "a subdirectory of the
	// default datadir" would treat a deliberate PGDATA elsewhere (a second volume,
	// say) as unfixed and overwrite it — pointing Postgres at an empty directory
	// and initdb'ing a new cluster, while their real one sits untouched and
	// unreachable. Silence beats a fix here.
	if hasPGDATA(svc) {
		return serviceAdaptation{}, false
	}
	// A mount below the data directory would be stranded above the new PGDATA.
	if hasNestedDataDirMount(svc) {
		return serviceAdaptation{}, false
	}
	for _, v := range svc.Volumes {
		src, target, mode, ok := splitMount(v)
		if !ok || target != postgresDataDir {
			continue
		}
		// Only the Postgres that owns the directory, and never a read-only mount
		// (a database can't run on one) — same reasoning as the bind-mount fix.
		if !ownsDataDir(svc, target) || readOnlyMount(mode) {
			continue
		}
		// The redirection exists because a NAMED VOLUME's mount point isn't empty.
		// It must fire for a named volume today, or for a host path this overlay is
		// converting into one — but never for a bind mount that stays a bind mount
		// (its directory is the user's, initdb is happy with it, and moving PGDATA
		// would just relocate their data a level down for no reason).
		if isHostPath(src) && !willBeNamedVolume {
			continue
		}
		if !isNamedVolume(src) && !isHostPath(src) {
			continue
		}
		if isNamedVolume(src) && o.isExternalVolume(src) {
			continue // an external volume is the user's to manage
		}
		sub := postgresDataDir + "/pgdata"
		return serviceAdaptation{
			Adaptation: Adaptation{
				Service: name,
				Code:    string(codePGDATADatadir),
				Summary: fmt.Sprintf("service %q: PGDATA pointed at %s (a subdirectory of the volume)", name, sub),
			},
			comment: commentBlock(
				fmt.Sprintf("%s service %q: PGDATA moved to a subdirectory of the data volume.", overlayMarker, esc(name)),
				[]string{
					"Apple container attaches a named volume as a filesystem mount point, so",
					"the directory can hold lost+found, which Postgres initdb refuses to",
					fmt.Sprintf("initialize into. Diagnostic: %s. opossum clears that from the", codePGDATADatadir),
					"volumes it creates, so this is belt and braces: it also covers a volume",
					"made before that, or by another tool. The data still lives inside the",
					"same volume, one level down.",
				},
				[]string{
					fmt.Sprintf("after `opossum up`, `opossum logs %s` should show initdb completing", name),
					"and the database accepting connections.",
				},
				[]string{
					fmt.Sprintf("run `opossum logs %s` and `opossum doctor`, then match the error", name),
					"against the failure-signatures table in AGENTS.md.",
				},
			),
			block:   "environment",
			entries: []string{fmt.Sprintf("      PGDATA: %s", sub)},
		}, true
	}
	return serviceAdaptation{}, false
}

// commentBlock renders the five-part contract every generated entry carries. The
// shape is fixed so a reader (often an agent) can rely on it: what changed, why it
// was needed, how to confirm it worked, what to do if it didn't, and how to undo
// it. Wrapped lines are indented so the block stays readable.
func commentBlock(what string, why, verify, ifFails []string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n", OneLine(what))
	commentSection(&b, "Why", why)
	commentSection(&b, "Verify", verify)
	commentSection(&b, "If this still fails", ifFails)
	commentSection(&b, "To undo", []string{
		"delete this entry, or this whole file. Your original compose file was",
		"not modified, and docker compose never reads this file.",
	})
	return b.String()
}

// renderOverlay assembles the overlay file: a header explaining what the file is,
// then one commented entry per adaptation, grouped under each service, then any
// named volumes the adaptations introduced.
func renderOverlay(plans []serviceAdaptation) string {
	var applied, suggestions, notes []serviceAdaptation
	for _, p := range plans {
		switch p.class {
		case classSuggestion:
			suggestions = append(suggestions, p)
		case classNote:
			notes = append(notes, p)
		default:
			applied = append(applied, p)
		}
	}

	var b strings.Builder
	b.WriteString(overlayGeneratedHeader + "\n" +
		"#\n" +
		"# This file adapts the compose project to Apple's `container` runtime. opossum\n" +
		"# merges it last, at the highest precedence, on top of your compose file and any\n" +
		"# compose.override.yaml. docker compose does not read this file, so the same\n" +
		"# directory still works with both tools and your own files are unchanged.\n" +
		"#\n" +
		"# Entries come in three kinds, and each says which it is:\n" +
		"#   " + overlayMarker + "  — applied. This is live.\n" +
		"#   " + suggestionMarker + " — written out but commented; uncomment to apply.\n" +
		"#   " + noteMarker + "                    — things " + NoteFrame + "; recorded so\n" +
		"#                                        the failure isn't a mystery.\n" +
		"#\n" +
		"# Every entry says what it is about, why, how to check it, and how to undo it.\n" +
		"# Edit or delete anything here — opossum will not overwrite this file.\n")

	if len(applied) > 0 {
		b.WriteString("\nservices:\n")
		b.WriteString(renderServiceBlocks(applied, false))
	}
	if len(suggestions) > 0 {
		b.WriteString("\n# ── Suggestions ─────────────────────────────────────────────────────────\n" +
			"# opossum did NOT make these changes: each alters what the project means, so\n" +
			"# the call is yours. Uncommenting a whole block applies it (the `services:`\n" +
			"# line included — this file is merged like any compose file).\n")
		b.WriteString(commentOut("services:\n" + renderServiceBlocks(suggestions, true)))
	}
	if len(notes) > 0 {
		b.WriteString("\n# ── Notes ───────────────────────────────────────────────────────────────\n" +
			"# These are things " + NoteFrame + ".\n")
		for _, n := range notes {
			b.WriteString(strings.TrimRight(n.comment, "\n") + "\n")
		}
	}

	var volumes []string
	for _, p := range applied {
		if p.volume != "" {
			volumes = append(volumes, p.volume)
		}
	}
	if len(volumes) > 0 {
		sort.Strings(volumes)
		b.WriteString("\nvolumes:\n")
		for _, v := range volumes {
			fmt.Fprintf(&b, "  %s: {}\n", esc(yamlKey(v)))
		}
	}
	return b.String()
}

// renderServiceBlocks lays entries out as compose, grouped by service, each
// preceded by its comment. Two entries on one service share a single YAML key.
func renderServiceBlocks(plans []serviceAdaptation, inlineVolumes bool) string {
	type group struct {
		name     string
		comments []string
		blocks   []string
		entries  map[string][]string
		volumes  []string
	}
	var groups []group
	index := map[string]int{}
	for _, p := range plans {
		i, ok := index[p.Service]
		if !ok {
			index[p.Service] = len(groups)
			groups = append(groups, group{name: p.Service, entries: map[string][]string{}})
			i = len(groups) - 1
		}
		groups[i].comments = append(groups[i].comments, p.comment)
		if p.block == "" {
			continue
		}
		if _, seen := groups[i].entries[p.block]; !seen {
			groups[i].blocks = append(groups[i].blocks, p.block)
		}
		groups[i].entries[p.block] = append(groups[i].entries[p.block], p.entries...)
		if p.volume != "" {
			groups[i].volumes = append(groups[i].volumes, p.volume)
		}
	}
	var b strings.Builder
	for _, g := range groups {
		for _, c := range g.comments {
			for _, line := range strings.Split(strings.TrimRight(c, "\n"), "\n") {
				b.WriteString("  " + line + "\n")
			}
		}
		fmt.Fprintf(&b, "  %s:\n", esc(yamlKey(g.name)))
		for _, blk := range g.blocks {
			fmt.Fprintf(&b, "    %s:\n", blk)
			for _, e := range g.entries[blk] {
				b.WriteString(e + "\n")
			}
		}
	}
	// A SUGGESTION that introduces volumes has to carry their declarations, or
	// uncommenting the block would leave the project referencing volumes nobody
	// declared. They go in ONE section after every service — a `volumes:` key
	// emitted between services would either be a duplicate top-level key (invalid
	// YAML) or, worse, swallow the services that follow it as if they were volume
	// declarations, so the later suggestions would silently do nothing.
	if inlineVolumes {
		var all []string
		seen := map[string]bool{}
		for _, g := range groups {
			for _, v := range g.volumes {
				if !seen[v] {
					seen[v] = true
					all = append(all, v)
				}
			}
		}
		if len(all) > 0 {
			sort.Strings(all)
			b.WriteString("volumes:\n")
			for _, v := range all {
				fmt.Fprintf(&b, "  %s: {}\n", esc(yamlKey(v)))
			}
		}
	}
	return b.String()
}

// commentOut prefixes every line with "# " so a block of real YAML sits inert in
// the file until someone uncomments it.
func commentOut(s string) string {
	var b strings.Builder
	for _, line := range strings.Split(strings.TrimRight(s, "\n"), "\n") {
		if line == "" {
			b.WriteString("#\n")
			continue
		}
		b.WriteString("# " + line + "\n")
	}
	return b.String()
}

// splitMount splits a short-form volumes entry into source, target and mode.
// Entries with no source (an anonymous volume) return ok=false: there's no host
// path or named volume to reason about.
func splitMount(v string) (src, target, mode string, ok bool) {
	parts := strings.SplitN(v, ":", 3)
	if len(parts) < 2 {
		return "", "", "", false
	}
	if len(parts) == 3 {
		mode = parts[2]
	}
	return parts[0], strings.TrimRight(parts[1], "/"), mode, true
}

// readOnlyMount reports whether a mount is read-only. A read-only mount is strong
// evidence the service is NOT the database that owns the directory — a database
// can't run on one — so those are never adapted.
func readOnlyMount(mode string) bool {
	for _, opt := range strings.Split(mode, ",") {
		if strings.TrimSpace(opt) == "ro" {
			return true
		}
	}
	return false
}

// esc escapes a user-derived string for the generated file. opossum interpolates
// ${VAR} over the raw text before parsing — comments included — so an unescaped
// `$` from a host path would be expanded on the next load, or fail the load
// outright ("unterminated variable reference") and leave the project unusable.
func esc(s string) string { return strings.ReplaceAll(s, "$", "$$") }

// plainYAMLKey matches names safe to emit as a bare YAML key.
var plainYAMLKey = regexp.MustCompile(`^[A-Za-z][A-Za-z0-9_-]*$`)

// yamlBareUnsafe are names that look like a bare scalar but parse as something
// else (a bool, a null). A service legitimately named `on` or `no` would silently
// become a different key — or vanish — when the merged tree round-trips through
// YAML, so they must be quoted.
var yamlBareUnsafe = map[string]bool{
	"y": true, "n": true, "yes": true, "no": true, "true": true, "false": true,
	"on": true, "off": true, "null": true, "nil": true, "~": true,
}

// yamlKey renders a name as a YAML mapping key, quoting whatever wouldn't survive
// as a bare scalar. Compose allows service names (digits, dots, reserved words)
// that a bare key would mangle — writing those unquoted produces a file that
// silently renames or drops the service.
func yamlKey(s string) string {
	if plainYAMLKey.MatchString(s) && !yamlBareUnsafe[strings.ToLower(s)] {
		return s
	}
	return strconv.Quote(s)
}

// hasPGDATA reports whether the service sets PGDATA at all — including the
// pass-through forms (`- PGDATA` in a list, `PGDATA:` with no value in a map),
// which are stored as a bare name with no `=` and take their value from the host
// environment. Missing those would overwrite a PGDATA the user is supplying at run
// time, which is the exact damage this guard exists to prevent.
func hasPGDATA(svc *compose.Service) bool {
	for _, e := range svc.Environment {
		if e == "PGDATA" || strings.HasPrefix(e, "PGDATA=") {
			return true
		}
	}
	return false
}

// servicesSharingHostDir names the other services mounting the same host
// directory. The applied path only needs to know whether any exist (it refuses);
// a failure-driven suggestion is kept — the crash is real — so it has to say who
// else is reading the directory it proposes detaching.
func (o *Orchestrator) servicesSharingHostDir(self, src string) []string {
	var peers []string
	for name, svc := range o.Project.Services {
		if name == self || svc == nil {
			continue
		}
		for _, v := range svc.Volumes {
			if s, _, _, ok := splitMount(v); ok && s == src {
				peers = append(peers, name)
				break
			}
		}
	}
	sort.Strings(peers)
	return peers
}

// sharesHostDataDir reports whether another service mounts the same host path.
// Two services on one host directory are sharing it deliberately — a database and
// a backup/inspection sidecar, typically. Giving each its own named volume would
// sever that silently: the sidecar would keep working against an empty volume and
// look healthy forever. Adapting only one is no better (the other would read a
// directory the database no longer writes), so this is a decision for the user.
func (o *Orchestrator) sharesHostDataDir(self, src string) bool {
	for name, svc := range o.Project.Services {
		if name == self || svc == nil {
			continue
		}
		for _, v := range svc.Volumes {
			if s, _, _, ok := splitMount(v); ok && s == src {
				return true
			}
		}
	}
	return false
}

// hasNestedDataDirMount reports whether the service mounts anything at a path
// below Postgres's data directory — an injected `postgresql.conf`, a dedicated
// `pg_wal`. Moving PGDATA down a level would leave those mounts one level above
// the new data directory, so the config would stop being read and the WAL
// directory would go unused, both without a word of complaint.
func hasNestedDataDirMount(svc *compose.Service) bool {
	for _, v := range svc.Volumes {
		_, target, _, ok := splitMount(v)
		if ok && strings.HasPrefix(target, postgresDataDir+"/") {
			return true
		}
	}
	return false
}

// freeVolumeName returns a volume name that no other adaptation has claimed, that
// the project doesn't declare, and that no service already mounts. Reusing a
// declared name would merge into that declaration — including an `external: true`
// one, pointing a freshly-initialized database at data the user manages elsewhere.
// Undeclared-but-mounted names matter just as much: compose doesn't require a
// declaration, so taking one would silently hand another service's volume to a
// database (and trip the exclusive-attach failure, OPSM-102).
func (o *Orchestrator) freeVolumeName(base string, claimed map[string]bool) string {
	used := map[string]bool{}
	for _, svc := range o.Project.Services {
		for _, v := range svc.Volumes {
			if src, _, _, ok := splitMount(v); ok && isNamedVolume(src) {
				used[src] = true
			}
		}
	}
	taken := func(n string) bool {
		if claimed[n] || used[n] {
			return true
		}
		_, declared := o.Project.Volumes[n]
		return declared
	}
	name := base
	for i := 2; taken(name); i++ {
		name = fmt.Sprintf("%s-%d", base, i)
	}
	claimed[name] = true
	return name
}

// suggestSharedVolumeFix proposes — without applying — a way out of the one
// incompatibility that is purely about sharing: Apple `container` attaches a named
// volume to a single container at a time, so two services that mount the same one
// cannot both run (OPSM-102). A host directory IS shareable, so swapping the
// volume for a bind mount fixes it.
//
// This is a suggestion rather than a fix because it changes what the project
// means: the data leaves the runtime's storage for a directory on the Mac, and
// that directory's contents and permissions become the user's problem. Nobody
// should discover that from a tool doing it silently.
func (o *Orchestrator) suggestSharedVolumeFix(order []string) []serviceAdaptation {
	users := map[string][]string{} // volume -> services mounting it
	target := map[string]string{}  // volume -> where the first user mounts it
	for _, name := range order {
		svc := o.Project.Services[name]
		if svc == nil {
			continue
		}
		for _, v := range svc.Volumes {
			src, tgt, _, ok := splitMount(v)
			if !ok || !isNamedVolume(src) || o.isExternalVolume(src) {
				continue
			}
			users[src] = append(users[src], name)
			if _, seen := target[src]; !seen {
				target[src] = tgt
			}
		}
	}
	var vols []string
	for v, u := range users {
		if len(u) > 1 {
			vols = append(vols, v)
		}
	}
	sort.Strings(vols)

	var out []serviceAdaptation
	for _, vol := range vols {
		svcs := users[vol]
		sort.Strings(svcs)
		host := "./" + compose.SanitizeName(vol)
		for _, name := range svcs {
			out = append(out, serviceAdaptation{
				Adaptation: Adaptation{
					Service: name,
					Code:    string(codeSharedVolume),
					Summary: fmt.Sprintf("service %q shares named volume %q with %d other service(s); a bind mount would let them all run", name, vol, len(svcs)-1),
				},
				class: classSuggestion,
				comment: suggestionBlock(
					fmt.Sprintf("%s service %q: mount the shared data from a host directory instead of the named volume %q.",
						suggestionMarker, esc(name), esc(vol)),
					[]string{
						"Apple container attaches a named volume to one container at a time, so",
						fmt.Sprintf("%s cannot all run while they share %q — whichever starts", quotedList(svcs), esc(vol)),
						"first gets it and the rest fail to attach. Diagnostic: " + string(codeSharedVolume) + ".",
						"A host directory is shareable, so a bind mount lets them all mount it.",
						"NOT APPLIED, because it changes what the project means: the data moves out",
						"of the runtime's storage onto the Mac, and that directory's contents and",
						"permissions become yours to manage. A database's data directory in",
						"particular should NOT be moved this way — it needs to be chownable.",
					},
					[]string{
						fmt.Sprintf("uncomment the block for every service sharing %q (all of them,", esc(vol)),
						"or none), create the directory, then `opossum up`. `opossum ps`",
						"should show them all running.",
					},
				),
				block:   "volumes",
				entries: []string{fmt.Sprintf("      - %s:%s", esc(host), esc(target[vol]))},
			})
		}
	}
	return out
}

// suggestionBlock renders a suggestion: what it proposes, why (with the code),
// and how to apply it. The YAML that follows is commented out by the renderer.
func suggestionBlock(what string, why, apply []string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n", OneLine(what))
	commentSection(&b, "Why", why)
	commentSection(&b, "To apply", apply)
	commentSection(&b, "To ignore", []string{"delete this block. Nothing here is in effect until you uncomment it."})
	return b.String()
}

// quotedList renders names for prose: `"a", "b" and "c"`.
func quotedList(names []string) string {
	q := make([]string, len(names))
	for i, n := range names {
		q[i] = fmt.Sprintf("%q", esc(n))
	}
	switch len(q) {
	case 0:
		return ""
	case 1:
		return q[0]
	}
	return strings.Join(q[:len(q)-1], ", ") + " and " + q[len(q)-1]
}

// handsThroughAFile reports whether a mount is passing one file into the
// container rather than handing over a directory.
//
// A bind source that does not exist is created as a directory whatever it was
// meant to be — docker compose does the same — so a file the user was told to
// supply becomes an empty directory, indistinguishable from a data directory by
// the time anything downstream looks at it. ensureBindDirs says so (OPSM-107)
// rather than let the failure surface later as something else.
//
// The shape it looks for is the same name on both sides with an extension
// (`./x.js:/somewhere/x.js`), which is how a single file is nearly always passed
// through. It misses a renamed file (`./config.yml:/app/conf.yml`) and one with no
// extension (`./CaddyFile:/etc/caddy/Caddyfile`) — both real shapes in the wild,
// both only worth a warning, never a change.
func handsThroughAFile(src, target string) bool {
	name := path.Base(target)
	return name == path.Base(src) && path.Ext(name) != ""
}

// suggestObservedChownFailures turns each recorded crash into a suggestion for
// the mount that actually died.
//
// Nothing here is inferred from the shape of a path. The service ran, its
// entrypoint tried to take ownership of that directory, and Apple `container`
// refused because a bind mount is host-owned — so the one thing a reader wants to
// know, whether this actually breaks, is already answered. That is the difference
// from the predicate this replaced, which proposed the same swap for any empty
// read-write bind directory and was wrong about half the time.
//
// A record is skipped when the project has moved on: the service or the mount may
// be gone, or the mount may already be a named volume because the suggestion was
// taken. The record is evidence of what happened, not an instruction to keep
// repeating it.
func (o *Orchestrator) suggestObservedChownFailures(plans []serviceAdaptation, claimed map[string]bool) []serviceAdaptation {
	var out []serviceAdaptation
	for _, f := range o.recordedChownFailures() {
		svc := o.Project.Services[f.Service]
		if svc == nil {
			continue
		}
		stillBound := false
		for _, v := range svc.Volumes {
			src, target, mode, ok := splitMount(v)
			if ok && src == f.Source && target == f.Target && !readOnlyMount(mode) && isHostPath(src) {
				stillBound = true
				break
			}
		}
		if !stillBound {
			continue
		}
		// Suppress only when this plan really did emit an applied swap for the same
		// mount. Asking `ownsDataDir` instead was close but not the same question:
		// the applied path also requires the service to run its image's own server
		// and the directory not to be shared, so a mysql with an overridden
		// entrypoint would be silenced here while nothing was applied — the crash
		// would leave no trace in the overlay at all.
		if appliedSameMount(plans, f.Service, f.Target) {
			continue
		}
		// Another service reading the same host directory is what makes this change
		// cost more than it looks: detaching it silently ends the sharing. The applied
		// path refuses outright for that reason; here the crash is real, so the entry
		// stays and names who else is looking.
		var sharedWith []string
		if peers := o.servicesSharingHostDir(f.Service, f.Source); len(peers) > 0 {
			sharedWith = []string{
				"CAREFUL: " + quotedList(peers) + " also mount " + esc(f.Source) + ".",
				"Switching this service to a volume ends that sharing — they keep reading",
				"the directory on the Mac while this one stops writing to it.",
			}
		}
		vol := o.freeVolumeName(compose.SanitizeName(f.Service)+"-"+compose.SanitizeName(pathLeaf(f.Target)), claimed)
		out = append(out, serviceAdaptation{
			Adaptation: Adaptation{
				Service: f.Service,
				Code:    string(codeBindDataDirChown),
				Summary: fmt.Sprintf("service %q died taking ownership of %s; a named volume can be chowned, a bind mount cannot", f.Service, f.Target),
			},
			class: classSuggestion,
			comment: suggestionBlock(
				fmt.Sprintf("%s service %q: use a named volume for %s instead of the host path %q.",
					suggestionMarker, esc(f.Service), esc(f.Target), esc(f.Source)),
				append([]string{
					"This is not a guess. That container started, tried to take ownership of",
					esc(f.Target) + ", and exited: Apple container bind mounts are",
					"host-owned and cannot be chowned from inside. A named volume can.",
					"Diagnostic: " + string(codeBindDataDirChown) + ".",
					"NOT APPLIED, because it moves where the data lives. Today it is on the",
					"Mac at " + esc(f.Source) + " and you can open it; afterwards it",
					"is inside a volume that only the runtime manages. Anything already in",
					"that directory stays where it is and the service stops seeing it.",
				}, sharedWith...),
				[]string{
					"uncomment this block, then `opossum up` again. To keep the data on the",
					"Mac instead, run the service as the user that owns the directory",
					"(`user:` in the compose file) so it has nothing to chown.",
				},
			),
			block:   "volumes",
			entries: []string{fmt.Sprintf("      - %s:%s", esc(vol), esc(f.Target))},
			volume:  vol,
		})
	}
	return out
}

// appliedSameMount reports whether the plan already changes this service's mount
// at target, so the overlay does not carry two blocks for one mount.
func appliedSameMount(plans []serviceAdaptation, service, target string) bool {
	for _, p := range plans {
		if p.class != classApplied || p.Service != service {
			continue
		}
		for _, e := range p.entries {
			if strings.HasSuffix(strings.TrimSpace(e), ":"+target) {
				return true
			}
		}
	}
	return false
}
