package compose

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// The `build` of a service is read as docker compose v5.5.1 reads it (#1592; every row measured with `docker compose config -q`): a
// key of it takes the type the compose specification gives it (a list of strings for `tags`, `cache_from` and `platforms`, a list or
// a mapping of names for `labels` and `args`, and so on), in every file — a service that is not taken, and one an extends takes
// from another file, included, whatever the extender writes over it. A key with nothing after it is asked by its own check
// (refused in a file, read where the extender writes over it). known marks the rows left as they were, with what is done:
// `additional_contexts`, whose shapes docker compose refuses are read as far as they go, on purpose (the key is not acted on:
// TestAdditionalContextsAreReadForTheirNames); a later file's null or value over it, which goes with that; and the keys docker
// compose casts a string into a boolean, a size, a `host=ip` or a limit and a secret that is not declared, which are not the schema's types
// and are asked by TestTheCastsAndFormsOfAServicesBuildAreReadAsDockerComposeReadsThem (#1783).
func TestTheBuildOfAServiceIsReadAsDockerComposeReadsIt(t *testing.T) {
	for _, tc := range []struct {
		name           string
		files          map[string]string
		order          []string
		refused, known bool
	}{
		{"additional_contexts: {a: ~}", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      additional_contexts:\n        a: ~\n"}, []string{"a.yaml"}, true, false},
		{"additional_contexts: {a: 1}", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      additional_contexts:\n        a: 1\n"}, []string{"a.yaml"}, false, true},
		{"additional_contexts: {a: true}", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      additional_contexts:\n        a: true\n"}, []string{"a.yaml"}, false, true},
		{"additional_contexts: {a: 1.5}", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      additional_contexts:\n        a: 1.5\n"}, []string{"a.yaml"}, false, true},
		{"additional_contexts: {a: [x]}", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      additional_contexts:\n        a: [x]\n"}, []string{"a.yaml"}, false, true},
		{"additional_contexts: {a: {b: 1}}", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      additional_contexts:\n        a: {b: 1}\n"}, []string{"a.yaml"}, false, true},
		{"additional_contexts: {a: \"x\"}", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      additional_contexts:\n        a: \"x\"\n"}, []string{"a.yaml"}, false, false},
		{"additional_contexts: {a: \"\"}", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      additional_contexts:\n        a: \"\"\n"}, []string{"a.yaml"}, false, false},
		{"additional_contexts: {a: \"docker-image://alpine\"}", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      additional_contexts:\n        a: \"docker-image://alpine\"\n"}, []string{"a.yaml"}, false, false},
		{"additional_contexts: {a: 2001-01-01}", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      additional_contexts:\n        a: 2001-01-01\n"}, []string{"a.yaml"}, false, true},
		{"additional_contexts: []", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      additional_contexts: []\n"}, []string{"a.yaml"}, false, false},
		{"additional_contexts: [a=b]", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      additional_contexts: [a=b]\n"}, []string{"a.yaml"}, false, false},
		{"additional_contexts: [a]", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      additional_contexts: [a]\n"}, []string{"a.yaml"}, false, true},
		{"additional_contexts: [\"a=\"]", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      additional_contexts: [\"a=\"]\n"}, []string{"a.yaml"}, false, false},
		{"additional_contexts: [1]", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      additional_contexts: [1]\n"}, []string{"a.yaml"}, false, true},
		{"additional_contexts: [~]", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      additional_contexts: [~]\n"}, []string{"a.yaml"}, false, true},
		{"additional_contexts: [{a: b}]", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      additional_contexts: [{a: b}]\n"}, []string{"a.yaml"}, false, true},
		{"additional_contexts: x", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      additional_contexts: x\n"}, []string{"a.yaml"}, false, true},
		{"additional_contexts: 1", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      additional_contexts: 1\n"}, []string{"a.yaml"}, false, true},
		{"additional_contexts: ~", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      additional_contexts: ~\n"}, []string{"a.yaml"}, false, true},
		{"additional_contexts: {}", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      additional_contexts: {}\n"}, []string{"a.yaml"}, false, false},
		{"a later file writes null over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      additional_contexts:\n        a: x\n", "b.yaml": "services:\n  a:\n    build:\n      additional_contexts:\n        a:\n"}, []string{"a.yaml", "b.yaml"}, false, true},
		{"a later file writes a value over null", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      additional_contexts:\n        a: ~\n", "b.yaml": "services:\n  a:\n    build:\n      additional_contexts:\n        a: y\n"}, []string{"a.yaml", "b.yaml"}, true, true},
		{"a later file writes a value over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      additional_contexts:\n        a: x\n", "b.yaml": "services:\n  a:\n    build:\n      additional_contexts:\n        a: y\n"}, []string{"a.yaml", "b.yaml"}, false, false},
		{"build.args: a: ~", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      args:\n        a: ~\n"}, []string{"a.yaml"}, false, false},
		{"build.args: a: 1", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      args:\n        a: 1\n"}, []string{"a.yaml"}, false, false},
		{"build.args: a: [x]", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      args:\n        a: [x]\n"}, []string{"a.yaml"}, true, false},
		{"build.args: a: {b: 1}", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      args:\n        a: {b: 1}\n"}, []string{"a.yaml"}, true, false},
		{"build.args: a: true", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      args:\n        a: true\n"}, []string{"a.yaml"}, false, false},
		{"build.labels: a: ~", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      labels:\n        a: ~\n"}, []string{"a.yaml"}, false, false},
		{"build.labels: a: 1", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      labels:\n        a: 1\n"}, []string{"a.yaml"}, false, false},
		{"build.labels: a: [x]", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      labels:\n        a: [x]\n"}, []string{"a.yaml"}, true, false},
		{"build.labels: a: {b: 1}", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      labels:\n        a: {b: 1}\n"}, []string{"a.yaml"}, true, false},
		{"build.labels: \"\": 1", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      labels:\n        \"\": 1\n"}, []string{"a.yaml"}, true, false},
		{"build.extra_hosts: a: ~", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      extra_hosts:\n        a: ~\n"}, []string{"a.yaml"}, true, false},
		{"build.extra_hosts: a: 1", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      extra_hosts:\n        a: 1\n"}, []string{"a.yaml"}, true, false},
		{"build.extra_hosts: a: [x]", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      extra_hosts:\n        a: [x]\n"}, []string{"a.yaml"}, false, false},
		{"build.cache_from: [~]", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      cache_from: [~]\n"}, []string{"a.yaml"}, true, false},
		{"build.cache_from: [1]", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      cache_from: [1]\n"}, []string{"a.yaml"}, true, false},
		{"build.cache_from: [x]", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      cache_from: [x]\n"}, []string{"a.yaml"}, false, false},
		{"build.tags: [~]", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      tags: [~]\n"}, []string{"a.yaml"}, true, false},
		{"build.tags: [1]", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      tags: [1]\n"}, []string{"a.yaml"}, true, false},
		{"build.tags: [x]", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      tags: [x]\n"}, []string{"a.yaml"}, false, false},
		{"build.platforms: [~]", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      platforms: [~]\n"}, []string{"a.yaml"}, true, false},
		{"build.platforms: [1]", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      platforms: [1]\n"}, []string{"a.yaml"}, true, false},
		{"build.platforms: [x]", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      platforms: [x]\n"}, []string{"a.yaml"}, false, false},
		{"build.secrets: [~]", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      secrets: [~]\n"}, []string{"a.yaml"}, true, false},
		{"build.secrets: [1]", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      secrets: [1]\n"}, []string{"a.yaml"}, true, false},
		{"build.secrets: [x]", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      secrets: [x]\n"}, []string{"a.yaml"}, true, false},
		{"build.args: 1", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      args: 1\n"}, []string{"compose.yaml"}, true, false},
		{"build.args: true", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      args: true\n"}, []string{"compose.yaml"}, true, false},
		{"build.args: x", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      args: x\n"}, []string{"compose.yaml"}, true, false},
		{"build.args: \"x\"", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      args: \"x\"\n"}, []string{"compose.yaml"}, true, false},
		{"build.args: [x]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      args: [x]\n"}, []string{"compose.yaml"}, false, false},
		{"build.args: [1]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      args: [1]\n"}, []string{"compose.yaml"}, true, false},
		{"build.args: [~]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      args: [~]\n"}, []string{"compose.yaml"}, true, false},
		{"build.args: [a=b]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      args: [a=b]\n"}, []string{"compose.yaml"}, false, false},
		{"build.args: {a: b}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      args: {a: b}\n"}, []string{"compose.yaml"}, false, false},
		{"build.args: {a: 1}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      args: {a: 1}\n"}, []string{"compose.yaml"}, false, false},
		{"build.args: {a: [x]}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      args: {a: [x]}\n"}, []string{"compose.yaml"}, true, false},
		{"build.args: {a: {b: 1}}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      args: {a: {b: 1}}\n"}, []string{"compose.yaml"}, true, false},
		{"build.args: 1.5", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      args: 1.5\n"}, []string{"compose.yaml"}, true, false},
		{"build.args: \"\"", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      args: \"\"\n"}, []string{"compose.yaml"}, true, false},
		{"build.cache_from: 1", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      cache_from: 1\n"}, []string{"compose.yaml"}, true, false},
		{"build.cache_from: true", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      cache_from: true\n"}, []string{"compose.yaml"}, true, false},
		{"build.cache_from: x", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      cache_from: x\n"}, []string{"compose.yaml"}, true, false},
		{"build.cache_from: \"x\"", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      cache_from: \"x\"\n"}, []string{"compose.yaml"}, true, false},
		{"build.cache_from: [a=b]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      cache_from: [a=b]\n"}, []string{"compose.yaml"}, false, false},
		{"build.cache_from: {a: b}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      cache_from: {a: b}\n"}, []string{"compose.yaml"}, true, false},
		{"build.cache_from: {a: 1}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      cache_from: {a: 1}\n"}, []string{"compose.yaml"}, true, false},
		{"build.cache_from: {a: [x]}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      cache_from: {a: [x]}\n"}, []string{"compose.yaml"}, true, false},
		{"build.cache_from: {a: {b: 1}}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      cache_from: {a: {b: 1}}\n"}, []string{"compose.yaml"}, true, false},
		{"build.cache_from: 1.5", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      cache_from: 1.5\n"}, []string{"compose.yaml"}, true, false},
		{"build.cache_from: \"\"", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      cache_from: \"\"\n"}, []string{"compose.yaml"}, true, false},
		{"build.cache_to: 1", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      cache_to: 1\n"}, []string{"compose.yaml"}, true, false},
		{"build.cache_to: true", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      cache_to: true\n"}, []string{"compose.yaml"}, true, false},
		{"build.cache_to: x", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      cache_to: x\n"}, []string{"compose.yaml"}, true, false},
		{"build.cache_to: \"x\"", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      cache_to: \"x\"\n"}, []string{"compose.yaml"}, true, false},
		{"build.cache_to: [x]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      cache_to: [x]\n"}, []string{"compose.yaml"}, false, false},
		{"build.cache_to: [1]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      cache_to: [1]\n"}, []string{"compose.yaml"}, true, false},
		{"build.cache_to: [~]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      cache_to: [~]\n"}, []string{"compose.yaml"}, true, false},
		{"build.cache_to: [a=b]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      cache_to: [a=b]\n"}, []string{"compose.yaml"}, false, false},
		{"build.cache_to: {a: b}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      cache_to: {a: b}\n"}, []string{"compose.yaml"}, true, false},
		{"build.cache_to: {a: 1}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      cache_to: {a: 1}\n"}, []string{"compose.yaml"}, true, false},
		{"build.cache_to: {a: [x]}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      cache_to: {a: [x]}\n"}, []string{"compose.yaml"}, true, false},
		{"build.cache_to: {a: {b: 1}}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      cache_to: {a: {b: 1}}\n"}, []string{"compose.yaml"}, true, false},
		{"build.cache_to: 1.5", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      cache_to: 1.5\n"}, []string{"compose.yaml"}, true, false},
		{"build.cache_to: \"\"", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      cache_to: \"\"\n"}, []string{"compose.yaml"}, true, false},
		{"build.dockerfile: 1", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      dockerfile: 1\n"}, []string{"compose.yaml"}, true, false},
		{"build.dockerfile: true", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      dockerfile: true\n"}, []string{"compose.yaml"}, true, false},
		{"build.dockerfile: x", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      dockerfile: x\n"}, []string{"compose.yaml"}, false, false},
		{"build.dockerfile: \"x\"", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      dockerfile: \"x\"\n"}, []string{"compose.yaml"}, false, false},
		{"build.dockerfile: [x]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      dockerfile: [x]\n"}, []string{"compose.yaml"}, true, false},
		{"build.dockerfile: [1]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      dockerfile: [1]\n"}, []string{"compose.yaml"}, true, false},
		{"build.dockerfile: [~]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      dockerfile: [~]\n"}, []string{"compose.yaml"}, true, false},
		{"build.dockerfile: [a=b]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      dockerfile: [a=b]\n"}, []string{"compose.yaml"}, true, false},
		{"build.dockerfile: {a: b}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      dockerfile: {a: b}\n"}, []string{"compose.yaml"}, true, false},
		{"build.dockerfile: {a: 1}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      dockerfile: {a: 1}\n"}, []string{"compose.yaml"}, true, false},
		{"build.dockerfile: {a: [x]}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      dockerfile: {a: [x]}\n"}, []string{"compose.yaml"}, true, false},
		{"build.dockerfile: {a: {b: 1}}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      dockerfile: {a: {b: 1}}\n"}, []string{"compose.yaml"}, true, false},
		{"build.dockerfile: 1.5", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      dockerfile: 1.5\n"}, []string{"compose.yaml"}, true, false},
		{"build.dockerfile: \"\"", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      dockerfile: \"\"\n"}, []string{"compose.yaml"}, false, false},
		{"build.dockerfile_inline: 1", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      dockerfile_inline: 1\n"}, []string{"compose.yaml"}, true, false},
		{"build.dockerfile_inline: true", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      dockerfile_inline: true\n"}, []string{"compose.yaml"}, true, false},
		{"build.dockerfile_inline: x", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      dockerfile_inline: x\n"}, []string{"compose.yaml"}, false, false},
		{"build.dockerfile_inline: \"x\"", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      dockerfile_inline: \"x\"\n"}, []string{"compose.yaml"}, false, false},
		{"build.dockerfile_inline: [x]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      dockerfile_inline: [x]\n"}, []string{"compose.yaml"}, true, false},
		{"build.dockerfile_inline: [1]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      dockerfile_inline: [1]\n"}, []string{"compose.yaml"}, true, false},
		{"build.dockerfile_inline: [~]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      dockerfile_inline: [~]\n"}, []string{"compose.yaml"}, true, false},
		{"build.dockerfile_inline: [a=b]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      dockerfile_inline: [a=b]\n"}, []string{"compose.yaml"}, true, false},
		{"build.dockerfile_inline: {a: b}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      dockerfile_inline: {a: b}\n"}, []string{"compose.yaml"}, true, false},
		{"build.dockerfile_inline: {a: 1}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      dockerfile_inline: {a: 1}\n"}, []string{"compose.yaml"}, true, false},
		{"build.dockerfile_inline: {a: [x]}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      dockerfile_inline: {a: [x]}\n"}, []string{"compose.yaml"}, true, false},
		{"build.dockerfile_inline: {a: {b: 1}}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      dockerfile_inline: {a: {b: 1}}\n"}, []string{"compose.yaml"}, true, false},
		{"build.dockerfile_inline: 1.5", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      dockerfile_inline: 1.5\n"}, []string{"compose.yaml"}, true, false},
		{"build.dockerfile_inline: \"\"", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      dockerfile_inline: \"\"\n"}, []string{"compose.yaml"}, false, false},
		{"build.entitlements: 1", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      entitlements: 1\n"}, []string{"compose.yaml"}, true, false},
		{"build.entitlements: true", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      entitlements: true\n"}, []string{"compose.yaml"}, true, false},
		{"build.entitlements: x", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      entitlements: x\n"}, []string{"compose.yaml"}, true, false},
		{"build.entitlements: \"x\"", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      entitlements: \"x\"\n"}, []string{"compose.yaml"}, true, false},
		{"build.entitlements: [x]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      entitlements: [x]\n"}, []string{"compose.yaml"}, false, false},
		{"build.entitlements: [1]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      entitlements: [1]\n"}, []string{"compose.yaml"}, true, false},
		{"build.entitlements: [~]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      entitlements: [~]\n"}, []string{"compose.yaml"}, true, false},
		{"build.entitlements: [a=b]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      entitlements: [a=b]\n"}, []string{"compose.yaml"}, false, false},
		{"build.entitlements: {a: b}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      entitlements: {a: b}\n"}, []string{"compose.yaml"}, true, false},
		{"build.entitlements: {a: 1}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      entitlements: {a: 1}\n"}, []string{"compose.yaml"}, true, false},
		{"build.entitlements: {a: [x]}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      entitlements: {a: [x]}\n"}, []string{"compose.yaml"}, true, false},
		{"build.entitlements: {a: {b: 1}}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      entitlements: {a: {b: 1}}\n"}, []string{"compose.yaml"}, true, false},
		{"build.entitlements: 1.5", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      entitlements: 1.5\n"}, []string{"compose.yaml"}, true, false},
		{"build.entitlements: \"\"", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      entitlements: \"\"\n"}, []string{"compose.yaml"}, true, false},
		{"build.extra_hosts: 1", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      extra_hosts: 1\n"}, []string{"compose.yaml"}, true, false},
		{"build.extra_hosts: true", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      extra_hosts: true\n"}, []string{"compose.yaml"}, true, false},
		{"build.extra_hosts: x", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      extra_hosts: x\n"}, []string{"compose.yaml"}, true, false},
		{"build.extra_hosts: \"x\"", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      extra_hosts: \"x\"\n"}, []string{"compose.yaml"}, true, false},
		{"build.extra_hosts: [x]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      extra_hosts: [x]\n"}, []string{"compose.yaml"}, true, false},
		{"build.extra_hosts: [1]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      extra_hosts: [1]\n"}, []string{"compose.yaml"}, true, false},
		{"build.extra_hosts: [~]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      extra_hosts: [~]\n"}, []string{"compose.yaml"}, true, false},
		{"build.extra_hosts: [a=b]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      extra_hosts: [a=b]\n"}, []string{"compose.yaml"}, false, false},
		{"build.extra_hosts: {a: b}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      extra_hosts: {a: b}\n"}, []string{"compose.yaml"}, false, false},
		{"build.extra_hosts: {a: 1}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      extra_hosts: {a: 1}\n"}, []string{"compose.yaml"}, true, false},
		{"build.extra_hosts: {a: [x]}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      extra_hosts: {a: [x]}\n"}, []string{"compose.yaml"}, false, false},
		{"build.extra_hosts: {a: {b: 1}}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      extra_hosts: {a: {b: 1}}\n"}, []string{"compose.yaml"}, true, false},
		{"build.extra_hosts: 1.5", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      extra_hosts: 1.5\n"}, []string{"compose.yaml"}, true, false},
		{"build.extra_hosts: \"\"", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      extra_hosts: \"\"\n"}, []string{"compose.yaml"}, true, false},
		{"build.isolation: 1", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      isolation: 1\n"}, []string{"compose.yaml"}, true, false},
		{"build.isolation: true", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      isolation: true\n"}, []string{"compose.yaml"}, true, false},
		{"build.isolation: x", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      isolation: x\n"}, []string{"compose.yaml"}, false, false},
		{"build.isolation: \"x\"", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      isolation: \"x\"\n"}, []string{"compose.yaml"}, false, false},
		{"build.isolation: [x]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      isolation: [x]\n"}, []string{"compose.yaml"}, true, false},
		{"build.isolation: [1]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      isolation: [1]\n"}, []string{"compose.yaml"}, true, false},
		{"build.isolation: [~]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      isolation: [~]\n"}, []string{"compose.yaml"}, true, false},
		{"build.isolation: [a=b]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      isolation: [a=b]\n"}, []string{"compose.yaml"}, true, false},
		{"build.isolation: {a: b}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      isolation: {a: b}\n"}, []string{"compose.yaml"}, true, false},
		{"build.isolation: {a: 1}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      isolation: {a: 1}\n"}, []string{"compose.yaml"}, true, false},
		{"build.isolation: {a: [x]}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      isolation: {a: [x]}\n"}, []string{"compose.yaml"}, true, false},
		{"build.isolation: {a: {b: 1}}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      isolation: {a: {b: 1}}\n"}, []string{"compose.yaml"}, true, false},
		{"build.isolation: 1.5", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      isolation: 1.5\n"}, []string{"compose.yaml"}, true, false},
		{"build.isolation: \"\"", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      isolation: \"\"\n"}, []string{"compose.yaml"}, false, false},
		{"build.labels: 1", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      labels: 1\n"}, []string{"compose.yaml"}, true, false},
		{"build.labels: true", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      labels: true\n"}, []string{"compose.yaml"}, true, false},
		{"build.labels: x", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      labels: x\n"}, []string{"compose.yaml"}, true, false},
		{"build.labels: \"x\"", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      labels: \"x\"\n"}, []string{"compose.yaml"}, true, false},
		{"build.labels: [x]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      labels: [x]\n"}, []string{"compose.yaml"}, false, false},
		{"build.labels: [1]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      labels: [1]\n"}, []string{"compose.yaml"}, true, false},
		{"build.labels: [~]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      labels: [~]\n"}, []string{"compose.yaml"}, true, false},
		{"build.labels: [a=b]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      labels: [a=b]\n"}, []string{"compose.yaml"}, false, false},
		{"build.labels: {a: b}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      labels: {a: b}\n"}, []string{"compose.yaml"}, false, false},
		{"build.labels: {a: 1}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      labels: {a: 1}\n"}, []string{"compose.yaml"}, false, false},
		{"build.labels: {a: [x]}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      labels: {a: [x]}\n"}, []string{"compose.yaml"}, true, false},
		{"build.labels: {a: {b: 1}}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      labels: {a: {b: 1}}\n"}, []string{"compose.yaml"}, true, false},
		{"build.labels: 1.5", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      labels: 1.5\n"}, []string{"compose.yaml"}, true, false},
		{"build.labels: \"\"", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      labels: \"\"\n"}, []string{"compose.yaml"}, true, false},
		{"build.network: 1", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      network: 1\n"}, []string{"compose.yaml"}, true, false},
		{"build.network: true", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      network: true\n"}, []string{"compose.yaml"}, true, false},
		{"build.network: x", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      network: x\n"}, []string{"compose.yaml"}, false, false},
		{"build.network: \"x\"", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      network: \"x\"\n"}, []string{"compose.yaml"}, false, false},
		{"build.network: [x]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      network: [x]\n"}, []string{"compose.yaml"}, true, false},
		{"build.network: [1]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      network: [1]\n"}, []string{"compose.yaml"}, true, false},
		{"build.network: [~]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      network: [~]\n"}, []string{"compose.yaml"}, true, false},
		{"build.network: [a=b]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      network: [a=b]\n"}, []string{"compose.yaml"}, true, false},
		{"build.network: {a: b}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      network: {a: b}\n"}, []string{"compose.yaml"}, true, false},
		{"build.network: {a: 1}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      network: {a: 1}\n"}, []string{"compose.yaml"}, true, false},
		{"build.network: {a: [x]}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      network: {a: [x]}\n"}, []string{"compose.yaml"}, true, false},
		{"build.network: {a: {b: 1}}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      network: {a: {b: 1}}\n"}, []string{"compose.yaml"}, true, false},
		{"build.network: 1.5", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      network: 1.5\n"}, []string{"compose.yaml"}, true, false},
		{"build.network: \"\"", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      network: \"\"\n"}, []string{"compose.yaml"}, false, false},
		{"build.no_cache: 1", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      no_cache: 1\n"}, []string{"compose.yaml"}, true, false},
		{"build.no_cache: true", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      no_cache: true\n"}, []string{"compose.yaml"}, false, false},
		{"build.no_cache: x", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      no_cache: x\n"}, []string{"compose.yaml"}, true, false},
		{"build.no_cache: \"x\"", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      no_cache: \"x\"\n"}, []string{"compose.yaml"}, true, false},
		{"build.no_cache: [x]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      no_cache: [x]\n"}, []string{"compose.yaml"}, true, false},
		{"build.no_cache: [1]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      no_cache: [1]\n"}, []string{"compose.yaml"}, true, false},
		{"build.no_cache: [~]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      no_cache: [~]\n"}, []string{"compose.yaml"}, true, false},
		{"build.no_cache: [a=b]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      no_cache: [a=b]\n"}, []string{"compose.yaml"}, true, false},
		{"build.no_cache: {a: b}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      no_cache: {a: b}\n"}, []string{"compose.yaml"}, true, false},
		{"build.no_cache: {a: 1}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      no_cache: {a: 1}\n"}, []string{"compose.yaml"}, true, false},
		{"build.no_cache: {a: [x]}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      no_cache: {a: [x]}\n"}, []string{"compose.yaml"}, true, false},
		{"build.no_cache: {a: {b: 1}}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      no_cache: {a: {b: 1}}\n"}, []string{"compose.yaml"}, true, false},
		{"build.no_cache: 1.5", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      no_cache: 1.5\n"}, []string{"compose.yaml"}, true, false},
		{"build.no_cache: \"\"", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      no_cache: \"\"\n"}, []string{"compose.yaml"}, true, false},
		{"build.no_cache_filter: 1", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      no_cache_filter: 1\n"}, []string{"compose.yaml"}, true, false},
		{"build.no_cache_filter: true", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      no_cache_filter: true\n"}, []string{"compose.yaml"}, true, false},
		{"build.no_cache_filter: x", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      no_cache_filter: x\n"}, []string{"compose.yaml"}, false, false},
		{"build.no_cache_filter: \"x\"", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      no_cache_filter: \"x\"\n"}, []string{"compose.yaml"}, false, false},
		{"build.no_cache_filter: [x]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      no_cache_filter: [x]\n"}, []string{"compose.yaml"}, false, false},
		{"build.no_cache_filter: [1]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      no_cache_filter: [1]\n"}, []string{"compose.yaml"}, true, false},
		{"build.no_cache_filter: [~]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      no_cache_filter: [~]\n"}, []string{"compose.yaml"}, true, false},
		{"build.no_cache_filter: [a=b]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      no_cache_filter: [a=b]\n"}, []string{"compose.yaml"}, false, false},
		{"build.no_cache_filter: {a: b}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      no_cache_filter: {a: b}\n"}, []string{"compose.yaml"}, true, false},
		{"build.no_cache_filter: {a: 1}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      no_cache_filter: {a: 1}\n"}, []string{"compose.yaml"}, true, false},
		{"build.no_cache_filter: {a: [x]}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      no_cache_filter: {a: [x]}\n"}, []string{"compose.yaml"}, true, false},
		{"build.no_cache_filter: {a: {b: 1}}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      no_cache_filter: {a: {b: 1}}\n"}, []string{"compose.yaml"}, true, false},
		{"build.no_cache_filter: 1.5", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      no_cache_filter: 1.5\n"}, []string{"compose.yaml"}, true, false},
		{"build.no_cache_filter: \"\"", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      no_cache_filter: \"\"\n"}, []string{"compose.yaml"}, false, false},
		{"build.platforms: 1", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      platforms: 1\n"}, []string{"compose.yaml"}, true, false},
		{"build.platforms: true", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      platforms: true\n"}, []string{"compose.yaml"}, true, false},
		{"build.platforms: x", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      platforms: x\n"}, []string{"compose.yaml"}, true, false},
		{"build.platforms: \"x\"", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      platforms: \"x\"\n"}, []string{"compose.yaml"}, true, false},
		{"build.platforms: [a=b]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      platforms: [a=b]\n"}, []string{"compose.yaml"}, false, false},
		{"build.platforms: {a: b}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      platforms: {a: b}\n"}, []string{"compose.yaml"}, true, false},
		{"build.platforms: {a: 1}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      platforms: {a: 1}\n"}, []string{"compose.yaml"}, true, false},
		{"build.platforms: {a: [x]}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      platforms: {a: [x]}\n"}, []string{"compose.yaml"}, true, false},
		{"build.platforms: {a: {b: 1}}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      platforms: {a: {b: 1}}\n"}, []string{"compose.yaml"}, true, false},
		{"build.platforms: 1.5", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      platforms: 1.5\n"}, []string{"compose.yaml"}, true, false},
		{"build.platforms: \"\"", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      platforms: \"\"\n"}, []string{"compose.yaml"}, true, false},
		{"build.privileged: 1", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      privileged: 1\n"}, []string{"compose.yaml"}, true, false},
		{"build.privileged: true", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      privileged: true\n"}, []string{"compose.yaml"}, false, false},
		{"build.privileged: x", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      privileged: x\n"}, []string{"compose.yaml"}, true, false},
		{"build.privileged: \"x\"", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      privileged: \"x\"\n"}, []string{"compose.yaml"}, true, false},
		{"build.privileged: [x]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      privileged: [x]\n"}, []string{"compose.yaml"}, true, false},
		{"build.privileged: [1]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      privileged: [1]\n"}, []string{"compose.yaml"}, true, false},
		{"build.privileged: [~]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      privileged: [~]\n"}, []string{"compose.yaml"}, true, false},
		{"build.privileged: [a=b]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      privileged: [a=b]\n"}, []string{"compose.yaml"}, true, false},
		{"build.privileged: {a: b}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      privileged: {a: b}\n"}, []string{"compose.yaml"}, true, false},
		{"build.privileged: {a: 1}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      privileged: {a: 1}\n"}, []string{"compose.yaml"}, true, false},
		{"build.privileged: {a: [x]}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      privileged: {a: [x]}\n"}, []string{"compose.yaml"}, true, false},
		{"build.privileged: {a: {b: 1}}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      privileged: {a: {b: 1}}\n"}, []string{"compose.yaml"}, true, false},
		{"build.privileged: 1.5", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      privileged: 1.5\n"}, []string{"compose.yaml"}, true, false},
		{"build.privileged: \"\"", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      privileged: \"\"\n"}, []string{"compose.yaml"}, true, false},
		{"build.provenance: 1", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      provenance: 1\n"}, []string{"compose.yaml"}, true, false},
		{"build.provenance: true", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      provenance: true\n"}, []string{"compose.yaml"}, false, false},
		{"build.provenance: x", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      provenance: x\n"}, []string{"compose.yaml"}, false, false},
		{"build.provenance: \"x\"", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      provenance: \"x\"\n"}, []string{"compose.yaml"}, false, false},
		{"build.provenance: [x]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      provenance: [x]\n"}, []string{"compose.yaml"}, true, false},
		{"build.provenance: [1]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      provenance: [1]\n"}, []string{"compose.yaml"}, true, false},
		{"build.provenance: [~]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      provenance: [~]\n"}, []string{"compose.yaml"}, true, false},
		{"build.provenance: [a=b]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      provenance: [a=b]\n"}, []string{"compose.yaml"}, true, false},
		{"build.provenance: {a: b}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      provenance: {a: b}\n"}, []string{"compose.yaml"}, true, false},
		{"build.provenance: {a: 1}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      provenance: {a: 1}\n"}, []string{"compose.yaml"}, true, false},
		{"build.provenance: {a: [x]}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      provenance: {a: [x]}\n"}, []string{"compose.yaml"}, true, false},
		{"build.provenance: {a: {b: 1}}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      provenance: {a: {b: 1}}\n"}, []string{"compose.yaml"}, true, false},
		{"build.provenance: 1.5", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      provenance: 1.5\n"}, []string{"compose.yaml"}, true, false},
		{"build.provenance: \"\"", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      provenance: \"\"\n"}, []string{"compose.yaml"}, false, false},
		{"build.pull: 1", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      pull: 1\n"}, []string{"compose.yaml"}, true, false},
		{"build.pull: true", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      pull: true\n"}, []string{"compose.yaml"}, false, false},
		{"build.pull: x", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      pull: x\n"}, []string{"compose.yaml"}, true, false},
		{"build.pull: \"x\"", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      pull: \"x\"\n"}, []string{"compose.yaml"}, true, false},
		{"build.pull: [x]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      pull: [x]\n"}, []string{"compose.yaml"}, true, false},
		{"build.pull: [1]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      pull: [1]\n"}, []string{"compose.yaml"}, true, false},
		{"build.pull: [~]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      pull: [~]\n"}, []string{"compose.yaml"}, true, false},
		{"build.pull: [a=b]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      pull: [a=b]\n"}, []string{"compose.yaml"}, true, false},
		{"build.pull: {a: b}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      pull: {a: b}\n"}, []string{"compose.yaml"}, true, false},
		{"build.pull: {a: 1}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      pull: {a: 1}\n"}, []string{"compose.yaml"}, true, false},
		{"build.pull: {a: [x]}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      pull: {a: [x]}\n"}, []string{"compose.yaml"}, true, false},
		{"build.pull: {a: {b: 1}}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      pull: {a: {b: 1}}\n"}, []string{"compose.yaml"}, true, false},
		{"build.pull: 1.5", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      pull: 1.5\n"}, []string{"compose.yaml"}, true, false},
		{"build.pull: \"\"", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      pull: \"\"\n"}, []string{"compose.yaml"}, true, false},
		{"build.sbom: 1", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      sbom: 1\n"}, []string{"compose.yaml"}, true, false},
		{"build.sbom: true", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      sbom: true\n"}, []string{"compose.yaml"}, false, false},
		{"build.sbom: x", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      sbom: x\n"}, []string{"compose.yaml"}, false, false},
		{"build.sbom: \"x\"", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      sbom: \"x\"\n"}, []string{"compose.yaml"}, false, false},
		{"build.sbom: [x]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      sbom: [x]\n"}, []string{"compose.yaml"}, true, false},
		{"build.sbom: [1]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      sbom: [1]\n"}, []string{"compose.yaml"}, true, false},
		{"build.sbom: [~]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      sbom: [~]\n"}, []string{"compose.yaml"}, true, false},
		{"build.sbom: [a=b]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      sbom: [a=b]\n"}, []string{"compose.yaml"}, true, false},
		{"build.sbom: {a: b}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      sbom: {a: b}\n"}, []string{"compose.yaml"}, true, false},
		{"build.sbom: {a: 1}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      sbom: {a: 1}\n"}, []string{"compose.yaml"}, true, false},
		{"build.sbom: {a: [x]}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      sbom: {a: [x]}\n"}, []string{"compose.yaml"}, true, false},
		{"build.sbom: {a: {b: 1}}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      sbom: {a: {b: 1}}\n"}, []string{"compose.yaml"}, true, false},
		{"build.sbom: 1.5", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      sbom: 1.5\n"}, []string{"compose.yaml"}, true, false},
		{"build.sbom: \"\"", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      sbom: \"\"\n"}, []string{"compose.yaml"}, false, false},
		{"build.shm_size: 1", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      shm_size: 1\n"}, []string{"compose.yaml"}, false, false},
		{"build.shm_size: true", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      shm_size: true\n"}, []string{"compose.yaml"}, true, false},
		{"build.shm_size: x", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      shm_size: x\n"}, []string{"compose.yaml"}, true, false},
		{"build.shm_size: \"x\"", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      shm_size: \"x\"\n"}, []string{"compose.yaml"}, true, false},
		{"build.shm_size: [x]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      shm_size: [x]\n"}, []string{"compose.yaml"}, true, false},
		{"build.shm_size: [1]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      shm_size: [1]\n"}, []string{"compose.yaml"}, true, false},
		{"build.shm_size: [~]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      shm_size: [~]\n"}, []string{"compose.yaml"}, true, false},
		{"build.shm_size: [a=b]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      shm_size: [a=b]\n"}, []string{"compose.yaml"}, true, false},
		{"build.shm_size: {a: b}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      shm_size: {a: b}\n"}, []string{"compose.yaml"}, true, false},
		{"build.shm_size: {a: 1}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      shm_size: {a: 1}\n"}, []string{"compose.yaml"}, true, false},
		{"build.shm_size: {a: [x]}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      shm_size: {a: [x]}\n"}, []string{"compose.yaml"}, true, false},
		{"build.shm_size: {a: {b: 1}}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      shm_size: {a: {b: 1}}\n"}, []string{"compose.yaml"}, true, false},
		{"build.shm_size: 1.5", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      shm_size: 1.5\n"}, []string{"compose.yaml"}, true, false},
		{"build.shm_size: \"\"", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      shm_size: \"\"\n"}, []string{"compose.yaml"}, true, false},
		{"build.ssh: 1", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      ssh: 1\n"}, []string{"compose.yaml"}, true, false},
		{"build.ssh: true", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      ssh: true\n"}, []string{"compose.yaml"}, true, false},
		{"build.ssh: x", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      ssh: x\n"}, []string{"compose.yaml"}, true, false},
		{"build.ssh: \"x\"", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      ssh: \"x\"\n"}, []string{"compose.yaml"}, true, false},
		{"build.ssh: [x]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      ssh: [x]\n"}, []string{"compose.yaml"}, true, false},
		{"build.ssh: [1]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      ssh: [1]\n"}, []string{"compose.yaml"}, true, false},
		{"build.ssh: [~]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      ssh: [~]\n"}, []string{"compose.yaml"}, true, false},
		{"build.ssh: [a=b]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      ssh: [a=b]\n"}, []string{"compose.yaml"}, false, false},
		{"build.ssh: {a: b}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      ssh: {a: b}\n"}, []string{"compose.yaml"}, false, false},
		{"build.ssh: {a: 1}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      ssh: {a: 1}\n"}, []string{"compose.yaml"}, false, false},
		{"build.ssh: {a: [x]}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      ssh: {a: [x]}\n"}, []string{"compose.yaml"}, true, false},
		{"build.ssh: {a: {b: 1}}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      ssh: {a: {b: 1}}\n"}, []string{"compose.yaml"}, true, false},
		{"build.ssh: 1.5", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      ssh: 1.5\n"}, []string{"compose.yaml"}, true, false},
		{"build.ssh: \"\"", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      ssh: \"\"\n"}, []string{"compose.yaml"}, true, false},
		{"build.tags: 1", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      tags: 1\n"}, []string{"compose.yaml"}, true, false},
		{"build.tags: true", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      tags: true\n"}, []string{"compose.yaml"}, true, false},
		{"build.tags: x", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      tags: x\n"}, []string{"compose.yaml"}, true, false},
		{"build.tags: \"x\"", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      tags: \"x\"\n"}, []string{"compose.yaml"}, true, false},
		{"build.tags: [a=b]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      tags: [a=b]\n"}, []string{"compose.yaml"}, false, false},
		{"build.tags: {a: b}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      tags: {a: b}\n"}, []string{"compose.yaml"}, true, false},
		{"build.tags: {a: 1}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      tags: {a: 1}\n"}, []string{"compose.yaml"}, true, false},
		{"build.tags: {a: [x]}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      tags: {a: [x]}\n"}, []string{"compose.yaml"}, true, false},
		{"build.tags: {a: {b: 1}}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      tags: {a: {b: 1}}\n"}, []string{"compose.yaml"}, true, false},
		{"build.tags: 1.5", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      tags: 1.5\n"}, []string{"compose.yaml"}, true, false},
		{"build.tags: \"\"", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      tags: \"\"\n"}, []string{"compose.yaml"}, true, false},
		{"build.target: 1", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      target: 1\n"}, []string{"compose.yaml"}, true, false},
		{"build.target: true", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      target: true\n"}, []string{"compose.yaml"}, true, false},
		{"build.target: x", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      target: x\n"}, []string{"compose.yaml"}, false, false},
		{"build.target: \"x\"", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      target: \"x\"\n"}, []string{"compose.yaml"}, false, false},
		{"build.target: [x]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      target: [x]\n"}, []string{"compose.yaml"}, true, false},
		{"build.target: [1]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      target: [1]\n"}, []string{"compose.yaml"}, true, false},
		{"build.target: [~]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      target: [~]\n"}, []string{"compose.yaml"}, true, false},
		{"build.target: [a=b]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      target: [a=b]\n"}, []string{"compose.yaml"}, true, false},
		{"build.target: {a: b}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      target: {a: b}\n"}, []string{"compose.yaml"}, true, false},
		{"build.target: {a: 1}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      target: {a: 1}\n"}, []string{"compose.yaml"}, true, false},
		{"build.target: {a: [x]}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      target: {a: [x]}\n"}, []string{"compose.yaml"}, true, false},
		{"build.target: {a: {b: 1}}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      target: {a: {b: 1}}\n"}, []string{"compose.yaml"}, true, false},
		{"build.target: 1.5", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      target: 1.5\n"}, []string{"compose.yaml"}, true, false},
		{"build.target: \"\"", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      target: \"\"\n"}, []string{"compose.yaml"}, false, false},
		{"build.ulimits: 1", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      ulimits: 1\n"}, []string{"compose.yaml"}, true, false},
		{"build.ulimits: true", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      ulimits: true\n"}, []string{"compose.yaml"}, true, false},
		{"build.ulimits: x", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      ulimits: x\n"}, []string{"compose.yaml"}, true, false},
		{"build.ulimits: \"x\"", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      ulimits: \"x\"\n"}, []string{"compose.yaml"}, true, false},
		{"build.ulimits: [x]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      ulimits: [x]\n"}, []string{"compose.yaml"}, true, false},
		{"build.ulimits: [1]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      ulimits: [1]\n"}, []string{"compose.yaml"}, true, false},
		{"build.ulimits: [~]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      ulimits: [~]\n"}, []string{"compose.yaml"}, true, false},
		{"build.ulimits: [a=b]", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      ulimits: [a=b]\n"}, []string{"compose.yaml"}, true, false},
		{"build.ulimits: {a: b}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      ulimits: {a: b}\n"}, []string{"compose.yaml"}, true, false},
		{"build.ulimits: {a: 1}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      ulimits: {a: 1}\n"}, []string{"compose.yaml"}, false, false},
		{"build.ulimits: {a: [x]}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      ulimits: {a: [x]}\n"}, []string{"compose.yaml"}, true, false},
		{"build.ulimits: {a: {b: 1}}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      ulimits: {a: {b: 1}}\n"}, []string{"compose.yaml"}, true, false},
		{"build.ulimits: 1.5", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      ulimits: 1.5\n"}, []string{"compose.yaml"}, true, false},
		{"build.ulimits: \"\"", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      ulimits: \"\"\n"}, []string{"compose.yaml"}, true, false},
		{"build.secrets: 1", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      secrets: 1\n"}, []string{"compose.yaml"}, true, false},
		{"build.secrets: true", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      secrets: true\n"}, []string{"compose.yaml"}, true, false},
		{"build.secrets: {a: b}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      secrets: {a: b}\n"}, []string{"compose.yaml"}, true, false},
		{"build.secrets: {a: 1}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      secrets: {a: 1}\n"}, []string{"compose.yaml"}, true, false},
		{"build.secrets: {a: [x]}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      secrets: {a: [x]}\n"}, []string{"compose.yaml"}, true, false},
		{"build.secrets: {a: {b: 1}}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      secrets: {a: {b: 1}}\n"}, []string{"compose.yaml"}, true, false},
		{"build.secrets: 1.5", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      secrets: 1.5\n"}, []string{"compose.yaml"}, true, false},
		{"build.secrets: \"\"", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      secrets: \"\"\n"}, []string{"compose.yaml"}, true, false},
		{"extends taken, stays: labels list with a number", map[string]string{"base.yaml": "services:\n  base:\n    image: x\n    build:\n      context: .\n      labels: [x, 1]\n", "compose.yaml": "services:\n  a:\n    extends: {file: base.yaml, service: base}\n"}, []string{"compose.yaml"}, true, false},
		{"extends taken, the extender writes build over it", map[string]string{"base.yaml": "services:\n  base:\n    image: x\n    build:\n      context: .\n      labels: [x, 1]\n", "compose.yaml": "services:\n  a:\n    extends: {file: base.yaml, service: base}\n    build:\n      labels: !override [a=b]\n"}, []string{"compose.yaml"}, true, false},
		{"extends taken, the extender resets build", map[string]string{"base.yaml": "services:\n  base:\n    image: x\n    build:\n      context: .\n      labels: [x, 1]\n", "compose.yaml": "services:\n  a:\n    extends: {file: base.yaml, service: base}\n    build: !reset null\n"}, []string{"compose.yaml"}, true, false},
		{"extends: a service of the extended file that is not taken", map[string]string{"base.yaml": "services:\n  base:\n    image: x\n  other:\n    image: x\n    build:\n      context: .\n      labels: [x, 1]\n", "compose.yaml": "services:\n  a:\n    extends: {file: base.yaml, service: base}\n"}, []string{"compose.yaml"}, true, false},
		{"a later file writes the bad shape", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    build: .\n", "b.yaml": "services:\n  a:\n    build:\n      labels: [x, 1]\n"}, []string{"a.yaml", "b.yaml"}, true, false},
		{"a later file writes a good shape over a bad one", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      labels: [x, 1]\n", "b.yaml": "services:\n  a:\n    build:\n      labels: !override [a=b]\n"}, []string{"a.yaml", "b.yaml"}, true, false},
		{"a profile service", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    profiles: [p]\n    build:\n      context: .\n      tags: [1]\n"}, []string{"compose.yaml"}, true, false},
		{"the second service", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n  b:\n    image: x\n    build:\n      context: .\n      tags: [x, 1]\n"}, []string{"compose.yaml"}, true, false},
		{"build as a string", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build: .\n"}, []string{"compose.yaml"}, false, false},
		{"build as a number", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build: 1\n"}, []string{"compose.yaml"}, true, false},
		{"build with two bad keys, the second bad", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      tags: [x]\n      cache_from: [1]\n"}, []string{"compose.yaml"}, true, false},
		{"build.labels: {\"\": a}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      labels: {\"\": a}\n"}, []string{"compose.yaml"}, true, false},
		{"build.labels: {\"\": [x]}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      labels: {\"\": [x]}\n"}, []string{"compose.yaml"}, true, false},
		{"build.extra_hosts: {\"\": a}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      extra_hosts: {\"\": a}\n"}, []string{"compose.yaml"}, true, false},
		{"build.extra_hosts: {\"\": 1}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      extra_hosts: {\"\": 1}\n"}, []string{"compose.yaml"}, true, false},
		{"build.ssh: {\"\": a}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      ssh: {\"\": a}\n"}, []string{"compose.yaml"}, true, false},
		{"build.ssh: {\"\": [x]}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      ssh: {\"\": [x]}\n"}, []string{"compose.yaml"}, true, false},
		{"build.labels: {additional_contexts: [x]}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      labels: {additional_contexts: [x]}\n"}, []string{"compose.yaml"}, true, false},
		{"build.labels: {additional_contexts: a}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      labels: {additional_contexts: a}\n"}, []string{"compose.yaml"}, false, false},
		{"build.args: {additional_contexts: [x]}", map[string]string{"compose.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      args: {additional_contexts: [x]}\n"}, []string{"compose.yaml"}, true, false},
		{"extends taken: a null tags is written over", map[string]string{"base.yaml": "services:\n  base:\n    image: x\n    build:\n      context: .\n      tags:\n", "compose.yaml": "services:\n  a:\n    extends: {file: base.yaml, service: base}\n    build:\n      tags: [x]\n"}, []string{"compose.yaml"}, false, false},
		{"extends taken: a null network is written over", map[string]string{"base.yaml": "services:\n  base:\n    image: x\n    build:\n      context: .\n      network:\n", "compose.yaml": "services:\n  a:\n    extends: {file: base.yaml, service: base}\n    build:\n      network: host\n"}, []string{"compose.yaml"}, false, false},
		{"extends taken: a null ulimit field is written over", map[string]string{"base.yaml": "services:\n  base:\n    image: x\n    build:\n      context: .\n      ulimits:\n        nofile:\n          soft:\n          hard: 2\n", "compose.yaml": "services:\n  a:\n    extends: {file: base.yaml, service: base}\n    build:\n      ulimits:\n        nofile: {soft: 1, hard: 2}\n"}, []string{"compose.yaml"}, false, false},
		{"extends taken: a null tags stays", map[string]string{"base.yaml": "services:\n  base:\n    image: x\n    build:\n      context: .\n      tags:\n", "compose.yaml": "services:\n  a:\n    extends: {file: base.yaml, service: base}\n"}, []string{"compose.yaml"}, true, false},
		{"extends taken: a null ulimit field stays", map[string]string{"base.yaml": "services:\n  base:\n    image: x\n    build:\n      context: .\n      ulimits:\n        nofile:\n          soft:\n          hard: 2\n", "compose.yaml": "services:\n  a:\n    extends: {file: base.yaml, service: base}\n"}, []string{"compose.yaml"}, true, false},
	} {
		t.Run(tc.name, func(t *testing.T) {
			dir := t.TempDir()
			for name, body := range tc.files {
				if err := os.WriteFile(filepath.Join(dir, name), []byte(body), 0o644); err != nil {
					t.Fatal(err)
				}
			}
			var paths []string
			for _, name := range tc.order {
				paths = append(paths, filepath.Join(dir, name))
			}
			_, err := LoadFiles(paths, nil)
			if (err != nil) != tc.refused {
				t.Errorf("refused is %v, want %v (err %v)", err != nil, tc.refused, err)
			}
		})
	}
}

// A refusal names the key it is about: `services.a.build.tags[0]`.
func TestTheRefusalOfABuildShapeNamesTheKey(t *testing.T) {
	for _, tc := range []struct{ name, build, want string }{
		{"a list item", "tags: [x, 1]", "services.a.build.tags[1]"},
		{"a mapping's value", "labels: {a: [x]}", "services.a.build.labels.a"},
		{"a kind", "platforms: x", "services.a.build.platforms"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			path := filepath.Join(t.TempDir(), "compose.yaml")
			if err := os.WriteFile(path, []byte("services:\n  a:\n    image: x\n    build:\n      context: .\n      "+tc.build+"\n"), 0o644); err != nil {
				t.Fatal(err)
			}
			_, err := Load(path)
			if err == nil {
				t.Fatal("the shape was read")
			}
			if !strings.Contains(err.Error(), tc.want) {
				t.Errorf("the refusal is %q, want it to name %q", err, tc.want)
			}
		})
	}
}
