package compose

import (
	"os"
	"path/filepath"
	"testing"
)

// A null a `<<` merge key brings is read as one written where the key stands (#1594; every row measured with `docker compose
// config -q`, v5.5.1): over a value an earlier file gave, the keys docker compose refuses with nothing after them whatever an
// earlier file holds (`networks`, `depends_on`, `logging` and `models` as a whole, `logging.driver`, `healthcheck.test`, an
// entry of `ulimits` and of `extra_hosts`) are refused when the null comes by a merge key too, and the others are "not given" and
// leave the earlier value — through one merge key, a list of them, an inline one, a merge key of a merge key, and beside a written key (which wins); a key written as an alias (`*k : v`) is the name it stands for, directly and through a merge key.
func TestANullAMergeKeyBringsIsAskedOfWhatAnEarlierFileHolds(t *testing.T) {
	for _, tc := range []struct {
		name    string
		files   map[string]string
		order   []string
		refused bool
	}{
		{"networks: single file, via a merge key", map[string]string{"a.yaml": "x-e: &e\n  networks:\nservices:\n  a:\n    image: x\n    <<: *e\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n"}, []string{"a.yaml"}, true},
		{"networks: single file, via an alias of null", map[string]string{"a.yaml": "x-n: &n ~\nservices:\n  a:\n    image: x\n    networks: *n\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n"}, []string{"a.yaml"}, true},
		{"networks: a later file, via a merge key, over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    networks: [default]\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n", "b.yaml": "x-e: &e\n  networks:\nservices:\n  a:\n    <<: *e\n"}, []string{"a.yaml", "b.yaml"}, true},
		{"networks: a later file, via an alias of null, over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    networks: [default]\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n", "b.yaml": "x-n: &n ~\nservices:\n  a:\n    networks: *n\n"}, []string{"a.yaml", "b.yaml"}, true},
		{"networks: a later file, plainly null, over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    networks: [default]\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n", "b.yaml": "services:\n  a:\n    networks:\n"}, []string{"a.yaml", "b.yaml"}, true},
		{"depends_on: single file, via a merge key", map[string]string{"a.yaml": "x-e: &e\n  depends_on:\nservices:\n  a:\n    image: x\n    <<: *e\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n"}, []string{"a.yaml"}, true},
		{"depends_on: single file, via an alias of null", map[string]string{"a.yaml": "x-n: &n ~\nservices:\n  a:\n    image: x\n    depends_on: *n\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n"}, []string{"a.yaml"}, true},
		{"depends_on: a later file, via a merge key, over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    depends_on: [db]\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n", "b.yaml": "x-e: &e\n  depends_on:\nservices:\n  a:\n    <<: *e\n"}, []string{"a.yaml", "b.yaml"}, true},
		{"depends_on: a later file, via an alias of null, over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    depends_on: [db]\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n", "b.yaml": "x-n: &n ~\nservices:\n  a:\n    depends_on: *n\n"}, []string{"a.yaml", "b.yaml"}, true},
		{"depends_on: a later file, plainly null, over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    depends_on: [db]\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n", "b.yaml": "services:\n  a:\n    depends_on:\n"}, []string{"a.yaml", "b.yaml"}, true},
		{"logging: single file, via a merge key", map[string]string{"a.yaml": "x-e: &e\n  logging:\nservices:\n  a:\n    image: x\n    <<: *e\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n"}, []string{"a.yaml"}, true},
		{"logging: single file, via an alias of null", map[string]string{"a.yaml": "x-n: &n ~\nservices:\n  a:\n    image: x\n    logging: *n\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n"}, []string{"a.yaml"}, true},
		{"logging: a later file, via a merge key, over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    logging: {driver: json-file}\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n", "b.yaml": "x-e: &e\n  logging:\nservices:\n  a:\n    <<: *e\n"}, []string{"a.yaml", "b.yaml"}, true},
		{"logging: a later file, via an alias of null, over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    logging: {driver: json-file}\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n", "b.yaml": "x-n: &n ~\nservices:\n  a:\n    logging: *n\n"}, []string{"a.yaml", "b.yaml"}, true},
		{"logging: a later file, plainly null, over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    logging: {driver: json-file}\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n", "b.yaml": "services:\n  a:\n    logging:\n"}, []string{"a.yaml", "b.yaml"}, true},
		{"dns: single file, via a merge key", map[string]string{"a.yaml": "x-e: &e\n  dns:\nservices:\n  a:\n    image: x\n    <<: *e\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n"}, []string{"a.yaml"}, true},
		{"dns: single file, via an alias of null", map[string]string{"a.yaml": "x-n: &n ~\nservices:\n  a:\n    image: x\n    dns: *n\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n"}, []string{"a.yaml"}, true},
		{"dns: a later file, via a merge key, over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    dns: [1.1.1.1]\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n", "b.yaml": "x-e: &e\n  dns:\nservices:\n  a:\n    <<: *e\n"}, []string{"a.yaml", "b.yaml"}, false},
		{"dns: a later file, via an alias of null, over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    dns: [1.1.1.1]\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n", "b.yaml": "x-n: &n ~\nservices:\n  a:\n    dns: *n\n"}, []string{"a.yaml", "b.yaml"}, false},
		{"dns: a later file, plainly null, over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    dns: [1.1.1.1]\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n", "b.yaml": "services:\n  a:\n    dns:\n"}, []string{"a.yaml", "b.yaml"}, false},
		{"ports: single file, via a merge key", map[string]string{"a.yaml": "x-e: &e\n  ports:\nservices:\n  a:\n    image: x\n    <<: *e\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n"}, []string{"a.yaml"}, true},
		{"ports: single file, via an alias of null", map[string]string{"a.yaml": "x-n: &n ~\nservices:\n  a:\n    image: x\n    ports: *n\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n"}, []string{"a.yaml"}, true},
		{"ports: a later file, via a merge key, over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    ports: ['80:80']\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n", "b.yaml": "x-e: &e\n  ports:\nservices:\n  a:\n    <<: *e\n"}, []string{"a.yaml", "b.yaml"}, false},
		{"ports: a later file, via an alias of null, over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    ports: ['80:80']\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n", "b.yaml": "x-n: &n ~\nservices:\n  a:\n    ports: *n\n"}, []string{"a.yaml", "b.yaml"}, false},
		{"ports: a later file, plainly null, over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    ports: ['80:80']\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n", "b.yaml": "services:\n  a:\n    ports:\n"}, []string{"a.yaml", "b.yaml"}, false},
		{"working_dir: single file, via a merge key", map[string]string{"a.yaml": "x-e: &e\n  working_dir:\nservices:\n  a:\n    image: x\n    <<: *e\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n"}, []string{"a.yaml"}, true},
		{"working_dir: single file, via an alias of null", map[string]string{"a.yaml": "x-n: &n ~\nservices:\n  a:\n    image: x\n    working_dir: *n\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n"}, []string{"a.yaml"}, true},
		{"working_dir: a later file, via a merge key, over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    working_dir: /w\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n", "b.yaml": "x-e: &e\n  working_dir:\nservices:\n  a:\n    <<: *e\n"}, []string{"a.yaml", "b.yaml"}, false},
		{"working_dir: a later file, via an alias of null, over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    working_dir: /w\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n", "b.yaml": "x-n: &n ~\nservices:\n  a:\n    working_dir: *n\n"}, []string{"a.yaml", "b.yaml"}, false},
		{"working_dir: a later file, plainly null, over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    working_dir: /w\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n", "b.yaml": "services:\n  a:\n    working_dir:\n"}, []string{"a.yaml", "b.yaml"}, false},
		{"command: single file, via a merge key", map[string]string{"a.yaml": "x-e: &e\n  command:\nservices:\n  a:\n    image: x\n    <<: *e\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n"}, []string{"a.yaml"}, false},
		{"command: single file, via an alias of null", map[string]string{"a.yaml": "x-n: &n ~\nservices:\n  a:\n    image: x\n    command: *n\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n"}, []string{"a.yaml"}, false},
		{"command: a later file, via a merge key, over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    command: [sh]\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n", "b.yaml": "x-e: &e\n  command:\nservices:\n  a:\n    <<: *e\n"}, []string{"a.yaml", "b.yaml"}, false},
		{"command: a later file, via an alias of null, over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    command: [sh]\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n", "b.yaml": "x-n: &n ~\nservices:\n  a:\n    command: *n\n"}, []string{"a.yaml", "b.yaml"}, false},
		{"command: a later file, plainly null, over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    command: [sh]\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n", "b.yaml": "services:\n  a:\n    command:\n"}, []string{"a.yaml", "b.yaml"}, false},
		{"environment: single file, via a merge key", map[string]string{"a.yaml": "x-e: &e\n  environment:\nservices:\n  a:\n    image: x\n    <<: *e\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n"}, []string{"a.yaml"}, true},
		{"environment: single file, via an alias of null", map[string]string{"a.yaml": "x-n: &n ~\nservices:\n  a:\n    image: x\n    environment: *n\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n"}, []string{"a.yaml"}, true},
		{"environment: a later file, via a merge key, over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    environment: {A: b}\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n", "b.yaml": "x-e: &e\n  environment:\nservices:\n  a:\n    <<: *e\n"}, []string{"a.yaml", "b.yaml"}, false},
		{"environment: a later file, via an alias of null, over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    environment: {A: b}\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n", "b.yaml": "x-n: &n ~\nservices:\n  a:\n    environment: *n\n"}, []string{"a.yaml", "b.yaml"}, false},
		{"environment: a later file, plainly null, over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    environment: {A: b}\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n", "b.yaml": "services:\n  a:\n    environment:\n"}, []string{"a.yaml", "b.yaml"}, false},
		{"labels: single file, via a merge key", map[string]string{"a.yaml": "x-e: &e\n  labels:\nservices:\n  a:\n    image: x\n    <<: *e\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n"}, []string{"a.yaml"}, true},
		{"labels: single file, via an alias of null", map[string]string{"a.yaml": "x-n: &n ~\nservices:\n  a:\n    image: x\n    labels: *n\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n"}, []string{"a.yaml"}, true},
		{"labels: a later file, via a merge key, over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    labels: {a: b}\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n", "b.yaml": "x-e: &e\n  labels:\nservices:\n  a:\n    <<: *e\n"}, []string{"a.yaml", "b.yaml"}, false},
		{"labels: a later file, via an alias of null, over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    labels: {a: b}\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n", "b.yaml": "x-n: &n ~\nservices:\n  a:\n    labels: *n\n"}, []string{"a.yaml", "b.yaml"}, false},
		{"labels: a later file, plainly null, over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    labels: {a: b}\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n", "b.yaml": "services:\n  a:\n    labels:\n"}, []string{"a.yaml", "b.yaml"}, false},
		{"extra_hosts: single file, via a merge key", map[string]string{"a.yaml": "x-e: &e\n  extra_hosts:\nservices:\n  a:\n    image: x\n    <<: *e\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n"}, []string{"a.yaml"}, true},
		{"extra_hosts: single file, via an alias of null", map[string]string{"a.yaml": "x-n: &n ~\nservices:\n  a:\n    image: x\n    extra_hosts: *n\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n"}, []string{"a.yaml"}, true},
		{"extra_hosts: a later file, via a merge key, over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    extra_hosts: {h: 1.2.3.4}\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n", "b.yaml": "x-e: &e\n  extra_hosts:\nservices:\n  a:\n    <<: *e\n"}, []string{"a.yaml", "b.yaml"}, false},
		{"extra_hosts: a later file, via an alias of null, over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    extra_hosts: {h: 1.2.3.4}\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n", "b.yaml": "x-n: &n ~\nservices:\n  a:\n    extra_hosts: *n\n"}, []string{"a.yaml", "b.yaml"}, false},
		{"extra_hosts: a later file, plainly null, over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    extra_hosts: {h: 1.2.3.4}\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n", "b.yaml": "services:\n  a:\n    extra_hosts:\n"}, []string{"a.yaml", "b.yaml"}, false},
		{"models: single file, via a merge key", map[string]string{"a.yaml": "x-e: &e\n  models:\nservices:\n  a:\n    image: x\n    <<: *e\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n"}, []string{"a.yaml"}, true},
		{"models: single file, via an alias of null", map[string]string{"a.yaml": "x-n: &n ~\nservices:\n  a:\n    image: x\n    models: *n\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n"}, []string{"a.yaml"}, true},
		{"models: a later file, via a merge key, over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    models: [m]\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n", "b.yaml": "x-e: &e\n  models:\nservices:\n  a:\n    <<: *e\n"}, []string{"a.yaml", "b.yaml"}, true},
		{"models: a later file, via an alias of null, over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    models: [m]\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n", "b.yaml": "x-n: &n ~\nservices:\n  a:\n    models: *n\n"}, []string{"a.yaml", "b.yaml"}, true},
		{"models: a later file, plainly null, over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    models: [m]\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n", "b.yaml": "services:\n  a:\n    models:\n"}, []string{"a.yaml", "b.yaml"}, true},
		{"healthcheck: single file, via a merge key", map[string]string{"a.yaml": "x-e: &e\n  healthcheck:\nservices:\n  a:\n    image: x\n    <<: *e\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n"}, []string{"a.yaml"}, true},
		{"healthcheck: single file, via an alias of null", map[string]string{"a.yaml": "x-n: &n ~\nservices:\n  a:\n    image: x\n    healthcheck: *n\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n"}, []string{"a.yaml"}, true},
		{"healthcheck: a later file, via a merge key, over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    healthcheck: {test: [CMD, 'true']}\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n", "b.yaml": "x-e: &e\n  healthcheck:\nservices:\n  a:\n    <<: *e\n"}, []string{"a.yaml", "b.yaml"}, false},
		{"healthcheck: a later file, via an alias of null, over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    healthcheck: {test: [CMD, 'true']}\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n", "b.yaml": "x-n: &n ~\nservices:\n  a:\n    healthcheck: *n\n"}, []string{"a.yaml", "b.yaml"}, false},
		{"healthcheck: a later file, plainly null, over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    healthcheck: {test: [CMD, 'true']}\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n", "b.yaml": "services:\n  a:\n    healthcheck:\n"}, []string{"a.yaml", "b.yaml"}, false},
		{"build: single file, via a merge key", map[string]string{"a.yaml": "x-e: &e\n  build:\nservices:\n  a:\n    image: x\n    <<: *e\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n"}, []string{"a.yaml"}, true},
		{"build: single file, via an alias of null", map[string]string{"a.yaml": "x-n: &n ~\nservices:\n  a:\n    image: x\n    build: *n\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n"}, []string{"a.yaml"}, true},
		{"build: a later file, via a merge key, over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    build: .\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n", "b.yaml": "x-e: &e\n  build:\nservices:\n  a:\n    <<: *e\n"}, []string{"a.yaml", "b.yaml"}, false},
		{"build: a later file, via an alias of null, over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    build: .\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n", "b.yaml": "x-n: &n ~\nservices:\n  a:\n    build: *n\n"}, []string{"a.yaml", "b.yaml"}, false},
		{"build: a later file, plainly null, over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    build: .\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n", "b.yaml": "services:\n  a:\n    build:\n"}, []string{"a.yaml", "b.yaml"}, false},
		{"ulimits: single file, via a merge key", map[string]string{"a.yaml": "x-e: &e\n  ulimits:\nservices:\n  a:\n    image: x\n    <<: *e\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n"}, []string{"a.yaml"}, true},
		{"ulimits: single file, via an alias of null", map[string]string{"a.yaml": "x-n: &n ~\nservices:\n  a:\n    image: x\n    ulimits: *n\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n"}, []string{"a.yaml"}, true},
		{"ulimits: a later file, via a merge key, over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    ulimits: {nofile: 100}\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n", "b.yaml": "x-e: &e\n  ulimits:\nservices:\n  a:\n    <<: *e\n"}, []string{"a.yaml", "b.yaml"}, false},
		{"ulimits: a later file, via an alias of null, over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    ulimits: {nofile: 100}\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n", "b.yaml": "x-n: &n ~\nservices:\n  a:\n    ulimits: *n\n"}, []string{"a.yaml", "b.yaml"}, false},
		{"ulimits: a later file, plainly null, over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    ulimits: {nofile: 100}\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n", "b.yaml": "services:\n  a:\n    ulimits:\n"}, []string{"a.yaml", "b.yaml"}, false},
		{"user: single file, via a merge key", map[string]string{"a.yaml": "x-e: &e\n  user:\nservices:\n  a:\n    image: x\n    <<: *e\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n"}, []string{"a.yaml"}, true},
		{"user: single file, via an alias of null", map[string]string{"a.yaml": "x-n: &n ~\nservices:\n  a:\n    image: x\n    user: *n\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n"}, []string{"a.yaml"}, true},
		{"user: a later file, via a merge key, over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    user: root\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n", "b.yaml": "x-e: &e\n  user:\nservices:\n  a:\n    <<: *e\n"}, []string{"a.yaml", "b.yaml"}, false},
		{"user: a later file, via an alias of null, over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    user: root\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n", "b.yaml": "x-n: &n ~\nservices:\n  a:\n    user: *n\n"}, []string{"a.yaml", "b.yaml"}, false},
		{"user: a later file, plainly null, over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    user: root\n  db:\n    image: x\nmodels:\n  m:\n    model: ai/x\n", "b.yaml": "services:\n  a:\n    user:\n"}, []string{"a.yaml", "b.yaml"}, false},
		{"logging.driver via <<: single file", map[string]string{"a.yaml": "x-d: &d\n  driver:\nservices:\n  a:\n    image: x\n    logging:\n      <<: *d\n"}, []string{"a.yaml"}, true},
		{"healthcheck.test via <<: single file", map[string]string{"a.yaml": "x-h: &h\n  test:\nservices:\n  a:\n    image: x\n    healthcheck:\n      <<: *h\n"}, []string{"a.yaml"}, true},
		{"deploy.labels via <<: single file", map[string]string{"a.yaml": "x-d: &d\n  labels:\nservices:\n  a:\n    image: x\n    deploy:\n      <<: *d\n"}, []string{"a.yaml"}, true},
		{"ulimits nofile via <<: single file", map[string]string{"a.yaml": "x-u: &u\n  nofile:\nservices:\n  a:\n    image: x\n    ulimits:\n      <<: *u\n"}, []string{"a.yaml"}, true},
		{"logging.driver: a later file, nested, via a merge key, over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    logging: {driver: json-file}\n  db:\n    image: x\n", "b.yaml": "x-d: &d\n  driver:\nservices:\n  a:\n    logging:\n      <<: *d\n"}, []string{"a.yaml", "b.yaml"}, true},
		{"healthcheck.test: a later file, nested, via a merge key, over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    healthcheck: {test: [CMD, 'true']}\n  db:\n    image: x\n", "b.yaml": "x-h: &h\n  test:\nservices:\n  a:\n    healthcheck:\n      <<: *h\n"}, []string{"a.yaml", "b.yaml"}, true},
		{"ulimits nofile: a later file, nested, via a merge key, over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    ulimits: {nofile: 100}\n  db:\n    image: x\n", "b.yaml": "x-u: &u\n  nofile:\nservices:\n  a:\n    ulimits:\n      <<: *u\n"}, []string{"a.yaml", "b.yaml"}, true},
		{"extra_hosts entry: a later file, nested, via a merge key, over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    extra_hosts: {h: 1.2.3.4}\n  db:\n    image: x\n", "b.yaml": "x-c: &c\n  h:\nservices:\n  a:\n    extra_hosts:\n      <<: *c\n"}, []string{"a.yaml", "b.yaml"}, true},
		{"build.extra_hosts entry: a later file, nested, via a merge key, over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    build:\n      context: .\n      extra_hosts: {h: 1.2.3.4}\n  db:\n    image: x\n", "b.yaml": "x-c: &c\n  h:\nservices:\n  a:\n    build:\n      extra_hosts:\n        <<: *c\n"}, []string{"a.yaml", "b.yaml"}, true},
		{"deploy.labels (not refused over a value): a later file, nested, via a merge key, over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    deploy: {labels: {a: b}}\n  db:\n    image: x\n", "b.yaml": "x-d: &d\n  labels:\nservices:\n  a:\n    deploy:\n      <<: *d\n"}, []string{"a.yaml", "b.yaml"}, false},
		{"environment var (a null is a value): a later file, nested, via a merge key, over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    environment: {A: b}\n  db:\n    image: x\n", "b.yaml": "x-e: &e\n  A:\nservices:\n  a:\n    environment:\n      <<: *e\n"}, []string{"a.yaml", "b.yaml"}, false},
		{"healthcheck.interval (not given over a value): a later file, nested, via a merge key, over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    healthcheck: {interval: 5s, test: [CMD, 'true']}\n  db:\n    image: x\n", "b.yaml": "x-h: &h\n  interval:\nservices:\n  a:\n    healthcheck:\n      <<: *h\n"}, []string{"a.yaml", "b.yaml"}, false},
		{"a whole service merged, networks null, over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    networks: [default]\n  db:\n    image: x\n", "b.yaml": "x-e: &e\n  networks:\nservices:\n  a:\n    <<: *e\n    working_dir: /w\n"}, []string{"a.yaml", "b.yaml"}, true},
		{"a list of merge anchors, one carrying a null networks", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    networks: [default]\n  db:\n    image: x\n", "b.yaml": "x-e: &e\n  networks:\nx-f: &f\n  working_dir: /w\nservices:\n  a:\n    <<: [*f, *e]\n"}, []string{"a.yaml", "b.yaml"}, true},
		{"the written value wins over a merged null", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    networks: [default]\n  db:\n    image: x\n", "b.yaml": "x-e: &e\n  networks:\nservices:\n  a:\n    <<: *e\n    networks: [default]\n"}, []string{"a.yaml", "b.yaml"}, false},
		{"a merged null loses to a written value (no earlier value)", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n  db:\n    image: x\n", "b.yaml": "x-e: &e\n  networks:\nservices:\n  a:\n    <<: *e\n    networks: [default]\n"}, []string{"a.yaml", "b.yaml"}, false},
		{"three files: a merge-key null in the middle, a value in the last", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    networks: [default]\n  db:\n    image: x\n", "b.yaml": "x-e: &e\n  networks:\nservices:\n  a:\n    <<: *e\n", "c.yaml": "services:\n  a:\n    networks: [default]\n"}, []string{"a.yaml", "b.yaml", "c.yaml"}, true},
		{"logging: the merge key beside another written key", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    logging: {driver: json-file}\n  db:\n    image: x\n", "b.yaml": "x-d: &d\n  driver:\nservices:\n  a:\n    logging:\n      options: {a: b}\n      <<: *d\n"}, []string{"a.yaml", "b.yaml"}, true},
		{"logging: a written driver wins over a merged null", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    logging: {driver: json-file}\n  db:\n    image: x\n", "b.yaml": "x-d: &d\n  driver:\nservices:\n  a:\n    logging:\n      driver: json-file\n      <<: *d\n"}, []string{"a.yaml", "b.yaml"}, false},
		{"logging: a written null driver wins over a merged value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    logging: {driver: json-file}\n  db:\n    image: x\n", "b.yaml": "x-d: &d\n  driver: syslog\nservices:\n  a:\n    logging:\n      driver:\n      <<: *d\n"}, []string{"a.yaml", "b.yaml"}, true},
		{"logging: the first of a list of merge anchors carries the null", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    logging: {driver: json-file}\n  db:\n    image: x\n", "b.yaml": "x-d: &d\n  driver:\nx-e: &e\n  driver: syslog\nservices:\n  a:\n    logging:\n      <<: [*d, *e]\n"}, []string{"a.yaml", "b.yaml"}, true},
		{"logging: the second of a list of merge anchors carries the null (the first wins)", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    logging: {driver: json-file}\n  db:\n    image: x\n", "b.yaml": "x-d: &d\n  driver:\nx-e: &e\n  driver: syslog\nservices:\n  a:\n    logging:\n      <<: [*e, *d]\n"}, []string{"a.yaml", "b.yaml"}, false},
		{"logging: a merge key of a merge key", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    logging: {driver: json-file}\n  db:\n    image: x\n", "b.yaml": "x-d: &d\n  driver:\nx-f: &f\n  <<: *d\nservices:\n  a:\n    logging:\n      <<: *f\n"}, []string{"a.yaml", "b.yaml"}, true},
		{"a merge key that is no mapping", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    logging: {driver: json-file}\n  db:\n    image: x\n", "b.yaml": "services:\n  a:\n    logging:\n      <<: 1\n"}, []string{"a.yaml", "b.yaml"}, true},
		{"an alias as the name of a key, directly", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    working_dir: /w\n  db:\n    image: x\n", "b.yaml": "x-k: &k working_dir\nservices:\n  a:\n    *k :\n"}, []string{"a.yaml", "b.yaml"}, false},
		{"an alias as the name of a key, through a merge key", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    working_dir: /w\n  db:\n    image: x\n", "b.yaml": "x-k: &k working_dir\nx-e: &e\n  *k :\nservices:\n  a:\n    <<: *e\n"}, []string{"a.yaml", "b.yaml"}, false},
		{"an alias as the name of a key that is refused over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    networks: [default]\n  db:\n    image: x\n", "b.yaml": "x-k: &k networks\nservices:\n  a:\n    *k :\n"}, []string{"a.yaml", "b.yaml"}, true},
		{"dns: a list of merge anchors brings a null over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    dns: [1.1.1.1]\n  db:\n    image: x\n", "b.yaml": "x-e: &e\n  dns:\nx-f: &f\n  image: y\nservices:\n  a:\n    <<: [*f, *e]\n"}, []string{"a.yaml", "b.yaml"}, false},
		{"working_dir: a list of merge anchors brings a null over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    working_dir: /w\n  db:\n    image: x\n", "b.yaml": "x-e: &e\n  working_dir:\nx-f: &f\n  image: y\nservices:\n  a:\n    <<: [*f, *e]\n"}, []string{"a.yaml", "b.yaml"}, false},
		{"user: a list of merge anchors brings a null over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    user: root\n  db:\n    image: x\n", "b.yaml": "x-e: &e\n  user:\nx-f: &f\n  image: y\nservices:\n  a:\n    <<: [*f, *e]\n"}, []string{"a.yaml", "b.yaml"}, false},
		{"an inline merge brings a null over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    working_dir: /w\n  db:\n    image: x\n", "b.yaml": "services:\n  a:\n    <<: {working_dir: }\n"}, []string{"a.yaml", "b.yaml"}, false},
		{"an inline merge brings a null networks over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    networks: [default]\n  db:\n    image: x\n", "b.yaml": "services:\n  a:\n    <<: {networks: }\n"}, []string{"a.yaml", "b.yaml"}, true},
		{"ulimits nofile: a null soft through a merge key over {soft, hard}", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    ulimits: {nofile: {soft: 1, hard: 2}}\n  db:\n    image: x\n", "b.yaml": "x-e: &e\n  soft:\n  hard: 3\nservices:\n  a:\n    ulimits:\n      nofile:\n        <<: *e\n"}, []string{"a.yaml", "b.yaml"}, false},
		{"ulimits nofile: a null soft only through a merge key over {soft, hard}", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    ulimits: {nofile: {soft: 1, hard: 2}}\n  db:\n    image: x\n", "b.yaml": "x-e: &e\n  soft:\nservices:\n  a:\n    ulimits:\n      nofile:\n        <<: *e\n"}, []string{"a.yaml", "b.yaml"}, false},
		{"logging.options: a list of merge anchors brings a null over a value", map[string]string{"a.yaml": "services:\n  a:\n    image: x\n    logging: {driver: json-file, options: {a: b}}\n  db:\n    image: x\n", "b.yaml": "x-e: &e\n  options:\nx-f: &f\n  driver: json-file\nservices:\n  a:\n    logging:\n      <<: [*f, *e]\n"}, []string{"a.yaml", "b.yaml"}, false},
	} {
		t.Run(tc.name, func(t *testing.T) {
			dir := t.TempDir()
			for name, body := range tc.files {
				if err := os.WriteFile(filepath.Join(dir, name), []byte(body), 0o644); err != nil {
					t.Fatal(err)
				}
			}
			var paths []string
			for _, name := range tc.order {
				paths = append(paths, filepath.Join(dir, name))
			}
			_, err := LoadFiles(paths, nil)
			if (err != nil) != tc.refused {
				t.Errorf("refused is %v, want %v (err %v)", err != nil, tc.refused, err)
			}
		})
	}
}
