package compose

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// The `mode` of a `secrets` or `configs` entry of a service, and of a `build.secrets` entry, is a whole number or an octal string to docker compose, and these are refused
// wherever the entry stands — in a file on its own, a second `-f`, an `include`, a service an `extends` takes from another file (v5.5.1, `config -q`, every row measured):
// a float (`0.0`, `+0.0`, `1.0`, `!!float -0`, which the merged files would write out again as an integer), `-0`, and a sign after the prefix of an octal or binary number
// (`0o-0`, `0o-1`, `0b-1`: the sign goes before the prefix). A number with the sign in front (`-0o1`, `+0o1`) and a prefix alone (`0o644`, `0x1ff`, `0b11`) are read (#2000).
func TestAModeThatIsNotAWholeNumberIsRefusedWhereverTheEntryStands(t *testing.T) {
	templates := map[string]func(v string) string{
		"service secrets": func(v string) string {
			return "secrets:\n  s:\n    file: ./f.txt\nservices:\n  web:\n    image: wi\n    secrets:\n      - source: s\n        mode: " + v + "\n"
		},
		"service configs": func(v string) string {
			return "configs:\n  c:\n    file: ./f.txt\nservices:\n  web:\n    image: wi\n    configs:\n      - source: c\n        mode: " + v + "\n"
		},
		"build secrets": func(v string) string {
			return "secrets:\n  s:\n    file: ./f.txt\nservices:\n  web:\n    image: wi\n    build:\n      context: .\n      secrets:\n        - source: s\n          mode: " + v + "\n"
		},
	}
	for _, tc := range []struct {
		place, value, where string
		refused             bool
	}{
		{"service secrets", "0o-0", "single", true},
		{"service secrets", "0o-0", "second -f", true},
		{"service secrets", "0o-0", "include", true},
		{"service secrets", "0o-0", "extends", true},
		{"service secrets", "0o-0", "later valid", false},
		{"service secrets", "0o-0", "later float", true},
		{"service secrets", "0.0", "single", true},
		{"service secrets", "0.0", "second -f", true},
		{"service secrets", "0.0", "include", true},
		{"service secrets", "0.0", "extends", true},
		{"service secrets", "0.0", "later valid", false},
		{"service secrets", "0.0", "later float", true},
		{"service secrets", "+0.0", "single", true},
		{"service secrets", "+0.0", "second -f", true},
		{"service secrets", "+0.0", "include", true},
		{"service secrets", "+0.0", "extends", true},
		{"service secrets", "+0.0", "later valid", false},
		{"service secrets", "+0.0", "later float", true},
		{"service secrets", "!!float -0", "single", true},
		{"service secrets", "!!float -0", "second -f", true},
		{"service secrets", "!!float -0", "include", true},
		{"service secrets", "!!float -0", "extends", true},
		{"service secrets", "!!float -0", "later valid", false},
		{"service secrets", "!!float -0", "later float", true},
		{"service secrets", "-0.0", "single", true},
		{"service secrets", "-0.0", "second -f", true},
		{"service secrets", "-0.0", "include", true},
		{"service secrets", "-0.0", "extends", true},
		{"service secrets", "-0.0", "later valid", false},
		{"service secrets", "-0.0", "later float", true},
		{"service secrets", "-0", "single", true},
		{"service secrets", "-0", "second -f", true},
		{"service secrets", "-0", "include", true},
		{"service secrets", "-0", "extends", true},
		{"service secrets", "-0", "later valid", false},
		{"service secrets", "-0", "later float", true},
		{"service secrets", "0o0", "single", false},
		{"service secrets", "0o0", "second -f", false},
		{"service secrets", "0o0", "include", false},
		{"service secrets", "0o0", "extends", false},
		{"service secrets", "0o0", "later valid", false},
		{"service secrets", "0o0", "later float", false},
		{"service secrets", "0o644", "single", false},
		{"service secrets", "0o644", "second -f", false},
		{"service secrets", "0o644", "include", false},
		{"service secrets", "0o644", "extends", false},
		{"service secrets", "0o644", "later valid", false},
		{"service secrets", "0o644", "later float", false},
		{"service secrets", "0.5", "single", true},
		{"service secrets", "0.5", "second -f", true},
		{"service secrets", "0.5", "include", true},
		{"service secrets", "0.5", "extends", true},
		{"service secrets", "0.5", "later valid", false},
		{"service secrets", "0.5", "later float", true},
		{"service secrets", "1.0", "single", true},
		{"service secrets", "1.0", "second -f", true},
		{"service secrets", "1.0", "include", true},
		{"service secrets", "1.0", "extends", true},
		{"service secrets", "1.0", "later valid", false},
		{"service secrets", "1.0", "later float", true},
		{"service secrets", "0x1ff", "single", false},
		{"service secrets", "0x1ff", "second -f", false},
		{"service secrets", "0x1ff", "include", false},
		{"service secrets", "0x1ff", "extends", false},
		{"service secrets", "0x1ff", "later valid", false},
		{"service secrets", "0x1ff", "later float", false},
		{"service secrets", "0b1", "single", false},
		{"service secrets", "0b1", "second -f", false},
		{"service secrets", "0b1", "include", false},
		{"service secrets", "0b1", "extends", false},
		{"service secrets", "0b1", "later valid", false},
		{"service secrets", "0b1", "later float", false},
		{"service secrets", "0o-1", "single", true},
		{"service secrets", "0o-1", "second -f", true},
		{"service secrets", "0o-1", "include", true},
		{"service secrets", "0o-1", "extends", true},
		{"service secrets", "0o-1", "later valid", false},
		{"service secrets", "0o-1", "later float", true},
		{"service secrets", "-1", "single", false},
		{"service secrets", "-1", "second -f", false},
		{"service secrets", "-1", "include", false},
		{"service secrets", "-1", "extends", false},
		{"service secrets", "-1", "later valid", false},
		{"service secrets", "-1", "later float", false},
		{"service secrets", "true", "single", true},
		{"service secrets", "true", "second -f", true},
		{"service secrets", "true", "include", true},
		{"service secrets", "true", "extends", true},
		{"service secrets", "true", "later valid", true},
		{"service secrets", "true", "later float", true},
		{"service secrets", "\"0o-0\"", "single", true},
		{"service secrets", "\"0o-0\"", "second -f", true},
		{"service secrets", "\"0o-0\"", "include", true},
		{"service secrets", "\"0o-0\"", "extends", true},
		{"service secrets", "\"0o-0\"", "later valid", false},
		{"service secrets", "\"0o-0\"", "later float", true},
		{"service secrets", "\"0644\"", "single", false},
		{"service secrets", "\"0644\"", "second -f", false},
		{"service secrets", "\"0644\"", "include", false},
		{"service secrets", "\"0644\"", "extends", false},
		{"service secrets", "\"0644\"", "later valid", false},
		{"service secrets", "\"0644\"", "later float", false},
		{"service secrets", "0644", "single", false},
		{"service secrets", "0644", "second -f", false},
		{"service secrets", "0644", "include", false},
		{"service secrets", "0644", "extends", false},
		{"service secrets", "0644", "later valid", false},
		{"service secrets", "0644", "later float", false},
		{"service secrets", "0b-1", "single", true},
		{"service secrets", "0b-1", "second -f", true},
		{"service secrets", "0b-1", "include", true},
		{"service secrets", "0b-1", "extends", true},
		{"service secrets", "0b-1", "later valid", false},
		{"service secrets", "0b-1", "later float", true},
		{"service secrets", "0b+1", "single", true},
		{"service secrets", "0b+1", "second -f", true},
		{"service secrets", "0b+1", "include", true},
		{"service secrets", "0b+1", "extends", true},
		{"service secrets", "0b+1", "later valid", false},
		{"service secrets", "0b+1", "later float", true},
		{"service secrets", "0o+1", "single", true},
		{"service secrets", "0o+1", "second -f", true},
		{"service secrets", "0o+1", "include", true},
		{"service secrets", "0o+1", "extends", true},
		{"service secrets", "0o+1", "later valid", false},
		{"service secrets", "0o+1", "later float", true},
		{"service secrets", "0O-1", "single", true},
		{"service secrets", "0O-1", "second -f", true},
		{"service secrets", "0O-1", "include", true},
		{"service secrets", "0O-1", "extends", true},
		{"service secrets", "0O-1", "later valid", false},
		{"service secrets", "0O-1", "later float", true},
		{"service secrets", "-0o1", "single", false},
		{"service secrets", "-0o1", "second -f", false},
		{"service secrets", "-0o1", "include", false},
		{"service secrets", "-0o1", "extends", false},
		{"service secrets", "-0o1", "later valid", false},
		{"service secrets", "-0o1", "later float", false},
		{"service secrets", "+0o1", "single", false},
		{"service secrets", "+0o1", "second -f", false},
		{"service secrets", "+0o1", "include", false},
		{"service secrets", "+0o1", "extends", false},
		{"service secrets", "+0o1", "later valid", false},
		{"service secrets", "+0o1", "later float", false},
		{"service secrets", "-0b1", "single", false},
		{"service secrets", "-0b1", "second -f", false},
		{"service secrets", "-0b1", "include", false},
		{"service secrets", "-0b1", "extends", false},
		{"service secrets", "-0b1", "later valid", false},
		{"service secrets", "-0b1", "later float", false},
		{"service secrets", "0.0e0", "single", true},
		{"service secrets", "0.0e0", "second -f", true},
		{"service secrets", "0.0e0", "include", true},
		{"service secrets", "0.0e0", "extends", true},
		{"service secrets", "0.0e0", "later valid", false},
		{"service secrets", "0.0e0", "later float", true},
		{"service secrets", "1e3", "single", true},
		{"service secrets", "1e3", "second -f", true},
		{"service secrets", "1e3", "include", true},
		{"service secrets", "1e3", "extends", true},
		{"service secrets", "1e3", "later valid", false},
		{"service secrets", "1e3", "later float", true},
		{"service secrets", "-0o-1", "single", true},
		{"service secrets", "-0o-1", "second -f", true},
		{"service secrets", "-0o-1", "include", true},
		{"service secrets", "-0o-1", "extends", true},
		{"service secrets", "-0o-1", "later valid", false},
		{"service secrets", "-0o-1", "later float", true},
		{"service secrets", "+0b+1", "single", true},
		{"service secrets", "+0b+1", "second -f", true},
		{"service secrets", "+0b+1", "include", true},
		{"service secrets", "+0b+1", "extends", true},
		{"service secrets", "+0b+1", "later valid", false},
		{"service secrets", "+0b+1", "later float", true},
		{"service configs", "0o-0", "single", true},
		{"service configs", "0o-0", "second -f", true},
		{"service configs", "0o-0", "include", true},
		{"service configs", "0o-0", "extends", true},
		{"service configs", "0o-0", "later valid", false},
		{"service configs", "0o-0", "later float", true},
		{"service configs", "0.0", "single", true},
		{"service configs", "0.0", "second -f", true},
		{"service configs", "0.0", "include", true},
		{"service configs", "0.0", "extends", true},
		{"service configs", "0.0", "later valid", false},
		{"service configs", "0.0", "later float", true},
		{"service configs", "+0.0", "single", true},
		{"service configs", "+0.0", "second -f", true},
		{"service configs", "+0.0", "include", true},
		{"service configs", "+0.0", "extends", true},
		{"service configs", "+0.0", "later valid", false},
		{"service configs", "+0.0", "later float", true},
		{"service configs", "!!float -0", "single", true},
		{"service configs", "!!float -0", "second -f", true},
		{"service configs", "!!float -0", "include", true},
		{"service configs", "!!float -0", "extends", true},
		{"service configs", "!!float -0", "later valid", false},
		{"service configs", "!!float -0", "later float", true},
		{"service configs", "-0.0", "single", true},
		{"service configs", "-0.0", "second -f", true},
		{"service configs", "-0.0", "include", true},
		{"service configs", "-0.0", "extends", true},
		{"service configs", "-0.0", "later valid", false},
		{"service configs", "-0.0", "later float", true},
		{"service configs", "-0", "single", true},
		{"service configs", "-0", "second -f", true},
		{"service configs", "-0", "include", true},
		{"service configs", "-0", "extends", true},
		{"service configs", "-0", "later valid", false},
		{"service configs", "-0", "later float", true},
		{"service configs", "0o0", "single", false},
		{"service configs", "0o0", "second -f", false},
		{"service configs", "0o0", "include", false},
		{"service configs", "0o0", "extends", false},
		{"service configs", "0o0", "later valid", false},
		{"service configs", "0o0", "later float", false},
		{"service configs", "0o644", "single", false},
		{"service configs", "0o644", "second -f", false},
		{"service configs", "0o644", "include", false},
		{"service configs", "0o644", "extends", false},
		{"service configs", "0o644", "later valid", false},
		{"service configs", "0o644", "later float", false},
		{"service configs", "0.5", "single", true},
		{"service configs", "0.5", "second -f", true},
		{"service configs", "0.5", "include", true},
		{"service configs", "0.5", "extends", true},
		{"service configs", "0.5", "later valid", false},
		{"service configs", "0.5", "later float", true},
		{"service configs", "1.0", "single", true},
		{"service configs", "1.0", "second -f", true},
		{"service configs", "1.0", "include", true},
		{"service configs", "1.0", "extends", true},
		{"service configs", "1.0", "later valid", false},
		{"service configs", "1.0", "later float", true},
		{"service configs", "0x1ff", "single", false},
		{"service configs", "0x1ff", "second -f", false},
		{"service configs", "0x1ff", "include", false},
		{"service configs", "0x1ff", "extends", false},
		{"service configs", "0x1ff", "later valid", false},
		{"service configs", "0x1ff", "later float", false},
		{"service configs", "0b1", "single", false},
		{"service configs", "0b1", "second -f", false},
		{"service configs", "0b1", "include", false},
		{"service configs", "0b1", "extends", false},
		{"service configs", "0b1", "later valid", false},
		{"service configs", "0b1", "later float", false},
		{"service configs", "0o-1", "single", true},
		{"service configs", "0o-1", "second -f", true},
		{"service configs", "0o-1", "include", true},
		{"service configs", "0o-1", "extends", true},
		{"service configs", "0o-1", "later valid", false},
		{"service configs", "0o-1", "later float", true},
		{"service configs", "-1", "single", false},
		{"service configs", "-1", "second -f", false},
		{"service configs", "-1", "include", false},
		{"service configs", "-1", "extends", false},
		{"service configs", "-1", "later valid", false},
		{"service configs", "-1", "later float", false},
		{"service configs", "true", "single", true},
		{"service configs", "true", "second -f", true},
		{"service configs", "true", "include", true},
		{"service configs", "true", "extends", true},
		{"service configs", "true", "later valid", true},
		{"service configs", "true", "later float", true},
		{"service configs", "\"0o-0\"", "single", true},
		{"service configs", "\"0o-0\"", "second -f", true},
		{"service configs", "\"0o-0\"", "include", true},
		{"service configs", "\"0o-0\"", "extends", true},
		{"service configs", "\"0o-0\"", "later valid", false},
		{"service configs", "\"0o-0\"", "later float", true},
		{"service configs", "\"0644\"", "single", false},
		{"service configs", "\"0644\"", "second -f", false},
		{"service configs", "\"0644\"", "include", false},
		{"service configs", "\"0644\"", "extends", false},
		{"service configs", "\"0644\"", "later valid", false},
		{"service configs", "\"0644\"", "later float", false},
		{"service configs", "0644", "single", false},
		{"service configs", "0644", "second -f", false},
		{"service configs", "0644", "include", false},
		{"service configs", "0644", "extends", false},
		{"service configs", "0644", "later valid", false},
		{"service configs", "0644", "later float", false},
		{"service configs", "0b-1", "single", true},
		{"service configs", "0b-1", "second -f", true},
		{"service configs", "0b-1", "include", true},
		{"service configs", "0b-1", "extends", true},
		{"service configs", "0b-1", "later valid", false},
		{"service configs", "0b-1", "later float", true},
		{"service configs", "0b+1", "single", true},
		{"service configs", "0b+1", "second -f", true},
		{"service configs", "0b+1", "include", true},
		{"service configs", "0b+1", "extends", true},
		{"service configs", "0b+1", "later valid", false},
		{"service configs", "0b+1", "later float", true},
		{"service configs", "0o+1", "single", true},
		{"service configs", "0o+1", "second -f", true},
		{"service configs", "0o+1", "include", true},
		{"service configs", "0o+1", "extends", true},
		{"service configs", "0o+1", "later valid", false},
		{"service configs", "0o+1", "later float", true},
		{"service configs", "0O-1", "single", true},
		{"service configs", "0O-1", "second -f", true},
		{"service configs", "0O-1", "include", true},
		{"service configs", "0O-1", "extends", true},
		{"service configs", "0O-1", "later valid", false},
		{"service configs", "0O-1", "later float", true},
		{"service configs", "-0o1", "single", false},
		{"service configs", "-0o1", "second -f", false},
		{"service configs", "-0o1", "include", false},
		{"service configs", "-0o1", "extends", false},
		{"service configs", "-0o1", "later valid", false},
		{"service configs", "-0o1", "later float", false},
		{"service configs", "+0o1", "single", false},
		{"service configs", "+0o1", "second -f", false},
		{"service configs", "+0o1", "include", false},
		{"service configs", "+0o1", "extends", false},
		{"service configs", "+0o1", "later valid", false},
		{"service configs", "+0o1", "later float", false},
		{"service configs", "-0b1", "single", false},
		{"service configs", "-0b1", "second -f", false},
		{"service configs", "-0b1", "include", false},
		{"service configs", "-0b1", "extends", false},
		{"service configs", "-0b1", "later valid", false},
		{"service configs", "-0b1", "later float", false},
		{"service configs", "0.0e0", "single", true},
		{"service configs", "0.0e0", "second -f", true},
		{"service configs", "0.0e0", "include", true},
		{"service configs", "0.0e0", "extends", true},
		{"service configs", "0.0e0", "later valid", false},
		{"service configs", "0.0e0", "later float", true},
		{"service configs", "1e3", "single", true},
		{"service configs", "1e3", "second -f", true},
		{"service configs", "1e3", "include", true},
		{"service configs", "1e3", "extends", true},
		{"service configs", "1e3", "later valid", false},
		{"service configs", "1e3", "later float", true},
		{"service configs", "-0o-1", "single", true},
		{"service configs", "-0o-1", "second -f", true},
		{"service configs", "-0o-1", "include", true},
		{"service configs", "-0o-1", "extends", true},
		{"service configs", "-0o-1", "later valid", false},
		{"service configs", "-0o-1", "later float", true},
		{"service configs", "+0b+1", "single", true},
		{"service configs", "+0b+1", "second -f", true},
		{"service configs", "+0b+1", "include", true},
		{"service configs", "+0b+1", "extends", true},
		{"service configs", "+0b+1", "later valid", false},
		{"service configs", "+0b+1", "later float", true},
		{"build secrets", "0o-0", "single", true},
		{"build secrets", "0o-0", "second -f", true},
		{"build secrets", "0o-0", "include", true},
		{"build secrets", "0o-0", "extends", true},
		{"build secrets", "0o-0", "later valid", true},
		{"build secrets", "0o-0", "later float", true},
		{"build secrets", "0.0", "single", true},
		{"build secrets", "0.0", "second -f", true},
		{"build secrets", "0.0", "include", true},
		{"build secrets", "0.0", "extends", true},
		{"build secrets", "0.0", "later valid", true},
		{"build secrets", "0.0", "later float", true},
		{"build secrets", "+0.0", "single", true},
		{"build secrets", "+0.0", "second -f", true},
		{"build secrets", "+0.0", "include", true},
		{"build secrets", "+0.0", "extends", true},
		{"build secrets", "+0.0", "later valid", true},
		{"build secrets", "+0.0", "later float", true},
		{"build secrets", "!!float -0", "single", true},
		{"build secrets", "!!float -0", "second -f", true},
		{"build secrets", "!!float -0", "include", true},
		{"build secrets", "!!float -0", "extends", true},
		{"build secrets", "!!float -0", "later valid", true},
		{"build secrets", "!!float -0", "later float", true},
		{"build secrets", "-0.0", "single", true},
		{"build secrets", "-0.0", "second -f", true},
		{"build secrets", "-0.0", "include", true},
		{"build secrets", "-0.0", "extends", true},
		{"build secrets", "-0.0", "later valid", true},
		{"build secrets", "-0.0", "later float", true},
		{"build secrets", "-0", "single", true},
		{"build secrets", "-0", "second -f", true},
		{"build secrets", "-0", "include", true},
		{"build secrets", "-0", "extends", true},
		{"build secrets", "-0", "later valid", true},
		{"build secrets", "-0", "later float", true},
		{"build secrets", "0o0", "single", false},
		{"build secrets", "0o0", "second -f", false},
		{"build secrets", "0o0", "include", false},
		{"build secrets", "0o0", "extends", false},
		{"build secrets", "0o0", "later valid", false},
		{"build secrets", "0o0", "later float", false},
		{"build secrets", "0o644", "single", false},
		{"build secrets", "0o644", "second -f", false},
		{"build secrets", "0o644", "include", false},
		{"build secrets", "0o644", "extends", false},
		{"build secrets", "0o644", "later valid", false},
		{"build secrets", "0o644", "later float", false},
		{"build secrets", "0.5", "single", true},
		{"build secrets", "0.5", "second -f", true},
		{"build secrets", "0.5", "include", true},
		{"build secrets", "0.5", "extends", true},
		{"build secrets", "0.5", "later valid", true},
		{"build secrets", "0.5", "later float", true},
		{"build secrets", "1.0", "single", true},
		{"build secrets", "1.0", "second -f", true},
		{"build secrets", "1.0", "include", true},
		{"build secrets", "1.0", "extends", true},
		{"build secrets", "1.0", "later valid", true},
		{"build secrets", "1.0", "later float", true},
		{"build secrets", "0x1ff", "single", false},
		{"build secrets", "0x1ff", "second -f", false},
		{"build secrets", "0x1ff", "include", false},
		{"build secrets", "0x1ff", "extends", false},
		{"build secrets", "0x1ff", "later valid", false},
		{"build secrets", "0x1ff", "later float", false},
		{"build secrets", "0b1", "single", false},
		{"build secrets", "0b1", "second -f", false},
		{"build secrets", "0b1", "include", false},
		{"build secrets", "0b1", "extends", false},
		{"build secrets", "0b1", "later valid", false},
		{"build secrets", "0b1", "later float", false},
		{"build secrets", "0o-1", "single", true},
		{"build secrets", "0o-1", "second -f", true},
		{"build secrets", "0o-1", "include", true},
		{"build secrets", "0o-1", "extends", true},
		{"build secrets", "0o-1", "later valid", true},
		{"build secrets", "0o-1", "later float", true},
		{"build secrets", "-1", "single", false},
		{"build secrets", "-1", "second -f", false},
		{"build secrets", "-1", "include", false},
		{"build secrets", "-1", "extends", false},
		{"build secrets", "-1", "later valid", false},
		{"build secrets", "-1", "later float", false},
		{"build secrets", "true", "single", true},
		{"build secrets", "true", "second -f", true},
		{"build secrets", "true", "include", true},
		{"build secrets", "true", "extends", true},
		{"build secrets", "true", "later valid", true},
		{"build secrets", "true", "later float", true},
		{"build secrets", "\"0o-0\"", "single", true},
		{"build secrets", "\"0o-0\"", "second -f", true},
		{"build secrets", "\"0o-0\"", "include", true},
		{"build secrets", "\"0o-0\"", "extends", true},
		{"build secrets", "\"0o-0\"", "later valid", true},
		{"build secrets", "\"0o-0\"", "later float", true},
		{"build secrets", "\"0644\"", "single", false},
		{"build secrets", "\"0644\"", "second -f", false},
		{"build secrets", "\"0644\"", "include", false},
		{"build secrets", "\"0644\"", "extends", false},
		{"build secrets", "\"0644\"", "later valid", false},
		{"build secrets", "\"0644\"", "later float", false},
		{"build secrets", "0644", "single", false},
		{"build secrets", "0644", "second -f", false},
		{"build secrets", "0644", "include", false},
		{"build secrets", "0644", "extends", false},
		{"build secrets", "0644", "later valid", false},
		{"build secrets", "0644", "later float", false},
		{"build secrets", "0b-1", "single", true},
		{"build secrets", "0b-1", "second -f", true},
		{"build secrets", "0b-1", "include", true},
		{"build secrets", "0b-1", "extends", true},
		{"build secrets", "0b-1", "later valid", true},
		{"build secrets", "0b-1", "later float", true},
		{"build secrets", "0b+1", "single", true},
		{"build secrets", "0b+1", "second -f", true},
		{"build secrets", "0b+1", "include", true},
		{"build secrets", "0b+1", "extends", true},
		{"build secrets", "0b+1", "later valid", true},
		{"build secrets", "0b+1", "later float", true},
		{"build secrets", "0o+1", "single", true},
		{"build secrets", "0o+1", "second -f", true},
		{"build secrets", "0o+1", "include", true},
		{"build secrets", "0o+1", "extends", true},
		{"build secrets", "0o+1", "later valid", true},
		{"build secrets", "0o+1", "later float", true},
		{"build secrets", "0O-1", "single", true},
		{"build secrets", "0O-1", "second -f", true},
		{"build secrets", "0O-1", "include", true},
		{"build secrets", "0O-1", "extends", true},
		{"build secrets", "0O-1", "later valid", true},
		{"build secrets", "0O-1", "later float", true},
		{"build secrets", "-0o1", "single", false},
		{"build secrets", "-0o1", "second -f", false},
		{"build secrets", "-0o1", "include", false},
		{"build secrets", "-0o1", "extends", false},
		{"build secrets", "-0o1", "later valid", false},
		{"build secrets", "-0o1", "later float", false},
		{"build secrets", "+0o1", "single", false},
		{"build secrets", "+0o1", "second -f", false},
		{"build secrets", "+0o1", "include", false},
		{"build secrets", "+0o1", "extends", false},
		{"build secrets", "+0o1", "later valid", false},
		{"build secrets", "+0o1", "later float", false},
		{"build secrets", "-0b1", "single", false},
		{"build secrets", "-0b1", "second -f", false},
		{"build secrets", "-0b1", "include", false},
		{"build secrets", "-0b1", "extends", false},
		{"build secrets", "-0b1", "later valid", false},
		{"build secrets", "-0b1", "later float", false},
		{"build secrets", "0.0e0", "single", true},
		{"build secrets", "0.0e0", "second -f", true},
		{"build secrets", "0.0e0", "include", true},
		{"build secrets", "0.0e0", "extends", true},
		{"build secrets", "0.0e0", "later valid", true},
		{"build secrets", "0.0e0", "later float", true},
		{"build secrets", "1e3", "single", true},
		{"build secrets", "1e3", "second -f", true},
		{"build secrets", "1e3", "include", true},
		{"build secrets", "1e3", "extends", true},
		{"build secrets", "1e3", "later valid", true},
		{"build secrets", "1e3", "later float", true},
		{"build secrets", "-0o-1", "single", true},
		{"build secrets", "-0o-1", "second -f", true},
		{"build secrets", "-0o-1", "include", true},
		{"build secrets", "-0o-1", "extends", true},
		{"build secrets", "-0o-1", "later valid", true},
		{"build secrets", "-0o-1", "later float", true},
		{"build secrets", "+0b+1", "single", true},
		{"build secrets", "+0b+1", "second -f", true},
		{"build secrets", "+0b+1", "include", true},
		{"build secrets", "+0b+1", "extends", true},
		{"build secrets", "+0b+1", "later valid", true},
		{"build secrets", "+0b+1", "later float", true},
	} {
		t.Run(tc.place+"/"+tc.value+"/"+tc.where, func(t *testing.T) {
			dir := t.TempDir()
			write := func(name, text string) {
				if err := os.WriteFile(filepath.Join(dir, name), []byte(text), 0o644); err != nil {
					t.Fatal(err)
				}
			}
			write("f.txt", "x")
			text := templates[tc.place](tc.value)
			var paths []string
			switch tc.where {
			case "single":
				write("a.yaml", text)
				paths = []string{"a.yaml"}
			case "second -f":
				write("a.yaml", "services:\n  web:\n    image: wi\n")
				write("b.yaml", text)
				paths = []string{"a.yaml", "b.yaml"}
			case "include":
				write("inc.yaml", text)
				write("a.yaml", "include: [inc.yaml]\n")
				paths = []string{"a.yaml"}
			case "later valid":
				write("a.yaml", text)
				write("b.yaml", strings.Replace(strings.Replace(templates[tc.place]("0444"), "secrets:\n  s:\n    file: ./f.txt\n", "", 1), "configs:\n  c:\n    file: ./f.txt\n", "", 1))
				paths = []string{"a.yaml", "b.yaml"}
			case "later float":
				write("a.yaml", templates[tc.place]("0644"))
				write("b.yaml", strings.Replace(strings.Replace(text, "secrets:\n  s:\n    file: ./f.txt\n", "", 1), "configs:\n  c:\n    file: ./f.txt\n", "", 1))
				paths = []string{"a.yaml", "b.yaml"}
			default:
				write("base.yaml", strings.Replace(text, "web:", "y:", 1))
				write("a.yaml", "secrets:\n  s:\n    file: ./f.txt\nconfigs:\n  c:\n    file: ./f.txt\nservices:\n  web:\n    extends: {file: base.yaml, service: y}\n")
				paths = []string{"a.yaml"}
			}
			for i := range paths {
				paths[i] = filepath.Join(dir, paths[i])
			}
			_, err := LoadFiles(paths, nil)
			if (err != nil) != tc.refused {
				t.Errorf("refused = %v (%v), want %v", err != nil, err, tc.refused)
			}
			// A mode read as a float or with a sign after its prefix, once the files are merged, is shown as it was written, so that the file can be found by it.
			if err != nil && tc.where != "single" && (strings.Contains(tc.value, "0.0") || strings.HasPrefix(tc.value, "0o-") || strings.HasPrefix(tc.value, "0b-") || tc.value == "1.0") &&
				!strings.Contains(err.Error(), "mode "+strings.TrimPrefix(tc.value, "!!float ")) {
				t.Errorf("the refusal does not show the mode as it was written (%s): %v", tc.value, err)
			}
		})
	}
}

// The node a `mode` is written in may be shared: an anchor that something else reads as it was written (`x-m: &m {mode: 1.0}`, also the `environment` and `labels` of the service, or an
// entry that carries its own anchor). The mark that makes the merged files refuse a float stays on the copy the secret reads, and the other readers see `1.0` as docker compose gives it
// (`mode: "1"`, measured, v5.5.1; main and docker agree, and a version that wrote the mark into the shared node showed it there).
func TestTheMarkOfAModeIsNotWrittenIntoAnAnchorSomethingElseReads(t *testing.T) {
	for _, tc := range []struct {
		name, text string
	}{
		{"a mapping merged into the entry, used as the environment", "x-m: &m {mode: 1.0}\nservices:\n  web:\n    image: wi\n    environment: *m\n    secrets:\n      - source: s\n        <<: *m\n"},
		{"a mapping merged into the entry, used as the labels", "x-m: &m {mode: 1.0}\nservices:\n  web:\n    image: wi\n    labels: *m\n    secrets:\n      - source: s\n        <<: *m\n"},
		{"an entry that has its own anchor, used as the environment", "x-m: &m {mode: 1.0}\nservices:\n  web:\n    image: wi\n    environment: *m\n    secrets:\n      - &e {source: s, mode: 1.0}\n"},
		{"a prefix with a sign after it", "x-m: &m {mode: 0o-1}\nservices:\n  web:\n    image: wi\n    environment: *m\n    secrets:\n      - source: s\n        <<: *m\n"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			dir := t.TempDir()
			for name, text := range map[string]string{
				"f.txt":  "x",
				"a.yaml": "secrets:\n  s:\n    file: ./f.txt\n" + tc.text,
				"b.yaml": "services:\n  web:\n    secrets:\n      - source: s\n        mode: 0444\n",
			} {
				if err := os.WriteFile(filepath.Join(dir, name), []byte(text), 0o644); err != nil {
					t.Fatal(err)
				}
			}
			p, err := LoadFiles([]string{filepath.Join(dir, "a.yaml"), filepath.Join(dir, "b.yaml")}, nil)
			if err != nil {
				t.Fatalf("load: %v", err)
			}
			svc := p.Services["web"]
			for _, entry := range append(append([]string(nil), svc.Environment...), svc.Labels...) {
				if strings.Contains(entry, "\ue002") {
					t.Errorf("the mark is in what the service reads as its environment or labels: %q", entry)
				}
			}
		})
	}
}
