package compose

import (
	"flag"
	"fmt"
	"go/format"
	"os"
	"reflect"
	"sort"
	"strings"
	"testing"
)

var updateSpecKeys = flag.Bool("update-spec-keys", false, "rewrite speckeys_table.go from testdata/compose-spec.json")

// The table of keys docker compose takes is data copied out of the compose
// specification's schema, and this is what keeps the copy honest: the same
// extraction, run on the schema file, must give the same table. To take a
// newer schema, replace testdata/compose-spec.json and its .version note and
// run `go test ./internal/compose -run TestSpecKeysMatchTheSchema -update-spec-keys`.
func TestSpecKeysMatchTheSchema(t *testing.T) {
	data, err := os.ReadFile("testdata/compose-spec.json")
	if err != nil {
		t.Fatal(err)
	}
	version, err := os.ReadFile("testdata/compose-spec.version")
	if err != nil {
		t.Fatal(err)
	}
	want, err := specKeysFromSchema(data)
	if err != nil {
		t.Fatal(err)
	}
	if *updateSpecKeys {
		if err := os.WriteFile("speckeys_table.go", renderSpecKeys(strings.TrimSpace(string(version)), want), 0o644); err != nil {
			t.Fatal(err)
		}
		t.Log("speckeys_table.go rewritten")
		return
	}
	if !reflect.DeepEqual(specKeys, want) {
		t.Errorf("specKeys differs from testdata/compose-spec.json — run with -update-spec-keys")
	}
	if !strings.Contains(specKeysSource, strings.TrimSpace(string(version))) {
		t.Errorf("speckeys_table.go does not name the schema copy it came from (%s)", strings.TrimSpace(string(version)))
	}
}

// Every key opossum reads must be one docker compose takes at that place —
// otherwise the refusal of unknown keys would refuse opossum's own fields.
func TestOpossumsKeysAreInTheSpec(t *testing.T) {
	for k := range serviceKnownKeys {
		if !specKnows("services.*", k) && !opossumOwnServiceKeys[k] {
			t.Errorf("service key %q is read by opossum but not in the compose spec", k)
		}
	}
	for prefix, keys := range nestedKnownKeys {
		for _, k := range keys {
			if !specKnows("services.*."+prefix, k) {
				t.Errorf("%s.%s is read by opossum but not in the compose spec", prefix, k)
			}
		}
	}
	for field, keys := range itemKnownKeys {
		path := "services.*." + field + "[]"
		if field == "depends_on" {
			path = "services.*.depends_on.*"
		}
		if strings.Contains(field, ".") {
			path = "services.*." + strings.Replace(field, ".", "[].", 1)
		}
		for _, k := range keys {
			if !specKnows(path, k) {
				t.Errorf("%s item key %q is read by opossum but not in the compose spec (%s)", field, k, path)
			}
		}
	}
	for k := range watchRuleKeys {
		if !specKnows("services.*.develop.watch[]", k) {
			t.Errorf("watch rule key %q is read by opossum but not in the compose spec", k)
		}
	}
	for k := range networkDeclFields {
		if !specKnows("networks.*", k) {
			t.Errorf("network declaration key %q is read by opossum but not in the compose spec", k)
		}
	}
	for k := range volumeDeclFields {
		if !specKnows("volumes.*", k) {
			t.Errorf("volume declaration key %q is read by opossum but not in the compose spec", k)
		}
	}
	for k := range secretDeclFields {
		if !specKnows("secrets.*", k) {
			t.Errorf("secret declaration key %q is read by opossum but not in the compose spec", k)
		}
	}
	for k := range configDeclFields {
		if !specKnows("configs.*", k) {
			t.Errorf("config declaration key %q is read by opossum but not in the compose spec", k)
		}
	}
}

func renderSpecKeys(version string, keys map[string][]string) []byte {
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by `go test ./internal/compose -run TestSpecKeysMatchTheSchema -update-spec-keys`; DO NOT EDIT.\n")
	fmt.Fprintf(&b, "// Source: %s\n\npackage compose\n\n", version)
	fmt.Fprintf(&b, "// specKeysSource names the schema copy specKeys was taken from.\nconst specKeysSource = %q\n\n", version)
	fmt.Fprintf(&b, "// specKeys lists, for each place in a compose file, the keys docker compose\n// takes there (see specKnows).\nvar specKeys = map[string][]string{\n")
	paths := make([]string, 0, len(keys))
	for p := range keys {
		paths = append(paths, p)
	}
	sort.Strings(paths)
	for _, p := range paths {
		fmt.Fprintf(&b, "\t%q: {", p)
		for i, k := range keys[p] {
			if i > 0 {
				b.WriteString(", ")
			}
			fmt.Fprintf(&b, "%q", k)
		}
		b.WriteString("},\n")
	}
	b.WriteString("}\n")
	src, err := format.Source([]byte(b.String()))
	if err != nil {
		panic(err)
	}
	return src
}

// specKnows checks only the places the table names, so a place it does not
// name refuses nothing — the refusal never reaches past what was measured
// against docker compose. And an `x-` key is taken anywhere.
func TestSpecKnowsChecksOnlyThePlacesItNames(t *testing.T) {
	if !specKnows("services.*.somewhere.new", "anything") {
		t.Errorf("a place the table does not name must refuse nothing")
	}
	if !specKnows("services.*", "x-anything") || !specKnows("", "x-anything") {
		t.Errorf("an x- key is taken anywhere")
	}
	if specKnows("services.*", "enviroment") {
		t.Errorf("a key the schema does not have at a named place is not taken")
	}
}
