// Code generated by `go test ./internal/compose -run TestSpecKeysMatchTheSchema -update-spec-keys`; DO NOT EDIT.
// Source: compose-spec/compose-spec@fee041b381ff (schema/compose-spec.json, 2026-09-01)

package compose

// specKeysSource names the schema copy specKeys was taken from.
const specKeysSource = "compose-spec/compose-spec@fee041b381ff (schema/compose-spec.json, 2026-09-01)"

// specKeys lists, for each place in a compose file, the keys docker compose
// takes there (see specKnows).
var specKeys = map[string][]string{
	"":                                   {"configs", "include", "models", "name", "networks", "secrets", "services", "version", "volumes"},
	"configs.*":                          {"content", "environment", "external", "file", "labels", "name", "template_driver"},
	"include[]":                          {"env_file", "path", "project_directory"},
	"networks.*":                         {"attachable", "driver", "driver_opts", "enable_ipv4", "enable_ipv6", "external", "internal", "ipam", "labels", "name"},
	"networks.*.ipam":                    {"config", "driver", "options"},
	"networks.*.ipam.config[]":           {"aux_addresses", "gateway", "ip_range", "subnet"},
	"secrets.*":                          {"driver", "driver_opts", "environment", "external", "file", "labels", "name", "template_driver"},
	"services.*":                         {"annotations", "attach", "blkio_config", "build", "cap_add", "cap_drop", "cgroup", "cgroup_parent", "command", "configs", "container_name", "cpu_count", "cpu_percent", "cpu_period", "cpu_quota", "cpu_rt_period", "cpu_rt_runtime", "cpu_shares", "cpus", "cpuset", "credential_spec", "depends_on", "deploy", "develop", "device_cgroup_rules", "devices", "dns", "dns_opt", "dns_search", "domainname", "entrypoint", "env_file", "environment", "expose", "extends", "external_links", "extra_hosts", "gpus", "group_add", "healthcheck", "hostname", "image", "init", "ipc", "isolation", "label_file", "labels", "links", "logging", "mac_address", "mem_limit", "mem_reservation", "mem_swappiness", "memswap_limit", "models", "network_mode", "networks", "oom_kill_disable", "oom_score_adj", "pid", "pids_limit", "platform", "ports", "post_start", "pre_start", "pre_stop", "privileged", "profiles", "provider", "pull_policy", "pull_refresh_after", "read_only", "restart", "runtime", "scale", "secrets", "security_opt", "shm_size", "stdin_open", "stop_grace_period", "stop_signal", "storage_opt", "sysctls", "tmpfs", "tty", "ulimits", "use_api_socket", "user", "userns_mode", "uts", "volumes", "volumes_from", "working_dir"},
	"services.*.blkio_config":            {"device_read_bps", "device_read_iops", "device_write_bps", "device_write_iops", "weight", "weight_device"},
	"services.*.build":                   {"additional_contexts", "args", "cache_from", "cache_to", "context", "dockerfile", "dockerfile_inline", "entitlements", "extra_hosts", "isolation", "labels", "network", "no_cache", "no_cache_filter", "platforms", "privileged", "provenance", "pull", "sbom", "secrets", "shm_size", "ssh", "tags", "target", "ulimits"},
	"services.*.configs[]":               {"gid", "mode", "source", "target", "uid"},
	"services.*.depends_on.*":            {"condition", "required", "restart"},
	"services.*.deploy":                  {"endpoint_mode", "labels", "mode", "placement", "replicas", "resources", "restart_policy", "rollback_config", "update_config"},
	"services.*.deploy.resources":        {"limits", "reservations"},
	"services.*.deploy.resources.limits": {"cpus", "memory", "pids"},
	"services.*.deploy.resources.reservations": {"cpus", "devices", "generic_resources", "memory"},
	"services.*.develop":                       {"watch"},
	"services.*.develop.watch[]":               {"action", "exec", "ignore", "include", "initial_sync", "path", "target"},
	"services.*.env_file[]":                    {"format", "path", "required"},
	"services.*.extends":                       {"file", "service"},
	"services.*.healthcheck":                   {"disable", "interval", "retries", "start_interval", "start_period", "test", "timeout"},
	"services.*.logging":                       {"driver", "options"},
	"services.*.networks.*":                    {"aliases", "driver_opts", "gw_priority", "interface_name", "ipv4_address", "ipv6_address", "link_local_ips", "mac_address", "priority"},
	"services.*.ports[]":                       {"app_protocol", "host_ip", "mode", "name", "protocol", "published", "target"},
	"services.*.secrets[]":                     {"gid", "mode", "source", "target", "uid"},
	"services.*.volumes[]":                     {"bind", "consistency", "image", "read_only", "source", "target", "tmpfs", "type", "volume"},
	"services.*.volumes[].bind":                {"create_host_path", "propagation", "recursive", "selinux"},
	"services.*.volumes[].tmpfs":               {"mode", "size"},
	"services.*.volumes[].volume":              {"labels", "nocopy", "subpath"},
	"volumes.*":                                {"driver", "driver_opts", "external", "labels", "name"},
}
