package main

import (
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"
)

// The commands opossum's output suggests are held to what they say: each is
// taken as printed, handed to a shell, and run — and the run it starts has to
// read the project the run that printed it read, and reach what it made.
// Everything here goes through shellReads (composefile_test.go).

// Where opossum wrote the overlay and this run found more, the way to have it
// rewritten is said as a command — and the rewrite looks only at the services
// the run enables, so it has to be the run that found these. A profile may now
// come from an `--env-file`, which a shell does not carry over as it does
// COMPOSE_PROFILES: the command has to. Each row follows the command as printed
// and asks whether that run still sees what this one reported.
func TestTheRewriteTheAdviceNamesSeesWhatThisRunSaw(t *testing.T) {
	const compose = "services:\n  base:\n    image: alpine:3\n" +
		"  extra:\n    image: alpine:3\n    profiles: [extras]\n    volumes: [\"shared:/data\"]\n" +
		"  worker:\n    image: alpine:3\n    profiles: [extras]\n    volumes: [\"shared:/data\"]\n" +
		"volumes:\n  shared: {}\n"
	for _, tc := range []struct {
		name  string
		args  []string
		shell *string
		// files are written beside the compose file: name and body.
		files map[string]string
		// named are the services the run names, after the subcommand's flags.
		named []string
		// wantCommand is a part of the command as printed.
		wantCommand string
	}{
		{name: "the profile from an --env-file", args: []string{"--env-file", "cf.env"},
			files: map[string]string{"cf.env": "COMPOSE_PROFILES=extras\n"}, wantCommand: " --env-file cf.env"},
		{name: "from an --env-file a shell would take apart", args: []string{"--env-file", "my env/cf.env"},
			files: map[string]string{"my env/cf.env": "COMPOSE_PROFILES=extras\n"}, wantCommand: " --env-file 'my env/cf.env'"},
		// --env-file repeats and the later file wins: all of them, in order. Here
		// only the last one says anything.
		{name: "from the later of two --env-files", args: []string{"--env-file", "quiet.env", "--env-file", "cf.env"},
			files:       map[string]string{"quiet.env": "COMPOSE_PROFILES=\n", "cf.env": "COMPOSE_PROFILES=extras\n"},
			wantCommand: " --env-file quiet.env --env-file cf.env"},
		{name: "from the flag", args: []string{"--profile", "extras"}, wantCommand: " --profile extras"},
		// The project's name and the DNS domain are in the names of what the
		// run made: a rewrite without them would be another project's.
		{name: "with the project's name", args: []string{"-p", "my proj", "--profile", "extras"}, wantCommand: " -p 'my proj' --profile extras"},
		{name: "with the DNS domain", args: []string{"--dns-domain", "foo", "--profile", "extras"}, wantCommand: " --profile extras --dns-domain foo"},
		// The services the run named are named again — and here they are all
		// that enables extra and worker, so a rewrite without them sees nothing.
		{name: "with the services it named", named: []string{"extra", "worker"},
			wantCommand: " extra worker"},
		// The shell's and the `.env`'s need no repeating: the rewrite runs with both.
		{name: "from the shell", shell: ptr("extras")},
		{name: "from the .env", files: map[string]string{".env": "COMPOSE_PROFILES=extras\n"}},
	} {
		t.Run(tc.name, func(t *testing.T) {
			fakeShim(t)
			t.Setenv("XDG_STATE_HOME", t.TempDir())
			root := t.TempDir()
			dir := filepath.Join(root, "proj")
			if err := os.MkdirAll(dir, 0o755); err != nil {
				t.Fatal(err)
			}
			write(t, filepath.Join(dir, "compose.yaml"), compose)
			for name, body := range tc.files {
				if err := os.MkdirAll(filepath.Dir(filepath.Join(dir, name)), 0o755); err != nil {
					t.Fatal(err)
				}
				write(t, filepath.Join(dir, name), body)
			}
			t.Chdir(dir)
			for _, name := range []string{"COMPOSE_PROJECT_NAME", "COMPOSE_PATH_SEPARATOR", "COMPOSE_FILE"} {
				setOrUnset(t, name, nil)
			}
			setOrUnset(t, "COMPOSE_PROFILES", tc.shell)
			// An overlay opossum wrote, by a run that found less than this one will.
			write(t, filepath.Join(dir, "compose.opossum.yaml"), "# Generated by `opossum up --from-docker-compose`.\nservices: {}\n")

			const saw = `service "extra" shares named volume`
			first := append(append([]string{}, tc.args...), "up", "--from-docker-compose", "--no-build", "--dry-run")
			_, stderr, err := runSplit(t, append(first, tc.named...)...)
			if err != nil {
				t.Fatalf("up --from-docker-compose: %v\n%s", err, stderr)
			}
			_, rest, ok := strings.Cut(stderr, "was generated by opossum, so `")
			if !ok || !strings.Contains(stderr, saw) {
				t.Fatalf("this fixture should have the run find more than the overlay holds and say how to rewrite it; got:\n%s", stderr)
			}
			command, _, _ := strings.Cut(rest, "` rewrites it")
			if !strings.HasSuffix(command, "opossum up --from-docker-compose"+tc.wantCommand) {
				t.Errorf("the command should end %q, got: %s", "opossum up --from-docker-compose"+tc.wantCommand, command)
			}
			_, argv := shellReads(t, root, command)
			if _, err := os.Stat(filepath.Join(dir, "compose.opossum.yaml")); err == nil {
				t.Fatalf("the command should have removed the overlay: %s", command)
			}
			// The flags this adds go before the services the command names.
			at := len(argv) - len(tc.named)
			followed := append(append(append([]string{}, argv[:at]...), "--no-build", "--dry-run"), argv[at:]...)
			_, stderr2, err := runSplit(t, followed...)
			if err != nil {
				t.Fatalf("following the advice (%s) failed: %v\n%s", command, err, stderr2)
			}
			if !strings.Contains(stderr2, saw) {
				t.Errorf("the rewrite (%s) does not see what this run reported; got:\n%s", command, stderr2)
			}
			// …and it is the same project: the name it would make things under.
			before, err := run(t, append(append([]string{}, tc.args...), "config")...)
			if err != nil {
				t.Fatal(err)
			}
			// The command's root flags come after `up --from-docker-compose`.
			flags := argv[2:at]
			after, err := run(t, append(append([]string{}, flags...), "config")...)
			if err != nil {
				t.Fatalf("config with the command's flags (%v): %v", flags, err)
			}
			if configName(before) != configName(after) {
				t.Errorf("the rewrite reads project %q where this run read %q", configName(after), configName(before))
			}
		})
	}
}

// A `--profile` that names nothing is still the flag — it keeps
// COMPOSE_PROFILES from being read — so a command that repeats a run's flags
// repeats that one too.
func TestProfileFlagsSpellsAnEmptyProfile(t *testing.T) {
	if got, want := profileFlags([]string{"", "a b", " c "}), " --profile '' --profile 'a b' --profile c"; got != want {
		t.Errorf("profileFlags = %q, want %q", got, want)
	}
}

// A service name opossum takes may be one a shell would take apart (docker
// compose refuses such names; opossum does not), so a command that names
// services spells them as words.
func TestServiceArgsSpellsNamesAsWords(t *testing.T) {
	if got, want := serviceArgs([]string{"web", "we b", "wo*rk"}), " web 'we b' 'wo*rk'"; got != want {
		t.Errorf("serviceArgs = %q, want %q", got, want)
	}
}

// When a service depends on one behind a profile that is not active, the
// refusal says how to enable it — and what it says has to hold in the run that
// got it. None of the places profiles come from add up: `--profile` replaces
// COMPOSE_PROFILES, and COMPOSE_PROFILES in the shell replaces the `.env`'s.
// Naming the service is no way out of any of these: every row has `web` turned on by a profile, so the run reads it without a name (docker compose v5.5.1, measured, #1973: `up db web`
// is refused as `up` is; for a `web` that only its name enables, `up web db` is the way out, TestNamingTheGatedDependencyIsUpsWayOutOnlyForAServiceANameEnables).
// Each row is a run that is refused — its
// profiles from one of those places — then what following the refusal, in the
// place the run reads, comes to.
func TestTheGatedDependencysRefusalHoldsInTheRunThatGotIt(t *testing.T) {
	const compose = "services:\n  web:\n    image: alpine:3\n    profiles: [a]\n    depends_on: [db]\n  db:\n    image: alpine:3\n    profiles: [b]\n"
	type given struct {
		args  []string
		shell *string
		// dotenv and envFile are the working directory's `.env` and an
		// `--env-file` there, "" for none (envFile is given to the run as
		// well). composeFile, when set, is COMPOSE_FILE in the shell: the file
		// is then sub/x.yaml, and subenv is sub/.env.
		dotenv, envFile     string
		composeFile, subenv string
	}
	for _, tc := range []struct {
		name string
		// exit is the subcommand the refusal comes out of, with what it needs.
		exit []string
		// canName is whether that exit can be followed by naming the service.
		canName bool
		first   given
		then    given
		// wantServices is what `config --services` says of the followed run;
		// "" is refused still, with the same refusal, and "-" is no service.
		wantServices string
	}{
		{"up, given --profile: another --profile", []string{"up", "--dry-run", "--no-build"}, false,
			given{args: []string{"--profile", "a"}}, given{args: []string{"--profile", "a", "--profile", "b"}}, "db,web"},
		// COMPOSE_PROFILES beside --profile changes nothing (docker compose
		// does not read it either): the refusal says so, and this row is that.
		{"up, given --profile: COMPOSE_PROFILES changes nothing", []string{"up", "--dry-run", "--no-build"}, false,
			given{args: []string{"--profile", "a"}}, given{args: []string{"--profile", "a"}, shell: ptr("a,b")}, ""},
		{"up, given COMPOSE_PROFILES in the shell: the other profile there as well", []string{"up", "--dry-run", "--no-build"}, false,
			given{shell: ptr("a")}, given{shell: ptr("a,b")}, "db,web"},
		{"config, given COMPOSE_PROFILES in the shell: the other profile there as well", []string{"config", "--services"}, false,
			given{shell: ptr("a")}, given{shell: ptr("a,b")}, "db,web"},
		// A --profile added to a run that had COMPOSE_PROFILES takes its place:
		// db's profile alone is active, web is left out, nothing is refused.
		{"config, given COMPOSE_PROFILES: a --profile alone replaces it", []string{"config", "--services"}, false,
			given{shell: ptr("a")}, given{shell: ptr("a"), args: []string{"--profile", "b"}}, "db"},
		{"config, given --profile: another --profile", []string{"config", "--services"}, false,
			given{args: []string{"--profile", "a"}}, given{args: []string{"--profile", "a", "--profile", "b"}}, "db,web"},
		// The profile came from the `.env`: that is where to add the other. In
		// the shell instead, COMPOSE_PROFILES replaces the `.env`'s — the
		// refusal says so — and db's profile alone is active.
		{"config, given COMPOSE_PROFILES in the .env: the other profile there as well", []string{"config", "--services"}, false,
			given{dotenv: "COMPOSE_PROFILES=a\n"}, given{dotenv: "COMPOSE_PROFILES=a,b\n"}, "db,web"},
		{"config, given COMPOSE_PROFILES in the .env: in the shell instead, it replaces", []string{"config", "--services"}, false,
			given{dotenv: "COMPOSE_PROFILES=a\n"}, given{dotenv: "COMPOSE_PROFILES=a\n", shell: ptr("b")}, "db"},
		{"up, given COMPOSE_PROFILES in an --env-file: the other profile there as well", []string{"up", "--dry-run", "--no-build"}, false,
			given{envFile: "COMPOSE_PROFILES=a\n"}, given{envFile: "COMPOSE_PROFILES=a,b\n"}, "db,web"},
		{"up, given COMPOSE_PROFILES in the .env: the other profile there as well", []string{"up", "--dry-run", "--no-build"}, false,
			given{dotenv: "COMPOSE_PROFILES=a\n"}, given{dotenv: "COMPOSE_PROFILES=a,b\n"}, "db,web"},
		{"config, given COMPOSE_PROFILES in an --env-file: the other profile there as well", []string{"config", "--services"}, false,
			given{envFile: "COMPOSE_PROFILES=a\n"}, given{envFile: "COMPOSE_PROFILES=a,b\n"}, "db,web"},
		// The flag replaces both: an empty one, too, is the flag.
		{"config, given COMPOSE_PROFILES in the .env: --profile '' replaces it with nothing", []string{"config", "--services"}, false,
			given{dotenv: "COMPOSE_PROFILES=a\n"}, given{dotenv: "COMPOSE_PROFILES=a\n", args: []string{"--profile", ""}}, "-"},
		// The profile came from the compose file's own directory's `.env`
		// (COMPOSE_FILE chose a file elsewhere): that is a place this run reads,
		// and so is the working directory's `.env` — over it.
		{"config, given COMPOSE_PROFILES in the file's directory's .env: the other profile there as well", []string{"config", "--services"}, false,
			given{composeFile: "sub/x.yaml", subenv: "COMPOSE_PROFILES=a\n"}, given{composeFile: "sub/x.yaml", subenv: "COMPOSE_PROFILES=a,b\n"}, "db,web"},
		{"config, given COMPOSE_PROFILES in the file's directory's .env: in the working directory's, beside it", []string{"config", "--services"}, false,
			given{composeFile: "sub/x.yaml", subenv: "COMPOSE_PROFILES=a\n"}, given{composeFile: "sub/x.yaml", subenv: "COMPOSE_PROFILES=a\n", dotenv: "COMPOSE_PROFILES=a,b\n"}, "db,web"},
		{"run: another --profile", []string{"run", "--rm", "web", "true"}, false,
			given{args: []string{"--profile", "a"}}, given{args: []string{"--profile", "a", "--profile", "b"}}, "db,web"},
		{"run, given COMPOSE_PROFILES in the shell: the other profile there as well", []string{"run", "--rm", "web", "true"}, false,
			given{shell: ptr("a")}, given{shell: ptr("a,b")}, "db,web"},
		{"run, given COMPOSE_PROFILES in the .env: the other profile there as well", []string{"run", "--rm", "web", "true"}, false,
			given{dotenv: "COMPOSE_PROFILES=a\n"}, given{dotenv: "COMPOSE_PROFILES=a,b\n"}, "db,web"},
		{"run, given COMPOSE_PROFILES in an --env-file: the other profile there as well", []string{"run", "--rm", "web", "true"}, false,
			given{envFile: "COMPOSE_PROFILES=a\n"}, given{envFile: "COMPOSE_PROFILES=a,b\n"}, "db,web"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			fakeShim(t)
			t.Setenv("XDG_STATE_HOME", t.TempDir())
			dir := filepath.Join(t.TempDir(), "proj")
			if err := os.MkdirAll(dir, 0o755); err != nil {
				t.Fatal(err)
			}
			write(t, filepath.Join(dir, "compose.yaml"), compose)
			if err := os.Mkdir(filepath.Join(dir, "sub"), 0o755); err != nil {
				t.Fatal(err)
			}
			write(t, filepath.Join(dir, "sub", "x.yaml"), compose)
			t.Chdir(dir)
			for _, name := range []string{"COMPOSE_PROJECT_NAME", "COMPOSE_PATH_SEPARATOR"} {
				setOrUnset(t, name, nil)
			}
			// arrange writes the env files a run reads and returns its arguments.
			arrange := func(g given) []string {
				os.Remove(filepath.Join(dir, ".env"))
				os.Remove(filepath.Join(dir, "sub", ".env"))
				if g.dotenv != "" {
					write(t, filepath.Join(dir, ".env"), g.dotenv)
				}
				if g.subenv != "" {
					write(t, filepath.Join(dir, "sub", ".env"), g.subenv)
				}
				var composeFile *string
				if g.composeFile != "" {
					composeFile = ptr(g.composeFile)
				}
				setOrUnset(t, "COMPOSE_FILE", composeFile)
				args := append([]string{}, g.args...)
				if g.envFile != "" {
					write(t, filepath.Join(dir, "cf.env"), g.envFile)
					args = append(args, "--env-file", "cf.env")
				}
				setOrUnset(t, "COMPOSE_PROFILES", g.shell)
				return args
			}
			out, stderr, err := runSplit(t, append(arrange(tc.first), tc.exit...)...)
			if err == nil {
				t.Fatalf("web depends on db, whose profile is not active: want it refused, got:\n%s%s", out, stderr)
			}
			const refusal = `depends on "db", whose profile is not active`
			for _, want := range []string{refusal, "another --profile in a run that has one", "COMPOSE_PROFILES in a run with no --profile", "in the shell replaces one in the .env", "none of them add up"} {
				if !strings.Contains(err.Error(), want) {
					t.Errorf("the refusal should say %q, got: %v", want, err)
				}
			}
			if strings.Contains(err.Error(), "name it explicitly") != tc.canName {
				t.Errorf("naming the service is a way out of this exit: %v; got: %v", tc.canName, err)
			}
			// Following it, and asking `config --services` what is active then.
			out, _, err = runSplit(t, append(arrange(tc.then), "config", "--services")...)
			got := strings.Fields(out)
			sort.Strings(got)
			switch {
			case tc.wantServices == "":
				if err == nil || !strings.Contains(err.Error(), refusal) {
					t.Errorf("want it refused still, with the same refusal; got services %v, %v", got, err)
				}
			case tc.wantServices == "-":
				if err != nil || len(got) != 0 {
					t.Errorf("following the refusal should leave no service active; got %v, %v", got, err)
				}
			case err != nil || strings.Join(got, ",") != tc.wantServices:
				t.Errorf("following the refusal should come to %q; got %v, %v", tc.wantServices, got, err)
			}
		})
	}
}

// Naming the dependency is `up`'s way out for a service that only its name enables: `up web db` reads db beside web and starts both, where `up web` is refused. For a service the run
// reads without a name — `web` behind a profile that `--profile a` turns on — it is not: `up db web` is refused as `up` is, and the refusal does not say to name it (docker compose
// v5.5.1, measured, #1973); enabling db's profile beside the active ones is the way out, and `--profile a --profile b` accepts it.
func TestNamingTheGatedDependencyIsUpsWayOutOnlyForAServiceANameEnables(t *testing.T) {
	fakeShim(t)
	t.Setenv("XDG_STATE_HOME", t.TempDir())
	dir := filepath.Join(t.TempDir(), "proj")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatal(err)
	}
	write(t, filepath.Join(dir, "compose.yaml"), "services:\n  web:\n    image: alpine:3\n    profiles: [a]\n    depends_on: [db]\n  db:\n    image: alpine:3\n    profiles: [b]\n")
	t.Chdir(dir)
	for _, name := range []string{"COMPOSE_PROJECT_NAME", "COMPOSE_PATH_SEPARATOR", "COMPOSE_FILE", "COMPOSE_PROFILES"} {
		setOrUnset(t, name, nil)
	}
	// web is enabled by its name alone: naming db is the way out.
	if _, _, err := runSplit(t, "up", "--dry-run", "--no-build", "web"); err == nil || !strings.Contains(err.Error(), "name it explicitly") {
		t.Fatalf("want it refused, naming a way out; got: %v", err)
	}
	out, err := run(t, "up", "--dry-run", "--no-build", "web", "db")
	if err != nil {
		t.Fatalf("naming db beside web should be accepted; got: %v\n%s", err, out)
	}
	if !strings.Contains(out, "db") || !strings.Contains(out, "web") {
		t.Errorf("both should be in the plan; got:\n%s", out)
	}
	// web is read without a name (--profile a): naming db is no way out, and the refusal does not say it is.
	if _, _, err := runSplit(t, "--profile", "a", "up", "--dry-run", "--no-build"); err == nil || strings.Contains(err.Error(), "name it explicitly") || !strings.Contains(err.Error(), "whose profile is not active") {
		t.Fatalf("want it refused, without advice to name it; got: %v", err)
	}
	if out, _, err := runSplit(t, "--profile", "a", "up", "--dry-run", "--no-build", "db", "web"); err == nil || !strings.Contains(err.Error(), "whose profile is not active") {
		t.Fatalf("naming db beside a service the run reads without a name should be refused; got: %v\n%s", err, out)
	}
	if out, err := run(t, "--profile", "a", "--profile", "b", "up", "--dry-run", "--no-build"); err != nil || !strings.Contains(out, "db") {
		t.Fatalf("enabling db's profile beside the active ones should be accepted; got: %v\n%s", err, out)
	}
}

// A service with no `profiles:` that depends on a gated one is read without a name whatever `up` is given: `up other db` is refused as `up other` is, and neither says to name db (docker
// compose v5.5.1, measured, #1973); a dependency that shares the profile the run has on is fine.
func TestNamingTheGatedDependencyOfAnUngatedServiceIsNoWayOut(t *testing.T) {
	fakeShim(t)
	t.Setenv("XDG_STATE_HOME", t.TempDir())
	dir := filepath.Join(t.TempDir(), "proj")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatal(err)
	}
	write(t, filepath.Join(dir, "compose.yaml"), "services:\n  other:\n    image: alpine:3\n    depends_on: [db]\n  db:\n    image: alpine:3\n    profiles: [g]\n")
	t.Chdir(dir)
	for _, name := range []string{"COMPOSE_PROJECT_NAME", "COMPOSE_PATH_SEPARATOR", "COMPOSE_FILE", "COMPOSE_PROFILES"} {
		setOrUnset(t, name, nil)
	}
	for _, args := range [][]string{{"up", "--dry-run", "--no-build", "other"}, {"up", "--dry-run", "--no-build", "other", "db"}, {"up", "--dry-run", "--no-build", "db", "other"}} {
		if _, _, err := runSplit(t, args...); err == nil || strings.Contains(err.Error(), "name it explicitly") || !strings.Contains(err.Error(), `"db", whose profile is not active`) {
			t.Errorf("%v: want it refused, without advice to name it; got: %v", args, err)
		}
	}
	if out, err := run(t, "--profile", "g", "up", "--dry-run", "--no-build", "other"); err != nil || !strings.Contains(out, "db") {
		t.Errorf("the profile that enables db should be accepted; got: %v\n%s", err, out)
	}
}

// …and `run`, `build` and `pull` hold it the same way, naming the dependency or not (`run db true` on `other` -> `db`[g] is refused as `run other true` is); a dependency written
// `required: false` is no fault whatever it points at, and naming it is fine (docker compose v5.5.1, measured, #1973).
func TestTheGatedDependencyOfAServiceReadWithoutANameInRunBuildPullAndWhenOptional(t *testing.T) {
	fakeShim(t)
	t.Setenv("XDG_STATE_HOME", t.TempDir())
	for _, tc := range []struct {
		name, deps string
		args       [][]string
		refused    bool
	}{
		{"required", "[db]", [][]string{{"run", "--rm", "db", "true"}, {"run", "--rm", "other", "true"}, {"up", "--dry-run", "--no-build", "db"}}, true},
		{"not required", "{db: {condition: service_started, required: false}}", [][]string{{"run", "--rm", "db", "true"}, {"up", "--dry-run", "--no-build", "other", "db"}, {"up", "--dry-run", "--no-build", "db"}}, false},
	} {
		t.Run(tc.name, func(t *testing.T) {
			dir := filepath.Join(t.TempDir(), "proj")
			if err := os.MkdirAll(dir, 0o755); err != nil {
				t.Fatal(err)
			}
			write(t, filepath.Join(dir, "compose.yaml"), "services:\n  other:\n    image: alpine:3\n    depends_on: "+tc.deps+"\n  db:\n    image: alpine:3\n    profiles: [g]\n")
			t.Chdir(dir)
			for _, name := range []string{"COMPOSE_PROJECT_NAME", "COMPOSE_PATH_SEPARATOR", "COMPOSE_FILE", "COMPOSE_PROFILES"} {
				setOrUnset(t, name, nil)
			}
			for _, args := range tc.args {
				_, _, err := runSplit(t, args...)
				refusedOverIt := err != nil && strings.Contains(err.Error(), `"db", whose profile is not active`)
				if refusedOverIt != tc.refused {
					t.Errorf("%v: refused over the gated dependency = %v, docker compose: %v (err %v)", args, refusedOverIt, tc.refused, err)
				}
			}
		})
	}
}

// The note about what is left under the project's former name says how to
// reach it: `opossum -p <former> down`. That command reads a compose file, and
// has to read the one this run read — a run given `-f` is reading a file that
// the command, typed in the same directory without it, would not — and reach
// the containers' names, which carry the DNS domain. So the command carries
// the rest of the run's root flags, and is followed here.
func TestTheFormerNamesCommandReadsWhatThisRunRead(t *testing.T) {
	for _, tc := range []struct {
		name     string
		args     []string
		domain   string
		wantFlag string
	}{
		{"named by -f", []string{"-f", "sub/x.yaml"}, "opossum", " -f sub/x.yaml "},
		{"with a DNS domain", []string{"-f", "sub/x.yaml", "--dns-domain", "foo"}, "foo", " --dns-domain foo "},
	} {
		t.Run(tc.name, func(t *testing.T) {
			log := fakeShim(t)
			t.Setenv("XDG_STATE_HOME", t.TempDir())
			root := t.TempDir()
			dir := filepath.Join(root, "proj")
			if err := os.MkdirAll(filepath.Join(dir, "sub"), 0o755); err != nil {
				t.Fatal(err)
			}
			// The working directory's own file describes another service: what
			// a command that forgot -f would act on.
			write(t, filepath.Join(dir, "compose.yaml"), "services:\n  other:\n    image: alpine:3\n")
			write(t, filepath.Join(dir, "sub", "x.yaml"), "services:\n  web:\n    image: alpine:3\n")
			write(t, filepath.Join(dir, "sub", ".env"), "COMPOSE_PROJECT_NAME=newname\n")
			t.Chdir(dir)
			for _, name := range []string{"COMPOSE_PROJECT_NAME", "COMPOSE_PATH_SEPARATOR", "COMPOSE_FILE", "COMPOSE_PROFILES"} {
				setOrUnset(t, name, nil)
			}
			left := "web.sub." + tc.domain
			t.Setenv("CONTAINER_LS", `[{"status":{"state":"running"},"configuration":{"id":"`+left+`","labels":{"opossum.project":"sub"}}}]`)
			_, stderr, err := runSplit(t, append(append([]string{}, tc.args...), "ps")...)
			if err != nil {
				t.Fatalf("ps: %v\n%s", err, stderr)
			}
			_, rest, ok := strings.Cut(stderr, "`opossum -p sub")
			if !ok {
				t.Fatalf("the note should say how to reach what is left under the former name; got:\n%s", stderr)
			}
			command, _, _ := strings.Cut("opossum -p sub"+rest, "`")
			if !strings.Contains(command+" ", tc.wantFlag) {
				t.Errorf("the command should carry %q, got: %s", tc.wantFlag, command)
			}
			_, argv := shellReads(t, root, command)
			before := len(log())
			if out, err := run(t, argv...); err != nil {
				t.Fatalf("following the note (%s) failed: %v\n%s", command, err, out)
			}
			var reached, other bool
			for _, l := range log()[before:] {
				if strings.Contains(l, left) {
					reached = true
				}
				if strings.Contains(l, "other.") {
					other = true
				}
			}
			if !reached || other {
				t.Errorf("following the note (%s) should reach %s and not the working directory's file's service; shim saw:\n%s", command, left, strings.Join(log()[before:], "\n"))
			}
		})
	}
}

// Every orchestrator a command loads is told this run's root flags, so that
// what it prints for the user to type carries them (watch's next steps).
func TestTheOrchestratorIsToldThisRunsFlags(t *testing.T) {
	fakeShim(t)
	dir := filepath.Join(t.TempDir(), "proj")
	if err := os.MkdirAll(filepath.Join(dir, "sub"), 0o755); err != nil {
		t.Fatal(err)
	}
	write(t, filepath.Join(dir, "sub", "x.yaml"), "services:\n  web:\n    image: alpine:3\n")
	t.Chdir(dir)
	for _, name := range []string{"COMPOSE_PROJECT_NAME", "COMPOSE_PATH_SEPARATOR", "COMPOSE_FILE", "COMPOSE_PROFILES"} {
		setOrUnset(t, name, nil)
	}
	root := newRootCmd()
	root.SetArgs([]string{"-f", "sub/x.yaml", "-p", "my proj", "--dns-domain", "foo", "config"})
	root.SetOut(&strings.Builder{})
	if err := root.Execute(); err != nil {
		t.Fatal(err)
	}
	o, err := loadOrchestrator(&strings.Builder{})
	if err != nil {
		t.Fatal(err)
	}
	if got, want := o.RunFlags(), " -f sub/x.yaml -p 'my proj' --dns-domain foo"; got != want {
		t.Errorf("run flags = %q, want %q", got, want)
	}
}
