package main

import (
	"strings"
	"testing"
)

// A service the run reads without a name — no `profiles:`, or a profile turned on — is held to what the run reads without a name, and not helped by
// a service another one names: `stop web` on web (g) -> db (g) is refused for an unrelated `other` (no profile) that depends on db, as the name carries
// db for web and not for `other` (docker compose v5.5.1, `stop`, `kill` and `logs`, every row its rc; `start` is left to the rows of
// TestTheCommandsThatTakeANameReadTheDependenciesOfEveryServiceTheRunReads, as it refuses for a container that is not there) (#1831).
func TestAServiceTheRunReadsWithoutANameIsNotHelpedByAnotherOnesName(t *testing.T) {
	files := map[string]string{
		"other (no profile) depends on db (g), which web (g) shares":                         "services:\n  web:\n    image: alpine\n    profiles: [g]\n    depends_on: [db]\n  db:\n    image: alpine\n    profiles: [g]\n  other:\n    image: alpine\n    depends_on: [db]\n",
		"db has two profiles (g, h)":                                                         "services:\n  web:\n    image: alpine\n    profiles: [g]\n    depends_on: [db]\n  db:\n    image: alpine\n    profiles: [g, h]\n  other:\n    image: alpine\n    depends_on: [db]\n",
		"no unrelated service":                                                               "services:\n  web:\n    image: alpine\n    profiles: [g]\n    depends_on: [db]\n  db:\n    image: alpine\n    profiles: [g]\n",
		"other (no profile) optionally depends on db (g)":                                    "services:\n  web:\n    image: alpine\n    profiles: [g]\n    depends_on: [db]\n  db:\n    image: alpine\n    profiles: [g]\n  other:\n    image: alpine\n    depends_on:\n      db: {condition: service_started, required: false}\n",
		"other (h) depends on db (g)":                                                        "services:\n  web:\n    image: alpine\n    profiles: [g]\n    depends_on: [db]\n  db:\n    image: alpine\n    profiles: [g]\n  other:\n    image: alpine\n    profiles: [h]\n    depends_on: [db]\n",
		"mid (no profile) depends on other (h), which depends on db (g)":                     "services:\n  web:\n    image: alpine\n    profiles: [g]\n    depends_on: [db]\n  db:\n    image: alpine\n    profiles: [g]\n  mid:\n    image: alpine\n    depends_on: [other]\n  other:\n    image: alpine\n    profiles: [h]\n    depends_on: [db]\n",
		"other (no profile) depends on mid (no profile), which depends on db (g)":            "services:\n  web:\n    image: alpine\n    profiles: [g]\n    depends_on: [db]\n  db:\n    image: alpine\n    profiles: [g]\n  mid:\n    image: alpine\n    depends_on: [db]\n  other:\n    image: alpine\n    depends_on: [mid]\n",
		"other (no profile) optionally depends on mid (no profile), which depends on db (g)": "services:\n  web:\n    image: alpine\n    profiles: [g]\n    depends_on: [db]\n  db:\n    image: alpine\n    profiles: [g]\n  mid:\n    image: alpine\n    depends_on: [db]\n  other:\n    image: alpine\n    depends_on:\n      mid: {condition: service_started, required: false}\n",
		"web (g, h) depends on db (h): the name and the profile both read web":               "services:\n  web:\n    image: alpine\n    profiles: [g, h]\n    depends_on: [db]\n  db:\n    image: alpine\n    profiles: [h]\n",
		"other (no profile) links to db (g)":                                                 "services:\n  web:\n    image: alpine\n    profiles: [g]\n    depends_on: [db]\n  db:\n    image: alpine\n    profiles: [g]\n  other:\n    image: alpine\n    links: [db]\n",
		"other (no profile) shares the network of db (g)":                                    "services:\n  web:\n    image: alpine\n    profiles: [g]\n    depends_on: [db]\n  db:\n    image: alpine\n    profiles: [g]\n  other:\n    image: alpine\n    network_mode: \"service:db\"\n",
		"other (no profile) takes volumes_from db (g)":                                       "services:\n  web:\n    image: alpine\n    profiles: [g]\n    depends_on: [db]\n  db:\n    image: alpine\n    profiles: [g]\n  other:\n    image: alpine\n    volumes_from: [db]\n",
	}
	for _, tc := range []struct {
		file, command, way string
		refused            bool
	}{
		{"other (no profile) depends on db (g), which web (g) shares", "stop web", "none", true},
		{"other (no profile) depends on db (g), which web (g) shares", "stop web", "--profile g", false},
		{"other (no profile) depends on db (g), which web (g) shares", "stop web", "--profile h", true},
		{"other (no profile) depends on db (g), which web (g) shares", "stop web", "--profile g --profile h", false},
		{"other (no profile) depends on db (g), which web (g) shares", "stop db", "none", true},
		{"other (no profile) depends on db (g), which web (g) shares", "stop db", "--profile g", false},
		{"other (no profile) depends on db (g), which web (g) shares", "stop db", "--profile h", true},
		{"other (no profile) depends on db (g), which web (g) shares", "stop db", "--profile g --profile h", false},
		{"other (no profile) depends on db (g), which web (g) shares", "kill web", "none", true},
		{"other (no profile) depends on db (g), which web (g) shares", "kill web", "--profile g", false},
		{"other (no profile) depends on db (g), which web (g) shares", "kill web", "--profile h", true},
		{"other (no profile) depends on db (g), which web (g) shares", "kill web", "--profile g --profile h", false},
		{"other (no profile) depends on db (g), which web (g) shares", "logs db", "none", true},
		{"other (no profile) depends on db (g), which web (g) shares", "logs db", "--profile g", false},
		{"other (no profile) depends on db (g), which web (g) shares", "logs db", "--profile h", true},
		{"other (no profile) depends on db (g), which web (g) shares", "logs db", "--profile g --profile h", false},
		{"other (no profile) depends on db (g), which web (g) shares", "stop web db", "none", true},
		{"other (no profile) depends on db (g), which web (g) shares", "stop web db", "--profile g", false},
		{"other (no profile) depends on db (g), which web (g) shares", "stop web db", "--profile h", true},
		{"other (no profile) depends on db (g), which web (g) shares", "stop web db", "--profile g --profile h", false},
		{"db has two profiles (g, h)", "stop web", "none", true},
		{"db has two profiles (g, h)", "stop web", "--profile g", false},
		{"db has two profiles (g, h)", "stop web", "--profile h", false},
		{"db has two profiles (g, h)", "stop web", "--profile g --profile h", false},
		{"db has two profiles (g, h)", "stop db", "none", true},
		{"db has two profiles (g, h)", "stop db", "--profile g", false},
		{"db has two profiles (g, h)", "stop db", "--profile h", false},
		{"db has two profiles (g, h)", "stop db", "--profile g --profile h", false},
		{"db has two profiles (g, h)", "kill web", "none", true},
		{"db has two profiles (g, h)", "kill web", "--profile g", false},
		{"db has two profiles (g, h)", "kill web", "--profile h", false},
		{"db has two profiles (g, h)", "kill web", "--profile g --profile h", false},
		{"db has two profiles (g, h)", "logs db", "none", true},
		{"db has two profiles (g, h)", "logs db", "--profile g", false},
		{"db has two profiles (g, h)", "logs db", "--profile h", false},
		{"db has two profiles (g, h)", "logs db", "--profile g --profile h", false},
		{"db has two profiles (g, h)", "stop web db", "none", true},
		{"db has two profiles (g, h)", "stop web db", "--profile g", false},
		{"db has two profiles (g, h)", "stop web db", "--profile h", false},
		{"db has two profiles (g, h)", "stop web db", "--profile g --profile h", false},
		{"no unrelated service", "stop web", "none", false},
		{"no unrelated service", "stop web", "--profile g", false},
		{"no unrelated service", "stop web", "--profile h", false},
		{"no unrelated service", "stop web", "--profile g --profile h", false},
		{"no unrelated service", "stop db", "none", false},
		{"no unrelated service", "stop db", "--profile g", false},
		{"no unrelated service", "stop db", "--profile h", false},
		{"no unrelated service", "stop db", "--profile g --profile h", false},
		{"no unrelated service", "kill web", "none", false},
		{"no unrelated service", "kill web", "--profile g", false},
		{"no unrelated service", "kill web", "--profile h", false},
		{"no unrelated service", "kill web", "--profile g --profile h", false},
		{"no unrelated service", "logs db", "none", false},
		{"no unrelated service", "logs db", "--profile g", false},
		{"no unrelated service", "logs db", "--profile h", false},
		{"no unrelated service", "logs db", "--profile g --profile h", false},
		{"no unrelated service", "stop web db", "none", false},
		{"no unrelated service", "stop web db", "--profile g", false},
		{"no unrelated service", "stop web db", "--profile h", false},
		{"no unrelated service", "stop web db", "--profile g --profile h", false},
		{"other (no profile) optionally depends on db (g)", "stop web", "none", false},
		{"other (no profile) optionally depends on db (g)", "stop web", "--profile g", false},
		{"other (no profile) optionally depends on db (g)", "stop web", "--profile h", false},
		{"other (no profile) optionally depends on db (g)", "stop web", "--profile g --profile h", false},
		{"other (no profile) optionally depends on db (g)", "stop db", "none", false},
		{"other (no profile) optionally depends on db (g)", "stop db", "--profile g", false},
		{"other (no profile) optionally depends on db (g)", "stop db", "--profile h", false},
		{"other (no profile) optionally depends on db (g)", "stop db", "--profile g --profile h", false},
		{"other (no profile) optionally depends on db (g)", "kill web", "none", false},
		{"other (no profile) optionally depends on db (g)", "kill web", "--profile g", false},
		{"other (no profile) optionally depends on db (g)", "kill web", "--profile h", false},
		{"other (no profile) optionally depends on db (g)", "kill web", "--profile g --profile h", false},
		{"other (no profile) optionally depends on db (g)", "logs db", "none", false},
		{"other (no profile) optionally depends on db (g)", "logs db", "--profile g", false},
		{"other (no profile) optionally depends on db (g)", "logs db", "--profile h", false},
		{"other (no profile) optionally depends on db (g)", "logs db", "--profile g --profile h", false},
		{"other (no profile) optionally depends on db (g)", "stop web db", "none", false},
		{"other (no profile) optionally depends on db (g)", "stop web db", "--profile g", false},
		{"other (no profile) optionally depends on db (g)", "stop web db", "--profile h", false},
		{"other (no profile) optionally depends on db (g)", "stop web db", "--profile g --profile h", false},
		{"other (h) depends on db (g)", "stop web", "none", false},
		{"other (h) depends on db (g)", "stop web", "--profile g", false},
		{"other (h) depends on db (g)", "stop web", "--profile h", true},
		{"other (h) depends on db (g)", "stop web", "--profile g --profile h", false},
		{"other (h) depends on db (g)", "stop db", "none", false},
		{"other (h) depends on db (g)", "stop db", "--profile g", false},
		{"other (h) depends on db (g)", "stop db", "--profile h", true},
		{"other (h) depends on db (g)", "stop db", "--profile g --profile h", false},
		{"other (h) depends on db (g)", "kill web", "none", false},
		{"other (h) depends on db (g)", "kill web", "--profile g", false},
		{"other (h) depends on db (g)", "kill web", "--profile h", true},
		{"other (h) depends on db (g)", "kill web", "--profile g --profile h", false},
		{"other (h) depends on db (g)", "logs db", "none", false},
		{"other (h) depends on db (g)", "logs db", "--profile g", false},
		{"other (h) depends on db (g)", "logs db", "--profile h", true},
		{"other (h) depends on db (g)", "logs db", "--profile g --profile h", false},
		{"other (h) depends on db (g)", "stop web db", "none", false},
		{"other (h) depends on db (g)", "stop web db", "--profile g", false},
		{"other (h) depends on db (g)", "stop web db", "--profile h", true},
		{"other (h) depends on db (g)", "stop web db", "--profile g --profile h", false},
		{"mid (no profile) depends on other (h), which depends on db (g)", "stop web", "none", true},
		{"mid (no profile) depends on other (h), which depends on db (g)", "stop web", "--profile g", true},
		{"mid (no profile) depends on other (h), which depends on db (g)", "stop web", "--profile h", true},
		{"mid (no profile) depends on other (h), which depends on db (g)", "stop web", "--profile g --profile h", false},
		{"mid (no profile) depends on other (h), which depends on db (g)", "stop db", "none", true},
		{"mid (no profile) depends on other (h), which depends on db (g)", "stop db", "--profile g", true},
		{"mid (no profile) depends on other (h), which depends on db (g)", "stop db", "--profile h", true},
		{"mid (no profile) depends on other (h), which depends on db (g)", "stop db", "--profile g --profile h", false},
		{"mid (no profile) depends on other (h), which depends on db (g)", "kill web", "none", true},
		{"mid (no profile) depends on other (h), which depends on db (g)", "kill web", "--profile g", true},
		{"mid (no profile) depends on other (h), which depends on db (g)", "kill web", "--profile h", true},
		{"mid (no profile) depends on other (h), which depends on db (g)", "kill web", "--profile g --profile h", false},
		{"mid (no profile) depends on other (h), which depends on db (g)", "logs db", "none", true},
		{"mid (no profile) depends on other (h), which depends on db (g)", "logs db", "--profile g", true},
		{"mid (no profile) depends on other (h), which depends on db (g)", "logs db", "--profile h", true},
		{"mid (no profile) depends on other (h), which depends on db (g)", "logs db", "--profile g --profile h", false},
		{"mid (no profile) depends on other (h), which depends on db (g)", "stop web db", "none", true},
		{"mid (no profile) depends on other (h), which depends on db (g)", "stop web db", "--profile g", true},
		{"mid (no profile) depends on other (h), which depends on db (g)", "stop web db", "--profile h", true},
		{"mid (no profile) depends on other (h), which depends on db (g)", "stop web db", "--profile g --profile h", false},
		{"other (no profile) depends on mid (no profile), which depends on db (g)", "stop web", "none", true},
		{"other (no profile) depends on mid (no profile), which depends on db (g)", "stop web", "--profile g", false},
		{"other (no profile) depends on mid (no profile), which depends on db (g)", "stop web", "--profile h", true},
		{"other (no profile) depends on mid (no profile), which depends on db (g)", "stop web", "--profile g --profile h", false},
		{"other (no profile) depends on mid (no profile), which depends on db (g)", "stop db", "none", true},
		{"other (no profile) depends on mid (no profile), which depends on db (g)", "stop db", "--profile g", false},
		{"other (no profile) depends on mid (no profile), which depends on db (g)", "stop db", "--profile h", true},
		{"other (no profile) depends on mid (no profile), which depends on db (g)", "stop db", "--profile g --profile h", false},
		{"other (no profile) depends on mid (no profile), which depends on db (g)", "kill web", "none", true},
		{"other (no profile) depends on mid (no profile), which depends on db (g)", "kill web", "--profile g", false},
		{"other (no profile) depends on mid (no profile), which depends on db (g)", "kill web", "--profile h", true},
		{"other (no profile) depends on mid (no profile), which depends on db (g)", "kill web", "--profile g --profile h", false},
		{"other (no profile) depends on mid (no profile), which depends on db (g)", "logs db", "none", true},
		{"other (no profile) depends on mid (no profile), which depends on db (g)", "logs db", "--profile g", false},
		{"other (no profile) depends on mid (no profile), which depends on db (g)", "logs db", "--profile h", true},
		{"other (no profile) depends on mid (no profile), which depends on db (g)", "logs db", "--profile g --profile h", false},
		{"other (no profile) depends on mid (no profile), which depends on db (g)", "stop web db", "none", true},
		{"other (no profile) depends on mid (no profile), which depends on db (g)", "stop web db", "--profile g", false},
		{"other (no profile) depends on mid (no profile), which depends on db (g)", "stop web db", "--profile h", true},
		{"other (no profile) depends on mid (no profile), which depends on db (g)", "stop web db", "--profile g --profile h", false},
		{"other (no profile) optionally depends on mid (no profile), which depends on db (g)", "stop web", "none", true},
		{"other (no profile) optionally depends on mid (no profile), which depends on db (g)", "stop web", "--profile g", false},
		{"other (no profile) optionally depends on mid (no profile), which depends on db (g)", "stop web", "--profile h", true},
		{"other (no profile) optionally depends on mid (no profile), which depends on db (g)", "stop web", "--profile g --profile h", false},
		{"other (no profile) optionally depends on mid (no profile), which depends on db (g)", "stop db", "none", true},
		{"other (no profile) optionally depends on mid (no profile), which depends on db (g)", "stop db", "--profile g", false},
		{"other (no profile) optionally depends on mid (no profile), which depends on db (g)", "stop db", "--profile h", true},
		{"other (no profile) optionally depends on mid (no profile), which depends on db (g)", "stop db", "--profile g --profile h", false},
		{"other (no profile) optionally depends on mid (no profile), which depends on db (g)", "kill web", "none", true},
		{"other (no profile) optionally depends on mid (no profile), which depends on db (g)", "kill web", "--profile g", false},
		{"other (no profile) optionally depends on mid (no profile), which depends on db (g)", "kill web", "--profile h", true},
		{"other (no profile) optionally depends on mid (no profile), which depends on db (g)", "kill web", "--profile g --profile h", false},
		{"other (no profile) optionally depends on mid (no profile), which depends on db (g)", "logs db", "none", true},
		{"other (no profile) optionally depends on mid (no profile), which depends on db (g)", "logs db", "--profile g", false},
		{"other (no profile) optionally depends on mid (no profile), which depends on db (g)", "logs db", "--profile h", true},
		{"other (no profile) optionally depends on mid (no profile), which depends on db (g)", "logs db", "--profile g --profile h", false},
		{"other (no profile) optionally depends on mid (no profile), which depends on db (g)", "stop web db", "none", true},
		{"other (no profile) optionally depends on mid (no profile), which depends on db (g)", "stop web db", "--profile g", false},
		{"other (no profile) optionally depends on mid (no profile), which depends on db (g)", "stop web db", "--profile h", true},
		{"other (no profile) optionally depends on mid (no profile), which depends on db (g)", "stop web db", "--profile g --profile h", false},
		{"web (g, h) depends on db (h): the name and the profile both read web", "stop web", "none", false},
		{"web (g, h) depends on db (h): the name and the profile both read web", "stop web", "--profile g", true},
		{"web (g, h) depends on db (h): the name and the profile both read web", "stop web", "--profile h", false},
		{"web (g, h) depends on db (h): the name and the profile both read web", "stop web", "--profile g --profile h", false},
		{"web (g, h) depends on db (h): the name and the profile both read web", "stop db", "none", false},
		{"web (g, h) depends on db (h): the name and the profile both read web", "stop db", "--profile g", true},
		{"web (g, h) depends on db (h): the name and the profile both read web", "stop db", "--profile h", false},
		{"web (g, h) depends on db (h): the name and the profile both read web", "stop db", "--profile g --profile h", false},
		{"web (g, h) depends on db (h): the name and the profile both read web", "kill web", "none", false},
		{"web (g, h) depends on db (h): the name and the profile both read web", "kill web", "--profile g", true},
		{"web (g, h) depends on db (h): the name and the profile both read web", "kill web", "--profile h", false},
		{"web (g, h) depends on db (h): the name and the profile both read web", "kill web", "--profile g --profile h", false},
		{"web (g, h) depends on db (h): the name and the profile both read web", "logs db", "none", false},
		{"web (g, h) depends on db (h): the name and the profile both read web", "logs db", "--profile g", true},
		{"web (g, h) depends on db (h): the name and the profile both read web", "logs db", "--profile h", false},
		{"web (g, h) depends on db (h): the name and the profile both read web", "logs db", "--profile g --profile h", false},
		{"web (g, h) depends on db (h): the name and the profile both read web", "stop web db", "none", false},
		{"web (g, h) depends on db (h): the name and the profile both read web", "stop web db", "--profile g", true},
		{"web (g, h) depends on db (h): the name and the profile both read web", "stop web db", "--profile h", false},
		{"web (g, h) depends on db (h): the name and the profile both read web", "stop web db", "--profile g --profile h", false},
		{"other (no profile) links to db (g)", "stop web", "none", true},
		{"other (no profile) links to db (g)", "stop web", "--profile g", false},
		{"other (no profile) links to db (g)", "stop web", "--profile h", true},
		{"other (no profile) links to db (g)", "stop web", "--profile g --profile h", false},
		{"other (no profile) links to db (g)", "stop db", "none", true},
		{"other (no profile) links to db (g)", "stop db", "--profile g", false},
		{"other (no profile) links to db (g)", "stop db", "--profile h", true},
		{"other (no profile) links to db (g)", "stop db", "--profile g --profile h", false},
		{"other (no profile) links to db (g)", "kill web", "none", true},
		{"other (no profile) links to db (g)", "kill web", "--profile g", false},
		{"other (no profile) links to db (g)", "kill web", "--profile h", true},
		{"other (no profile) links to db (g)", "kill web", "--profile g --profile h", false},
		{"other (no profile) links to db (g)", "logs db", "none", true},
		{"other (no profile) links to db (g)", "logs db", "--profile g", false},
		{"other (no profile) links to db (g)", "logs db", "--profile h", true},
		{"other (no profile) links to db (g)", "logs db", "--profile g --profile h", false},
		{"other (no profile) links to db (g)", "stop web db", "none", true},
		{"other (no profile) links to db (g)", "stop web db", "--profile g", false},
		{"other (no profile) links to db (g)", "stop web db", "--profile h", true},
		{"other (no profile) links to db (g)", "stop web db", "--profile g --profile h", false},
		{"other (no profile) shares the network of db (g)", "stop web", "none", true},
		{"other (no profile) shares the network of db (g)", "stop web", "--profile g", false},
		{"other (no profile) shares the network of db (g)", "stop web", "--profile h", true},
		{"other (no profile) shares the network of db (g)", "stop web", "--profile g --profile h", false},
		{"other (no profile) shares the network of db (g)", "stop db", "none", true},
		{"other (no profile) shares the network of db (g)", "stop db", "--profile g", false},
		{"other (no profile) shares the network of db (g)", "stop db", "--profile h", true},
		{"other (no profile) shares the network of db (g)", "stop db", "--profile g --profile h", false},
		{"other (no profile) shares the network of db (g)", "kill web", "none", true},
		{"other (no profile) shares the network of db (g)", "kill web", "--profile g", false},
		{"other (no profile) shares the network of db (g)", "kill web", "--profile h", true},
		{"other (no profile) shares the network of db (g)", "kill web", "--profile g --profile h", false},
		{"other (no profile) shares the network of db (g)", "logs db", "none", true},
		{"other (no profile) shares the network of db (g)", "logs db", "--profile g", false},
		{"other (no profile) shares the network of db (g)", "logs db", "--profile h", true},
		{"other (no profile) shares the network of db (g)", "logs db", "--profile g --profile h", false},
		{"other (no profile) shares the network of db (g)", "stop web db", "none", true},
		{"other (no profile) shares the network of db (g)", "stop web db", "--profile g", false},
		{"other (no profile) shares the network of db (g)", "stop web db", "--profile h", true},
		{"other (no profile) shares the network of db (g)", "stop web db", "--profile g --profile h", false},
		{"other (no profile) takes volumes_from db (g)", "stop web", "none", true},
		{"other (no profile) takes volumes_from db (g)", "stop web", "--profile g", false},
		{"other (no profile) takes volumes_from db (g)", "stop web", "--profile h", true},
		{"other (no profile) takes volumes_from db (g)", "stop web", "--profile g --profile h", false},
		{"other (no profile) takes volumes_from db (g)", "stop db", "none", true},
		{"other (no profile) takes volumes_from db (g)", "stop db", "--profile g", false},
		{"other (no profile) takes volumes_from db (g)", "stop db", "--profile h", true},
		{"other (no profile) takes volumes_from db (g)", "stop db", "--profile g --profile h", false},
		{"other (no profile) takes volumes_from db (g)", "kill web", "none", true},
		{"other (no profile) takes volumes_from db (g)", "kill web", "--profile g", false},
		{"other (no profile) takes volumes_from db (g)", "kill web", "--profile h", true},
		{"other (no profile) takes volumes_from db (g)", "kill web", "--profile g --profile h", false},
		{"other (no profile) takes volumes_from db (g)", "logs db", "none", true},
		{"other (no profile) takes volumes_from db (g)", "logs db", "--profile g", false},
		{"other (no profile) takes volumes_from db (g)", "logs db", "--profile h", true},
		{"other (no profile) takes volumes_from db (g)", "logs db", "--profile g --profile h", false},
		{"other (no profile) takes volumes_from db (g)", "stop web db", "none", true},
		{"other (no profile) takes volumes_from db (g)", "stop web db", "--profile g", false},
		{"other (no profile) takes volumes_from db (g)", "stop web db", "--profile h", true},
		{"other (no profile) takes volumes_from db (g)", "stop web db", "--profile g --profile h", false},
	} {
		t.Run(tc.file+": "+tc.command+" ("+tc.way+")", func(t *testing.T) {
			t.Setenv("XDG_STATE_HOME", t.TempDir())
			fakeShim(t)
			setOrUnset(t, "COMPOSE_PROFILES", nil)
			var flags []string
			if tc.way != "none" {
				flags = strings.Fields(tc.way)
			}
			args := append([]string{"-f", writeCompose(t, files[tc.file])}, flags...)
			out, err := run(t, append(args, strings.Fields(tc.command)...)...)
			if (err != nil) != tc.refused {
				t.Errorf("%s: err %v, docker compose refuses it: %v\n%s", tc.command, err, tc.refused, out)
			}
			// Every refusal here is for a service read without a name, which naming a service does not help: the words must not say it does.
			if tc.refused && err != nil && strings.Contains(err.Error()+out, "name it explicitly") {
				t.Errorf("%s: the refusal suggests naming the service, which docker compose does not let through:\n%s%v", tc.command, out, err)
			}
		})
	}
}
