package main

import (
	"strings"
	"testing"
)

// `stop`, `kill`, `logs` and `start` of a named service read the dependencies of every service the run reads — those with no `profiles:`
// and those a `--profile` or COMPOSE_PROFILES turns on — and not only of the service they are given: a broken one of an unrelated `other`
// stops `stop web` (#1801). Every row is docker compose v5.5.1's answer (rc 0 or not) for the same file, command and way of turning
// a profile on (`start` is asked only where docker compose refuses it for the dependency, not for a container that is not there).
func TestTheCommandsThatTakeANameReadTheDependenciesOfEveryServiceTheRunReads(t *testing.T) {
	files := map[string]string{
		"other (g) has an undefined dependency":                         "services:\n  web:\n    image: x\n  other:\n    image: y\n    profiles: [g]\n    depends_on: {nosuch: {condition: service_started}}\n",
		"other (ungated) has an undefined dependency":                   "services:\n  web:\n    image: x\n  other:\n    image: y\n    depends_on: {nosuch: {condition: service_started}}\n",
		"other (g) has an optional undefined dependency":                "services:\n  web:\n    image: x\n  other:\n    image: y\n    profiles: [g]\n    depends_on: {nosuch: {condition: service_started, required: false}}\n",
		"other (g) depends on c (h), which no profile turns on":         "services:\n  web:\n    image: x\n  other:\n    image: y\n    profiles: [g]\n    depends_on: [c]\n  c:\n    image: z\n    profiles: [h]\n",
		"other (g) depends on c (g), whose own dependency is undefined": "services:\n  web:\n    image: x\n  other:\n    image: y\n    profiles: [g]\n    depends_on: [c]\n  c:\n    image: z\n    profiles: [g]\n    depends_on: {nosuch: {condition: service_started}}\n",
		"other (g) links to a service that is not defined":              "services:\n  web:\n    image: x\n  other:\n    image: y\n    profiles: [g]\n    links: [nosuch]\n",
		"other (g) takes volumes_from a service that is not defined":    "services:\n  web:\n    image: x\n  other:\n    image: y\n    profiles: [g]\n    volumes_from: [nosuch]\n",
		"other (ungated) depends on c (h), which no profile turns on":   "services:\n  web:\n    image: x\n  other:\n    image: y\n    depends_on: [c]\n  c:\n    image: z\n    profiles: [h]\n",
		"other (ungated) optionally depends on c (h)":                   "services:\n  web:\n    image: x\n  other:\n    image: y\n    depends_on: {c: {condition: service_started, required: false}}\n  c:\n    image: z\n    profiles: [h]\n",
		"other (g, h) has an undefined dependency":                      "services:\n  web:\n    image: x\n  other:\n    image: y\n    profiles: [g, h]\n    depends_on: {nosuch: {condition: service_started}}\n",
	}
	ways := map[string]struct {
		flags []string
		env   map[string]string
	}{
		"none":                 {},
		"--profile g":          {flags: []string{"--profile", "g"}},
		"COMPOSE_PROFILES=g":   {env: map[string]string{"COMPOSE_PROFILES": "g"}},
		"--profile h":          {flags: []string{"--profile", "h"}},
		"COMPOSE_PROFILES=g,h": {env: map[string]string{"COMPOSE_PROFILES": "g,h"}},
	}
	for _, tc := range []struct {
		file, way, command string
		refused            bool
	}{
		{"other (g) has an undefined dependency", "none", "stop web", false},
		{"other (g) has an undefined dependency", "none", "kill web", false},
		{"other (g) has an undefined dependency", "none", "logs web", false},
		{"other (g) has an undefined dependency", "--profile g", "stop web", true},
		{"other (g) has an undefined dependency", "--profile g", "kill web", true},
		{"other (g) has an undefined dependency", "--profile g", "logs web", true},
		{"other (g) has an undefined dependency", "--profile g", "start web", true},
		{"other (g) has an undefined dependency", "COMPOSE_PROFILES=g", "stop web", true},
		{"other (g) has an undefined dependency", "COMPOSE_PROFILES=g", "kill web", true},
		{"other (g) has an undefined dependency", "COMPOSE_PROFILES=g", "logs web", true},
		{"other (g) has an undefined dependency", "COMPOSE_PROFILES=g", "start web", true},
		{"other (g) has an undefined dependency", "--profile h", "stop web", false},
		{"other (g) has an undefined dependency", "--profile h", "kill web", false},
		{"other (g) has an undefined dependency", "--profile h", "logs web", false},
		{"other (g) has an undefined dependency", "COMPOSE_PROFILES=g,h", "stop web", true},
		{"other (g) has an undefined dependency", "COMPOSE_PROFILES=g,h", "kill web", true},
		{"other (g) has an undefined dependency", "COMPOSE_PROFILES=g,h", "logs web", true},
		{"other (g) has an undefined dependency", "COMPOSE_PROFILES=g,h", "start web", true},
		{"other (ungated) has an undefined dependency", "none", "stop web", true},
		{"other (ungated) has an undefined dependency", "none", "kill web", true},
		{"other (ungated) has an undefined dependency", "none", "logs web", true},
		{"other (ungated) has an undefined dependency", "none", "start web", true},
		{"other (ungated) has an undefined dependency", "--profile g", "stop web", true},
		{"other (ungated) has an undefined dependency", "--profile g", "kill web", true},
		{"other (ungated) has an undefined dependency", "--profile g", "logs web", true},
		{"other (ungated) has an undefined dependency", "--profile g", "start web", true},
		{"other (ungated) has an undefined dependency", "COMPOSE_PROFILES=g", "stop web", true},
		{"other (ungated) has an undefined dependency", "COMPOSE_PROFILES=g", "kill web", true},
		{"other (ungated) has an undefined dependency", "COMPOSE_PROFILES=g", "logs web", true},
		{"other (ungated) has an undefined dependency", "COMPOSE_PROFILES=g", "start web", true},
		{"other (ungated) has an undefined dependency", "--profile h", "stop web", true},
		{"other (ungated) has an undefined dependency", "--profile h", "kill web", true},
		{"other (ungated) has an undefined dependency", "--profile h", "logs web", true},
		{"other (ungated) has an undefined dependency", "--profile h", "start web", true},
		{"other (ungated) has an undefined dependency", "COMPOSE_PROFILES=g,h", "stop web", true},
		{"other (ungated) has an undefined dependency", "COMPOSE_PROFILES=g,h", "kill web", true},
		{"other (ungated) has an undefined dependency", "COMPOSE_PROFILES=g,h", "logs web", true},
		{"other (ungated) has an undefined dependency", "COMPOSE_PROFILES=g,h", "start web", true},
		{"other (g) has an optional undefined dependency", "none", "stop web", false},
		{"other (g) has an optional undefined dependency", "none", "kill web", false},
		{"other (g) has an optional undefined dependency", "none", "logs web", false},
		{"other (g) has an optional undefined dependency", "--profile g", "stop web", true},
		{"other (g) has an optional undefined dependency", "--profile g", "kill web", true},
		{"other (g) has an optional undefined dependency", "--profile g", "logs web", true},
		{"other (g) has an optional undefined dependency", "--profile g", "start web", true},
		{"other (g) has an optional undefined dependency", "COMPOSE_PROFILES=g", "stop web", true},
		{"other (g) has an optional undefined dependency", "COMPOSE_PROFILES=g", "kill web", true},
		{"other (g) has an optional undefined dependency", "COMPOSE_PROFILES=g", "logs web", true},
		{"other (g) has an optional undefined dependency", "COMPOSE_PROFILES=g", "start web", true},
		{"other (g) has an optional undefined dependency", "--profile h", "stop web", false},
		{"other (g) has an optional undefined dependency", "--profile h", "kill web", false},
		{"other (g) has an optional undefined dependency", "--profile h", "logs web", false},
		{"other (g) has an optional undefined dependency", "COMPOSE_PROFILES=g,h", "stop web", true},
		{"other (g) has an optional undefined dependency", "COMPOSE_PROFILES=g,h", "kill web", true},
		{"other (g) has an optional undefined dependency", "COMPOSE_PROFILES=g,h", "logs web", true},
		{"other (g) has an optional undefined dependency", "COMPOSE_PROFILES=g,h", "start web", true},
		{"other (g) depends on c (h), which no profile turns on", "none", "stop web", false},
		{"other (g) depends on c (h), which no profile turns on", "none", "kill web", false},
		{"other (g) depends on c (h), which no profile turns on", "none", "logs web", false},
		{"other (g) depends on c (h), which no profile turns on", "--profile g", "stop web", true},
		{"other (g) depends on c (h), which no profile turns on", "--profile g", "kill web", true},
		{"other (g) depends on c (h), which no profile turns on", "--profile g", "logs web", true},
		{"other (g) depends on c (h), which no profile turns on", "--profile g", "start web", true},
		{"other (g) depends on c (h), which no profile turns on", "COMPOSE_PROFILES=g", "stop web", true},
		{"other (g) depends on c (h), which no profile turns on", "COMPOSE_PROFILES=g", "kill web", true},
		{"other (g) depends on c (h), which no profile turns on", "COMPOSE_PROFILES=g", "logs web", true},
		{"other (g) depends on c (h), which no profile turns on", "COMPOSE_PROFILES=g", "start web", true},
		{"other (g) depends on c (h), which no profile turns on", "--profile h", "stop web", false},
		{"other (g) depends on c (h), which no profile turns on", "--profile h", "kill web", false},
		{"other (g) depends on c (h), which no profile turns on", "--profile h", "logs web", false},
		{"other (g) depends on c (h), which no profile turns on", "COMPOSE_PROFILES=g,h", "stop web", false},
		{"other (g) depends on c (h), which no profile turns on", "COMPOSE_PROFILES=g,h", "kill web", false},
		{"other (g) depends on c (h), which no profile turns on", "COMPOSE_PROFILES=g,h", "logs web", false},
		{"other (g) depends on c (g), whose own dependency is undefined", "none", "stop web", false},
		{"other (g) depends on c (g), whose own dependency is undefined", "none", "kill web", false},
		{"other (g) depends on c (g), whose own dependency is undefined", "none", "logs web", false},
		{"other (g) depends on c (g), whose own dependency is undefined", "--profile g", "stop web", true},
		{"other (g) depends on c (g), whose own dependency is undefined", "--profile g", "kill web", true},
		{"other (g) depends on c (g), whose own dependency is undefined", "--profile g", "logs web", true},
		{"other (g) depends on c (g), whose own dependency is undefined", "--profile g", "start web", true},
		{"other (g) depends on c (g), whose own dependency is undefined", "COMPOSE_PROFILES=g", "stop web", true},
		{"other (g) depends on c (g), whose own dependency is undefined", "COMPOSE_PROFILES=g", "kill web", true},
		{"other (g) depends on c (g), whose own dependency is undefined", "COMPOSE_PROFILES=g", "logs web", true},
		{"other (g) depends on c (g), whose own dependency is undefined", "COMPOSE_PROFILES=g", "start web", true},
		{"other (g) depends on c (g), whose own dependency is undefined", "--profile h", "stop web", false},
		{"other (g) depends on c (g), whose own dependency is undefined", "--profile h", "kill web", false},
		{"other (g) depends on c (g), whose own dependency is undefined", "--profile h", "logs web", false},
		{"other (g) depends on c (g), whose own dependency is undefined", "COMPOSE_PROFILES=g,h", "stop web", true},
		{"other (g) depends on c (g), whose own dependency is undefined", "COMPOSE_PROFILES=g,h", "kill web", true},
		{"other (g) depends on c (g), whose own dependency is undefined", "COMPOSE_PROFILES=g,h", "logs web", true},
		{"other (g) depends on c (g), whose own dependency is undefined", "COMPOSE_PROFILES=g,h", "start web", true},
		{"other (g) links to a service that is not defined", "none", "stop web", false},
		{"other (g) links to a service that is not defined", "none", "kill web", false},
		{"other (g) links to a service that is not defined", "none", "logs web", false},
		{"other (g) links to a service that is not defined", "--profile g", "stop web", true},
		{"other (g) links to a service that is not defined", "--profile g", "kill web", true},
		{"other (g) links to a service that is not defined", "--profile g", "logs web", true},
		{"other (g) links to a service that is not defined", "--profile g", "start web", true},
		{"other (g) links to a service that is not defined", "COMPOSE_PROFILES=g", "stop web", true},
		{"other (g) links to a service that is not defined", "COMPOSE_PROFILES=g", "kill web", true},
		{"other (g) links to a service that is not defined", "COMPOSE_PROFILES=g", "logs web", true},
		{"other (g) links to a service that is not defined", "COMPOSE_PROFILES=g", "start web", true},
		{"other (g) links to a service that is not defined", "--profile h", "stop web", false},
		{"other (g) links to a service that is not defined", "--profile h", "kill web", false},
		{"other (g) links to a service that is not defined", "--profile h", "logs web", false},
		{"other (g) links to a service that is not defined", "COMPOSE_PROFILES=g,h", "stop web", true},
		{"other (g) links to a service that is not defined", "COMPOSE_PROFILES=g,h", "kill web", true},
		{"other (g) links to a service that is not defined", "COMPOSE_PROFILES=g,h", "logs web", true},
		{"other (g) links to a service that is not defined", "COMPOSE_PROFILES=g,h", "start web", true},
		{"other (g) takes volumes_from a service that is not defined", "none", "stop web", false},
		{"other (g) takes volumes_from a service that is not defined", "none", "kill web", false},
		{"other (g) takes volumes_from a service that is not defined", "none", "logs web", false},
		{"other (g) takes volumes_from a service that is not defined", "--profile g", "stop web", true},
		{"other (g) takes volumes_from a service that is not defined", "--profile g", "kill web", true},
		{"other (g) takes volumes_from a service that is not defined", "--profile g", "logs web", true},
		{"other (g) takes volumes_from a service that is not defined", "--profile g", "start web", true},
		{"other (g) takes volumes_from a service that is not defined", "COMPOSE_PROFILES=g", "stop web", true},
		{"other (g) takes volumes_from a service that is not defined", "COMPOSE_PROFILES=g", "kill web", true},
		{"other (g) takes volumes_from a service that is not defined", "COMPOSE_PROFILES=g", "logs web", true},
		{"other (g) takes volumes_from a service that is not defined", "COMPOSE_PROFILES=g", "start web", true},
		{"other (g) takes volumes_from a service that is not defined", "--profile h", "stop web", false},
		{"other (g) takes volumes_from a service that is not defined", "--profile h", "kill web", false},
		{"other (g) takes volumes_from a service that is not defined", "--profile h", "logs web", false},
		{"other (g) takes volumes_from a service that is not defined", "COMPOSE_PROFILES=g,h", "stop web", true},
		{"other (g) takes volumes_from a service that is not defined", "COMPOSE_PROFILES=g,h", "kill web", true},
		{"other (g) takes volumes_from a service that is not defined", "COMPOSE_PROFILES=g,h", "logs web", true},
		{"other (g) takes volumes_from a service that is not defined", "COMPOSE_PROFILES=g,h", "start web", true},
		{"other (ungated) depends on c (h), which no profile turns on", "none", "stop web", true},
		{"other (ungated) depends on c (h), which no profile turns on", "none", "kill web", true},
		{"other (ungated) depends on c (h), which no profile turns on", "none", "logs web", true},
		{"other (ungated) depends on c (h), which no profile turns on", "none", "start web", true},
		{"other (ungated) depends on c (h), which no profile turns on", "--profile g", "stop web", true},
		{"other (ungated) depends on c (h), which no profile turns on", "--profile g", "kill web", true},
		{"other (ungated) depends on c (h), which no profile turns on", "--profile g", "logs web", true},
		{"other (ungated) depends on c (h), which no profile turns on", "--profile g", "start web", true},
		{"other (ungated) depends on c (h), which no profile turns on", "COMPOSE_PROFILES=g", "stop web", true},
		{"other (ungated) depends on c (h), which no profile turns on", "COMPOSE_PROFILES=g", "kill web", true},
		{"other (ungated) depends on c (h), which no profile turns on", "COMPOSE_PROFILES=g", "logs web", true},
		{"other (ungated) depends on c (h), which no profile turns on", "COMPOSE_PROFILES=g", "start web", true},
		{"other (ungated) depends on c (h), which no profile turns on", "--profile h", "stop web", false},
		{"other (ungated) depends on c (h), which no profile turns on", "--profile h", "kill web", false},
		{"other (ungated) depends on c (h), which no profile turns on", "--profile h", "logs web", false},
		{"other (ungated) depends on c (h), which no profile turns on", "COMPOSE_PROFILES=g,h", "stop web", false},
		{"other (ungated) depends on c (h), which no profile turns on", "COMPOSE_PROFILES=g,h", "kill web", false},
		{"other (ungated) depends on c (h), which no profile turns on", "COMPOSE_PROFILES=g,h", "logs web", false},
		{"other (ungated) optionally depends on c (h)", "none", "stop web", false},
		{"other (ungated) optionally depends on c (h)", "none", "kill web", false},
		{"other (ungated) optionally depends on c (h)", "none", "logs web", false},
		{"other (ungated) optionally depends on c (h)", "--profile g", "stop web", false},
		{"other (ungated) optionally depends on c (h)", "--profile g", "kill web", false},
		{"other (ungated) optionally depends on c (h)", "--profile g", "logs web", false},
		{"other (ungated) optionally depends on c (h)", "COMPOSE_PROFILES=g", "stop web", false},
		{"other (ungated) optionally depends on c (h)", "COMPOSE_PROFILES=g", "kill web", false},
		{"other (ungated) optionally depends on c (h)", "COMPOSE_PROFILES=g", "logs web", false},
		{"other (ungated) optionally depends on c (h)", "--profile h", "stop web", false},
		{"other (ungated) optionally depends on c (h)", "--profile h", "kill web", false},
		{"other (ungated) optionally depends on c (h)", "--profile h", "logs web", false},
		{"other (ungated) optionally depends on c (h)", "COMPOSE_PROFILES=g,h", "stop web", false},
		{"other (ungated) optionally depends on c (h)", "COMPOSE_PROFILES=g,h", "kill web", false},
		{"other (ungated) optionally depends on c (h)", "COMPOSE_PROFILES=g,h", "logs web", false},
		{"other (g, h) has an undefined dependency", "none", "stop web", false},
		{"other (g, h) has an undefined dependency", "none", "kill web", false},
		{"other (g, h) has an undefined dependency", "none", "logs web", false},
		{"other (g, h) has an undefined dependency", "--profile g", "stop web", true},
		{"other (g, h) has an undefined dependency", "--profile g", "kill web", true},
		{"other (g, h) has an undefined dependency", "--profile g", "logs web", true},
		{"other (g, h) has an undefined dependency", "--profile g", "start web", true},
		{"other (g, h) has an undefined dependency", "COMPOSE_PROFILES=g", "stop web", true},
		{"other (g, h) has an undefined dependency", "COMPOSE_PROFILES=g", "kill web", true},
		{"other (g, h) has an undefined dependency", "COMPOSE_PROFILES=g", "logs web", true},
		{"other (g, h) has an undefined dependency", "COMPOSE_PROFILES=g", "start web", true},
		{"other (g, h) has an undefined dependency", "--profile h", "stop web", true},
		{"other (g, h) has an undefined dependency", "--profile h", "kill web", true},
		{"other (g, h) has an undefined dependency", "--profile h", "logs web", true},
		{"other (g, h) has an undefined dependency", "--profile h", "start web", true},
		{"other (g, h) has an undefined dependency", "COMPOSE_PROFILES=g,h", "stop web", true},
		{"other (g, h) has an undefined dependency", "COMPOSE_PROFILES=g,h", "kill web", true},
		{"other (g, h) has an undefined dependency", "COMPOSE_PROFILES=g,h", "logs web", true},
		{"other (g, h) has an undefined dependency", "COMPOSE_PROFILES=g,h", "start web", true},
	} {
		t.Run(tc.file+": "+tc.command+" ("+tc.way+")", func(t *testing.T) {
			t.Setenv("XDG_STATE_HOME", t.TempDir())
			fakeShim(t)
			setOrUnset(t, "COMPOSE_PROFILES", nil)
			way := ways[tc.way]
			for k, v := range way.env {
				t.Setenv(k, v)
			}
			args := append([]string{"-f", writeCompose(t, files[tc.file])}, way.flags...)
			out, err := run(t, append(args, strings.Fields(tc.command)...)...)
			if (err != nil) != tc.refused {
				t.Errorf("%s: err %v, docker compose refuses it: %v\n%s", tc.command, err, tc.refused, out)
			}
		})
	}
}
